### ISSUE TITLE
Ombi not picking up requested movies in Radarr & throwing "wrong error"

### ISSUE THREAD

**Issue by Garderoben** [tidusjar/Ombi#1219]
#### Ombi Version:

	2.1.1336

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Operating System:

Windows Server 2016

#### Applicable Logs (from `/logs/` directory or the Admin page):

[http://prntscr.com/eh12su](http://prntscr.com/eh12su)

`
This movie has already been added	Ombi.Core.MovieSender	Error	3/7/2017 11:09:09 AM
`

#### Problem Description:

Movie X shows up as Not Requested yet, but is added to Radarr. When pressing Request it throws wrong info.

#### Reproduction Steps:

Request a movie that is added to Radarr already.

**Comment by tidusjar** [comment]
Please try the Early Access version of Ombi?

**Comment by Garderoben** [comment]
Works, now it shows up as Requested.

Thanks, as always!

**Comment by tidusjar** [comment]
There was an API change in Radarr, so in the EAP version I fixed that.

It will go out in the next release.

**Comment by shaunj928** [comment]
Very new to Unraid and dockers. This app after the last updates seems to just stop working. Also, the update did not fix the issue the Ombi not see movies already requested in Radarr & throwing Could not add movie, please contact your administrator
