### ISSUE TITLE
Newsletter not listing new episodes added for existing shows

### ISSUE THREAD

**Issue by Stryk3r78** [tidusjar/Ombi#1264]
Ombi Version:
2.1.1538

Update Branch:
Early Access Preview

Media Sever:
Plex

Media Server Version:
1.4.3.3433

Operating System:
Windows 10

Problem Description:
Since the recent changes to the newsletter the new tv episodes section is now not listing any new episodes added from existing shows, but is only listing new episodes for shows that were newly added. Since new tv shows are not added regularly, it would really be nice if it could have all new eps for new and existing shows listed that were recently added. It used to do this fine before the recent changes.

Reproduction Steps:
Sending a test newsletter after adding a new episode for an existing show will not include the episode in the newsletter list. But if I add a new show, then add new episodes, those will show up in the newsletter.

**Comment by tidusjar** [comment]
Do you have episode searching on?

**Comment by Stryk3r78** [comment]
No it's off, I've never turned it on as I don't have any episodes in my Plex library that aren't in Sonarr. Like I mentioned it picks up newly added shows fine (for 1 week), but picks up existing shows now and it did before with episode searching off as well.

Is this a requirement now to make this work?

**Comment by tidusjar** [comment]
For Ombi to add episodes to the newsletter then we require episode searching.

Can you upgrade to the latest EAP version and I just pushed some fixes to the newsletter around thsi.

**Comment by Stryk3r78** [comment]
ok I have enabled episode searching and updated to EAP version 1554. Will send another test newsletter tomorrow to see if new eps are being added to the newsletter.

Thanks for your help.

**Comment by Stryk3r78** [comment]
Still seems like a no go, even after enabling episode searching and upgrading to the latest EAP it's still not working. 3 new movies and 3 new episodes for existing shows were downloaded last night, and only the movies are showing in the newsletter.

**Comment by tidusjar** [comment]
Are there any errors in the log? It's difficult to diagnose an issue
without knowing what has happened.

When did the episode cacher last run? Was it before the newsletter sent?

**Comment by Stryk3r78** [comment]
no errors in the logs, i manually ran the episode cacher last night after I enabled episode searching. I've run it again now even though it should run every 12 hours. It seems to complete very quickly though it says "success" immediately, whereas some other jobs take a few seconds to complete, but it's not leaving anything in the logs.

I'll give my server a full reboot and see if it makes any difference. The problem is difficult to trace as everything seems to be working and doesn't create any errors, it just doesn't seem to pickup that new episodes are added unless I've just added the show to Sonarr for the first time. then it works fine.

If there is something more I can look at to assist you please let me know, I'm just not sure what else to try?

**Comment by JDIacobbo** [comment]
I am also having this issue. Enable Episode Searching is on in the Plex settings. I have attached a copy of the log at Trace Level. 

Application Version:	2.1.1554
OS:	Windows 8/Windows Server 2012
System Version:	4.0.30319.42000
Branch:	Early Access Preview

Job Name	Last Run	
Plex Episode Cacher	Sun, 26 Mar 2017 15:25:38 GMT	
Database Backup	Sun, 26 Mar 2017 15:22:46 GMT	
Request Limit Reset	Sun, 26 Mar 2017 15:27:45 GMT	
Database Cleanup	Sun, 26 Mar 2017 15:44:37 GMT	
Sonarr Cacher	Sun, 26 Mar 2017 15:56:08 GMT	
CouchPotato Cacher	Mon, 06 Mar 2017 20:12:24 GMT	
Plex Availability Cacher	Sun, 26 Mar 2017 15:58:08 GMT	
Plex Cacher	Sun, 26 Mar 2017 15:53:34 GMT	
Plex User Checker	Sun, 26 Mar 2017 15:54:09 GMT	
Watcher Cacher	Sun, 26 Mar 2017 15:55:08 GMT	
Request Fault Queue Handler	Sun, 26 Mar 2017 15:15:45 GMT	
Recently Added Email Notification	Fri, 24 Mar 2017 11:00:04 GMT	
Radarr Cacher	Sun, 26 Mar 2017 15:53:11 GMT

[Ombi_Newsletter_Log.txt](https://github.com/tidusjar/Ombi/files/870873/Ombi_Newsletter_Log.txt)

**Comment by tidusjar** [comment]
So the episode searcher even if manually triggered will not run until 11 hours has passed since the last run (due to with Plex it is very resource consuming).

Can you guys open up your databased (Ombi.sqlite) with something like SQLiteBrowser and look at the PlexEpisodeContent table to see if there is anything in there?

**Comment by JDIacobbo** [comment]
> So the episode searcher even if manually triggered will not run until 11 hours has passed since the last run (due to with Plex it is very resource consuming).
> 
> Can you guys open up your databased (Ombi.sqlite) with something like SQLiteBrowser and look at the PlexEpisodeContent table to see if there is anything in there?

I checked the PlexEpisodes table of PlexRequests.sqlite and there is definitely content there (11618 items!). I tried again to run the newsletter, but this time I am generating a blank newsletter and nothing is getting emailed out.

**Comment by tidusjar** [comment]
It's possible that it's marked things as already sent.

Maybe try and clear out some stuff from the `RecentlyAddedLog` table?

**Comment by tidusjar** [comment]
> Maybe try and clear out the RecentlyAddedLog table?

Then run it again?

**Comment by Stryk3r78** [comment]
my PlexEpisode table is blank, but I see my existing shows as well as my movies listed in the PlexContent table, I don't have a PlexEpisodeContent table though.

I upgraded to the latest EAP, unchecked episode searching, re-checked episode searching and restarted OMBI, and it says it's "indexing my tv shows and movies" but the episode table is still blank. Still no errors in the logs.

**Comment by JDIacobbo** [comment]
- Ran `DELETE FROM RECENTLYADDEDLOG`
- Cleared Logs and set to Debug.
- Restarted the Ombi service.
- Ran test newsletter to admin.
- Received e-mail.

So I think we may have an improvement here. After clearing the recently added log and rerunning the newsletter, EVERYTHING was listed on the test newsletter. I'm assuming this will be resolved the next time the does its compare to the last (side note: is there a way to force this?). But listed under the TV series I am now seeing:

```
Season: 1, Episode: 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,

Season: 2, Episode: 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,

Season: 3, Episode: 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,

Season: 4, Episode: 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,
```

**Comment by tidusjar** [comment]
Excellent.

So yes it will show everything because Ombi thinks that this is the very first time it has run.
The next newsletter will will compare what is in your library to what has been sent, if there is stuff that hasn't been sent then we will send it.

**Comment by JDIacobbo** [comment]
> Excellent.
> 
> So yes it will show everything because Ombi thinks that this is the very first time it has run.
> The next newsletter will will compare what is in your library to what has been sent, if there is stuff that hasn't been sent then we will send it.

Is there a way to force the compare before the next scheduled run? I don't want to send my users the same email that almost broke my inbox!

**Comment by tidusjar** [comment]
It will do the compare when the schedule runs. It's part of the job :)

**Comment by CyberMew** [comment]
I'm also not getting newly added episodes. The title text is there in the email but the contents are  blank. Can we actually make the test newsletter useful by actually including the contents instead of an empty email? Send it but not mark the contents as sent.

**Comment by Stryk3r78** [comment]
My PlexEpisodes table is still empty, what can I do to fix this?

**Comment by tidusjar** [comment]
@Stryk3r78 It's probably because your either have episode searching disabled Or there is an error when trying to get the Plex Episodes. Can you find that error and raise a new issue?

**Comment by Stryk3r78** [comment]
Bu this was my original issue? Why did you close it? it's not resolved?

There are no errors and episode searching is Enabled. like I said I even turned it off and back on.

**Comment by tidusjar** [comment]
Sorry I must have misread it.

If there is no Episodes in your PlexEpisodes table then there is a problem with getting the episodes out of Plex. There would be some sort of error for this.

What is your log level set to?

**Comment by Stryk3r78** [comment]
Log level is set to Error. And this is all I see in there.

Begin executing GetProfiles call to Radarr for quality profiles	Ombi.Core.Setup	Info	3/29/2017 8:31:29 AM
Begin executing GetProfiles call to Sonarr for quality profiles	Ombi.Core.Setup	Info	3/29/2017 8:31:29 AM
Begin executing GetProfiles call to Sonarr for quality profiles	Ombi.Core.Setup	Info	3/29/2017 8:30:19 AM
Begin executing GetProfiles call to Radarr for quality profiles	Ombi.Core.Setup	Info	3/29/2017 8:30:19 AM

**Comment by Stryk3r78** [comment]
I set it to Trace, and now the logs are filling up with this:

Message	Area	Log Level	Date
Request made to http://192.168.2.99:32400/library/metadata/19029/children with status code OK. The response was	Ombi.Api.ApiRequest	Trace	3/30/2017 8:26:45 AM
Request made to http://192.168.2.99:32400/library/metadata/19029 with status code OK. The response was	Ombi.Api.ApiRequest	Trace	3/30/2017 8:26:45 AM
Request made to http://192.168.2.99:32400/library/metadata/65699/children with status code OK. The response was	Ombi.Api.ApiRequest	Trace	3/30/2017 8:26:45 AM
Request made to http://192.168.2.99:32400/library/metadata/65699 with status code OK. The response was	Ombi.Api.ApiRequest	Trace	3/30/2017 8:26:45 AM
Request made to http://192.168.2.99:32400/library/metadata/64404/children with status code OK. The response was	Ombi.Api.ApiRequest	Trace	3/30/2017 8:26:45 AM
Request made to http://192.168.2.99:32400/library/metadata/64404 with status code OK. The response was	Ombi.Api.ApiRequest	Trace	3/30/2017 8:26:45 AM
Request made to http://192.168.2.99:32400/library/metadata/2355/children with status code OK. The response was	Ombi.Api.ApiRequest	Trace	3/30/2017 8:26:45 AM
Request made to http://192.168.2.99:32400/library/metadata/2355 with status code OK. The response was	Ombi.Api.ApiRequest	Trace	3/30/2017 8:26:45 AM

seems this is normal, no?

**Comment by Stryk3r78** [comment]
set to debug, shows this:

Message	Area	Log Level	Date
Done albums	Ombi.Services.Jobs.PlexContentCacher	Debug	3/30/2017 8:26:50 AM
Done TV	Ombi.Services.Jobs.PlexContentCacher	Debug	3/30/2017 8:26:50 AM
Done movies	Ombi.Services.Jobs.PlexContentCacher	Debug	3/30/2017 8:26:47 AM
done all that, moving onto the DB now	Ombi.Services.Jobs.PlexContentCacher	Debug	3/30/2017 8:26:45 AM

**Comment by tidusjar** [comment]
Everything seems normal.

Can you open your database (with Ombi closed) and execute the following in SQLiteBrowser:
`DROP TABLE PlexEpisodes`
Press save then restart Ombi and wait for the Job to run (it will not run unless 11 hours have passed)

**Comment by Stryk3r78** [comment]
Done

Query executed successfully: DROP TABLE PlexEpisodes (took 1ms)

I restarted OMBI and it has recreated the table. What should I leave the error level at to see any problems? Debug? Error? Trace?

**Comment by tidusjar** [comment]
Just put it to error :)

**Comment by Stryk3r78** [comment]
ok thanks,

I there any way to force the job to run sooner? I have a fairly powerful server so I'm not too concerned about the resources but would like to not have to wait 11 hrs to see if this is working every time I make a change?

**Comment by tidusjar** [comment]
Not currently. It's hard coded in to make sure we don't constantly run it.
Nowa'days we don't really need that check. I'll remove it in a future
version.

**Comment by Stryk3r78** [comment]
So the weekly newsletter went out again with no tv shows episodes listed and my Plex Episodes table is still blank. No errors in the logs since I updated to to the new EAP yesterday at 5pm.

Message	Area	Log Level	Date
Begin executing GetProfiles call to Sonarr for quality profiles	Ombi.Core.Setup	Info	3/30/2017 4:59:44 PM
Begin executing GetProfiles call to Radarr for quality profiles	Ombi.Core.Setup	Info	3/30/2017 4:59:44 PM

**Comment by tidusjar** [comment]
Great. There is clearly a problem trying to get the episodes from Plex. If the table was populated then the newsletter wouldn't have an issue.

There must be an error in your log somewhere, if it fails it will always log an error.

**Comment by Stryk3r78** [comment]
Also seemed someone else opened a ticket for a similar if not the same issue #1297. It definitely seems to be a problem with populating the episodes table, as no matter what I do it is not adding any data into it. I have upgraded to the latest Plexpass server Version 1.5.2.3557 as well, so not sure if they've changed anything but I would think it should be giving me an error of some kind? But there no errors? I pasted exactly what is listed. Do I need to use a different log level than error?

**Comment by Stryk3r78** [comment]
shows it ran the episode caching job at around 4am my time. and as there is nothing in the logs since I started the service at 5pm yesterday.

Job Name	Last Run	
Plex Cacher	Fri, 31 Mar 2017 10:59:55 GMT	
Plex User Checker	Fri, 31 Mar 2017 11:48:46 GMT	
Watcher Cacher	Fri, 31 Mar 2017 11:01:45 GMT	
Plex Availability Cacher	Fri, 31 Mar 2017 11:49:45 GMT	
Plex Episode Cacher	Fri, 31 Mar 2017 09:09:45 GMT	
CouchPotato Cacher	Mon, 01 Jan 0001 00:00:00 GMT	
Request Fault Queue Handler	Fri, 31 Mar 2017 09:12:45 GMT	
Database Backup	Thu, 30 Mar 2017 21:19:45 GMT	
Request Limit Reset	Fri, 31 Mar 2017 09:24:45 GMT	
Database Cleanup	Thu, 30 Mar 2017 21:34:45 GMT	
Radarr Cacher	Fri, 31 Mar 2017 10:59:47 GMT	
Sonarr Cacher	Fri, 31 Mar 2017 11:02:46 GMT	
Recently Added Email Notification	Fri, 31 Mar 2017 11:00:04 GMT

**Comment by Shiroihige** [comment]
Im also having this issue.  I have episode searching turned on. Running Ombi v2.2.1591, Plex v1.5.2.3557.

No episodes get added to newsletter.  If I run the episode cacher manually, it doesn't add anything to the PlexEpisodes table.  With log level set to error, nothing is written to logs during any point of this manual run

**Comment by JDIacobbo** [comment]
So a week after clearing out the PlexEpisodes and RecentlyAddedLog table, I am not receiving episodes in the newsletter. The first newsletter that ran on Friday was blank. I added a movie and several new episodes, but the test email is only showing the movie. New episodes are not showing up.

**Comment by jablesR** [comment]
in my experience, New shows get added to the list, but new episodes of existing shows do not get added.

**Comment by Stryk3r78** [comment]
@jablesR that is exactly what this issues says in title and description. Also there are no errors in the logs to help track down the problem it seems, and there are about 3 issues opened right now reporting the same problem.

**Comment by jablesR** [comment]
@Stryk3r78 just trying to add to the discussion, new to this github thing. hoping we can help with the solution here as the newsletter is a great addition to ombi.

**Comment by jjlambkin** [comment]
@jablesR I agree. That would be nice to have. I dont think however that that is how the application is intended to behave. I could be wrong though. I am pretty sure I saw something along these lines in the feature suggestions area.

**Comment by Shiroihige** [comment]
I've been having this issue and just upgraded to the EAP to test another issue that was being fixed.  After upgrading the newsletter now included new shows that had been added and movies, but does not include individual episodes that been added.  So it seems to be an issue with how ombi finds individual episodes that are being added or something in that process chain.

**Comment by Stryk3r78** [comment]
I appreciate the confirmation that I'm not crazy or alone in this situation. I'm trying to provide more info for the devs but there isn't much to be able to provide as everything "works" fine, and new things are added fine but existing shows don't add.

@jjlambkin it used to work this way, they changed the way the newsletter works and this has been the result. before they used to just query the API and dump all teh results, this worked fine but ended up with duplicate results. Then Plex changed the API in a fairly recent plexpass version and the OMBI dev had to update to compensate as it was sending BLANK newsletters for a while.

Once they fixed that, ever since it has been checking for dupes and not sending them. but it seems it's not scraping the existing shows and now only added NEW eps for NEW shows. whereas before it was sending all new shows from the recently added TV api.

This is definetly not how it should work, as bascially now the tv section is empty as you don't always add a new TV show every week.

**Comment by gilbN** [comment]
@stryk3r78 yes. Looks to me that the tv show part of the newsletter works the same as the movie part. It processes a TV show as a movie and doesn't add it on a per episode basis but per show.

**Comment by Stryk3r78** [comment]
@Shiroihige the issue you are describing is the one I've had all along since the newsletter API scraping changes. It has always added newly added shows fine for me, just nothing from existing shows hence my issue title. 

My plex episodes table in blank even with episode searching turned on, but this doesn't seem to stop it from recognizing new show episodes. but alas, as soon as a week passes and that shows isn't "new" anymore any new eps downloaded are once again ignored and not listed. I must download about 20-30 new eps a week and nothing has been listed for about 3 weeks and counting whereas all my new movies are listed (and no longer adding dupes from previous weeks which I believe was part of teh changes that seem to be causing this new problem). I believe it's no longer scraping teh API and instead looking to the local plex episodes DB to find episodes and then comparing them against the recently added log DB table. 
Since the plex episodes table is blank.... it think nothing new is added and send the tv section blank,

But it doesn't log any error about not populating the table, and the job runs every 11 hours without issue from what I can tell. So I don't know what else to do??

**Comment by Stryk3r78** [comment]
@gilbN I concur, if I download a "new show" and add 5 episodes for it, it still only lists the show in the newsletter as 1 item, not 5 episodes like it should. And then the following week, it's not a "new show" anymore so it's not added even if new episodes are added.

but this still doesn't explxain why the epsiode table doesn't populate when it runs the episode scraper which is what I believe is the other part of the issue since as long as it's not recording a list of episodes it never knows what new or not.

**Comment by gilbN** [comment]
@stryk3r78 hmm. well it does list the episodes I have downloaded on new shows for me. http://m.imgur.com/UgWFYND

**Comment by Stryk3r78** [comment]
@gilbN that must be new, mine didn't show that episode list that last time it actually posted a new show on March 24th.

Just a MASSIVE cover photo and this text underneath.

Marvel's Iron Fist 2017

Genre: Drama, Action, Crime
After his family meets a tragic fate while on expedition in China, a young Rand is adopted by the people of the mystical lost city of K'un-Lun, where he's taught a magical fighting style. Years later, he returns to New York to fight crime.
________________________________________

**Comment by ofurpesi** [comment]
Got this when i ran the newletter job:

System.NullReferenceException: Object reference not set to an instance of an object. at Ombi.Services.Jobs.RecentlyAddedNewsletter.PlexRecentlyAddedNewsletter.GenerateTvHtml(IEnumerable`1 recenetlyAddedTv, StringBuilder sb) in C:\projects\requestplex\Ombi.Services\Jobs\RecentlyAddedNewsletter\PlexRecentlyAddedNewsletter.cs:line 334

Still not showing new episodes in the newsletter

**Comment by Stryk3r78** [comment]
I updated to the EAP version 1607 and seems this may be fixed now. I manually ran the episode cacher, and now it actually seems to run on demand. It took about a minute or so to run (before it just "Succeeded" instantly) and now my Plex Episodes table has content! But sending a test newsletter was still only showing my movies. 

So I stopped OMBI and opened my recentlyaddedlog table in SQL browser and deleted all the entries listed that didn't start with tt (ie not movies) as there was a couple hundred of them and I'm assuming these were all my shows in my library. Then I restarted OMBI, manually ran the plex cacher and episode cacher, and resent the newsletter. It took MUCH longer this time (about 5 mins as I think it was actually processing all the data finally) and it sent the newsletter with new episodes finally! Only problem was it looks like it sent everything in my library as being new even old stuff that's been there forever. I think it had marked all my tv shows in the recentlyaddedlog table so it was ignoring them but now I removed the entries from the table it's listing everything as new. This at least hopefully means the next time it runs it will only add the new stuff.

So I manually ran the Recently added email notification job and it seems to have sent the newsletter with all the tv shows. I can also confirm that my recentlyaddedlog table is FULL of entries from today. Running a new test newsletter is still showing a few tv shows with no episodes listed but the list is only 4 items vs all the items it was listing after I modify the recently added table. There's also a few movies listed as well, not sure why they weren't marked as "not new" when the newsletter send. But I will see tonight if the episodes that download today appear in tomorrow's test newsletter.

**Comment by Stryk3r78** [comment]
I also finally have some errors in the logs. Maybe this relates to the few shows that didn't purge from the newsletter after I modified the recentlyaddedlog table.

System.NullReferenceException: Object reference not set to an instance of an object. at Ombi.Services.Jobs.RecentlyAddedNewsletter.PlexRecentlyAddedNewsletter.GenerateTvHtml(IEnumerable`1 recenetlyAddedTv, StringBuilder sb) in C:\projects\requestplex\Ombi.Services\Jobs\RecentlyAddedNewsletter\PlexRecentlyAddedNewsletter.cs:line 334	Ombi.Services.Jobs.RecentlyAddedNewsletter.PlexRecentlyAddedNewsletter	Error	4/4/2017 4:20:56 PM
System.NullReferenceException: Object reference not set to an instance of an object. at Ombi.Api.TvMazeApi.ShowLookupByTheTvDbId(Int32 theTvDbId) in C:\projects\requestplex\Ombi.Api\TvMazeApi.cs:line 87	Ombi.Api.TvMazeApi	Error	4/4/2017 4:20:56 PM
System.NullReferenceException: Object reference not set to an instance of an object. at Ombi.Services.Jobs.RecentlyAddedNewsletter.PlexRecentlyAddedNewsletter.GenerateTvHtml(IEnumerable`1 recenetlyAddedTv, StringBuilder sb) in C:\projects\requestplex\Ombi.Services\Jobs\RecentlyAddedNewsletter\PlexRecentlyAddedNewsletter.cs:line 334	Ombi.Services.Jobs.RecentlyAddedNewsletter.PlexRecentlyAddedNewsletter	Error	4/4/2017 4:20:56 PM
Newtonsoft.Json.JsonSerializationException: Error converting value {null} to type 'System.Double'. Path 'runtime', line 1, position 181. ---> System.InvalidCastException: Null object cannot be converted to a value type. at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType) --- End of inner exception stack trace --- at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue) at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent) at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType) at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings) at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings) at Ombi.Api.TvMazeApi.ShowLookupByTheTvDbId(Int32 theTvDbId) in C:\projects\requestplex\Ombi.Api\TvMazeApi.cs:line 87	Ombi.Api.TvMazeApi	Error	4/4/2017 4:20:56 PM

**Comment by JDIacobbo** [comment]
> So I stopped OMBI and opened my recentlyaddedlog table in SQL browser and deleted all the entries listed that didn't start with tt (ie not movies) as there was a couple hundred of them and I'm assuming these were all my shows in my library. Then I restarted OMBI, manually ran the plex cacher and episode cacher, and resent the newsletter. It took MUCH longer this time (about 5 mins as I think it was actually processing all the data finally) and it sent the newsletter with new episodes finally! Only problem was it looks like it sent everything in my library as being new even old stuff that's been there forever. I think it had marked all my tv shows in the recentlyaddedlog table so it was ignoring them but now I removed the entries from the table it's listing everything as new. This at least hopefully means the next time it runs it will only add the new stuff

I did this same thing and thought it might work. But after clearing out the table, the next email sent out was blank, and the following email only grabbed recently added movies.

**Comment by elit3ge** [comment]
Ok, so latest EAP with episode searching on. Started an episode cache run and my logs are filling up with this, over and over cause my Ombi to crash and become unresponsive. I have to restart it every 15 mins with ep searching on, with it off not an issue.

```
System.InvalidOperationException: There is an error in XML document (0, 0). ---> System.Xml.XmlException: Root element is missing. at System.Xml.XmlTextReaderImpl.Throw (System.Exception e) [0x0002a] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo (System.String res) [0x00017] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReaderImpl.ParseDocumentContent () [0x0041e] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReaderImpl.Read () [0x00097] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReader.Read () [0x00000] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlReader.MoveToContent () [0x0004b] in <1140eab9e72948548294172a9716416d>:0 at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPlexEpisodeMetadata.Read11_MediaContainer () [0x00008] in <9e2adf50005347d8a1cd9a351c15e59e>:0 at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&) at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00038] in <8f2c484307284b51944a1a13a14c0266>:0 --- End of inner exception stack trace --- at System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.XmlReader xmlReader, System.String encodingStyle, System.Xml.Serialization.XmlDeserializationEvents events) [0x00139] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.XmlReader xmlReader, System.String encodingStyle) [0x00000] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.Serialization.XmlSerializer.Deserialize (System.IO.TextReader textReader) [0x0001c] in <1140eab9e72948548294172a9716416d>:0 at Ombi.Api.ApiRequest.DeserializeXml[T] (System.String input) [0x00017] in :0	Ombi.Api.ApiRequest	Error	4/5/2017 7:59:33 AM
System.InvalidOperationException: There is an error in XML document (0, 0). ---> System.Xml.XmlException: Root element is missing. at System.Xml.XmlTextReaderImpl.Throw (System.Exception e) [0x0002a] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo (System.String res) [0x00017] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReaderImpl.ParseDocumentContent () [0x0041e] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReaderImpl.Read () [0x00097] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReader.Read () [0x00000] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlReader.MoveToContent () [0x0004b] in <1140eab9e72948548294172a9716416d>:0 at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPlexEpisodeMetadata.Read11_MediaContainer () [0x00008] in <9e2adf50005347d8a1cd9a351c15e59e>:0 at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&) at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00038] in <8f2c484307284b51944a1a13a14c0266>:0 --- End of inner exception stack trace --- at System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.XmlReader xmlReader, System.String encodingStyle, System.Xml.Serialization.XmlDeserializationEvents events) [0x00139] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.XmlReader xmlReader, System.String encodingStyle) [0x00000] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.Serialization.XmlSerializer.Deserialize (System.IO.TextReader textReader) [0x0001c] in <1140eab9e72948548294172a9716416d>:0 at Ombi.Api.ApiRequest.DeserializeXml[T] (System.String input) [0x00017] in :0	Ombi.Api.ApiRequest	Error	4/5/2017 7:59:32 AM
System.InvalidOperationException: There is an error in XML document (0, 0). ---> System.Xml.XmlException: Root element is missing. at System.Xml.XmlTextReaderImpl.Throw (System.Exception e) [0x0002a] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo (System.String res) [0x00017] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReaderImpl.ParseDocumentContent () [0x0041e] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReaderImpl.Read () [0x00097] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReader.Read () [0x00000] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlReader.MoveToContent () [0x0004b] in <1140eab9e72948548294172a9716416d>:0 at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPlexEpisodeMetadata.Read11_MediaContainer () [0x00008] in <9e2adf50005347d8a1cd9a351c15e59e>:0 at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&) at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00038] in <8f2c484307284b51944a1a13a14c0266>:0 --- End of inner exception stack trace --- at System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.XmlReader xmlReader, System.String encodingStyle, System.Xml.Serialization.XmlDeserializationEvents events) [0x00139] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.XmlReader xmlReader, System.String encodingStyle) [0x00000] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.Serialization.XmlSerializer.Deserialize (System.IO.TextReader textReader) [0x0001c] in <1140eab9e72948548294172a9716416d>:0 at Ombi.Api.ApiRequest.DeserializeXml[T] (System.String input) [0x00017] in :0	Ombi.Api.ApiRequest	Error	4/5/2017 7:59:32 AM
System.InvalidOperationException: There is an error in XML document (0, 0). ---> System.Xml.XmlException: Root element is missing. at System.Xml.XmlTextReaderImpl.Throw (System.Exception e) [0x0002a] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo (System.String res) [0x00017] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReaderImpl.ParseDocumentContent () [0x0041e] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReaderImpl.Read () [0x00097] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReader.Read () [0x00000] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlReader.MoveToContent () [0x0004b] in <1140eab9e72948548294172a9716416d>:0 at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPlexEpisodeMetadata.Read11_MediaContainer () [0x00008] in <9e2adf50005347d8a1cd9a351c15e59e>:0 at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&) at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00038] in <8f2c484307284b51944a1a13a14c0266>:0 --- End of inner exception stack trace --- at System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.XmlReader xmlReader, System.String encodingStyle, System.Xml.Serialization.XmlDeserializationEvents events) [0x00139] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.XmlReader xmlReader, System.String encodingStyle) [0x00000] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.Serialization.XmlSerializer.Deserialize (System.IO.TextReader textReader) [0x0001c] in <1140eab9e72948548294172a9716416d>:0 at Ombi.Api.ApiRequest.DeserializeXml[T] (System.String input) [0x00017] in :0	Ombi.Api.ApiRequest	Error	4/5/2017 7:59:31 AM
System.InvalidOperationException: There is an error in XML document (0, 0). ---> System.Xml.XmlException: Root element is missing. at System.Xml.XmlTextReaderImpl.Throw (System.Exception e) [0x0002a] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo (System.String res) [0x00017] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReaderImpl.ParseDocumentContent () [0x0041e] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReaderImpl.Read () [0x00097] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReader.Read () [0x00000] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlReader.MoveToContent () [0x0004b] in <1140eab9e72948548294172a9716416d>:0 at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPlexEpisodeMetadata.Read11_MediaContainer () [0x00008] in <9e2adf50005347d8a1cd9a351c15e59e>:0 at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&) at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00038] in <8f2c484307284b51944a1a13a14c0266>:0 --- End of inner exception stack trace --- at System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.XmlReader xmlReader, System.String encodingStyle, System.Xml.Serialization.XmlDeserializationEvents events) [0x00139] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.XmlReader xmlReader, System.String encodingStyle) [0x00000] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.Serialization.XmlSerializer.Deserialize (System.IO.TextReader textReader) [0x0001c] in <1140eab9e72948548294172a9716416d>:0 at Ombi.Api.ApiRequest.DeserializeXml[T] (System.String input) [0x00017] in :0	Ombi.Api.ApiRequest	Error	4/5/2017 7:59:31 AM
System.InvalidOperationException: There is an error in XML document (0, 0). ---> System.Xml.XmlException: Root element is missing. at System.Xml.XmlTextReaderImpl.Throw (System.Exception e) [0x0002a] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo (System.String res) [0x00017] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReaderImpl.ParseDocumentContent () [0x0041e] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReaderImpl.Read () [0x00097] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReader.Read () [0x00000] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlReader.MoveToContent () [0x0004b] in <1140eab9e72948548294172a9716416d>:0 at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPlexEpisodeMetadata.Read11_MediaContainer () [0x00008] in <9e2adf50005347d8a1cd9a351c15e59e>:0 at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&) at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00038] in <8f2c484307284b51944a1a13a14c0266>:0 --- End of inner exception stack trace --- at System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.XmlReader xmlReader, System.String encodingStyle, System.Xml.Serialization.XmlDeserializationEvents events) [0x00139] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.XmlReader xmlReader, System.String encodingStyle) [0x00000] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.Serialization.XmlSerializer.Deserialize (System.IO.TextReader textReader) [0x0001c] in <1140eab9e72948548294172a9716416d>:0 at Ombi.Api.ApiRequest.DeserializeXml[T] (System.String input) [0x00017] in :0	Ombi.Api.ApiRequest	Error	4/5/2017 7:59:31 AM
System.InvalidOperationException: There is an error in XML document (0, 0). ---> System.Xml.XmlException: Root element is missing. at System.Xml.XmlTextReaderImpl.Throw (System.Exception e) [0x0002a] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo (System.String res) [0x00017] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReaderImpl.ParseDocumentContent () [0x0041e] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReaderImpl.Read () [0x00097] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReader.Read () [0x00000] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlReader.MoveToContent () [0x0004b] in <1140eab9e72948548294172a9716416d>:0 at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPlexEpisodeMetadata.Read11_MediaContainer () [0x00008] in <9e2adf50005347d8a1cd9a351c15e59e>:0 at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&) at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00038] in <8f2c484307284b51944a1a13a14c0266>:0 --- End of inner exception stack trace --- at System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.XmlReader xmlReader, System.String encodingStyle, System.Xml.Serialization.XmlDeserializationEvents events) [0x00139] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.XmlReader xmlReader, System.String encodingStyle) [0x00000] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.Serialization.XmlSerializer.Deserialize (System.IO.TextReader textReader) [0x0001c] in <1140eab9e72948548294172a9716416d>:0 at Ombi.Api.ApiRequest.DeserializeXml[T] (System.String input) [0x00017] in :0	Ombi.Api.ApiRequest	Error	4/5/2017 7:59:31 AM
System.InvalidOperationException: There is an error in XML document (0, 0). ---> System.Xml.XmlException: Root element is missing. at System.Xml.XmlTextReaderImpl.Throw (System.Exception e) [0x0002a] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo (System.String res) [0x00017] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReaderImpl.ParseDocumentContent () [0x0041e] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReaderImpl.Read () [0x00097] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReader.Read () [0x00000] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlReader.MoveToContent () [0x0004b] in <1140eab9e72948548294172a9716416d>:0 at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPlexEpisodeMetadata.Read11_MediaContainer () [0x00008] in <9e2adf50005347d8a1cd9a351c15e59e>:0 at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&) at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00038] in <8f2c484307284b51944a1a13a14c0266>:0 --- End of inner exception stack trace --- at System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.XmlReader xmlReader, System.String encodingStyle, System.Xml.Serialization.XmlDeserializationEvents events) [0x00139] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.XmlReader xmlReader, System.String encodingStyle) [0x00000] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.Serialization.XmlSerializer.Deserialize (System.IO.TextReader textReader) [0x0001c] in <1140eab9e72948548294172a9716416d>:0 at Ombi.Api.ApiRequest.DeserializeXml[T] (System.String input) [0x00017] in :0	Ombi.Api.ApiRequest	Error	4/5/2017 7:59:30 AM
System.InvalidOperationException: There is an error in XML document (0, 0). ---> System.Xml.XmlException: Root element is missing. at System.Xml.XmlTextReaderImpl.Throw (System.Exception e) [0x0002a] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo (System.String res) [0x00017] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReaderImpl.ParseDocumentContent () [0x0041e] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReaderImpl.Read () [0x00097] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReader.Read () [0x00000] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlReader.MoveToContent () [0x0004b] in <1140eab9e72948548294172a9716416d>:0 at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPlexEpisodeMetadata.Read11_MediaContainer () [0x00008] in <9e2adf50005347d8a1cd9a351c15e59e>:0 at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&) at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00038] in <8f2c484307284b51944a1a13a14c0266>:0 --- End of inner exception stack trace --- at System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.XmlReader xmlReader, System.String encodingStyle, System.Xml.Serialization.XmlDeserializationEvents events) [0x00139] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.XmlReader xmlReader, System.String encodingStyle) [0x00000] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.Serialization.XmlSerializer.Deserialize (System.IO.TextReader textReader) [0x0001c] in <1140eab9e72948548294172a9716416d>:0 at Ombi.Api.ApiRequest.DeserializeXml[T] (System.String input) [0x00017] in :0	Ombi.Api.ApiRequest	Error	4/5/2017 7:59:30 AM
System.InvalidOperationException: There is an error in XML document (0, 0). ---> System.Xml.XmlException: Root element is missing. at System.Xml.XmlTextReaderImpl.Throw (System.Exception e) [0x0002a] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo (System.String res) [0x00017] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReaderImpl.ParseDocumentContent () [0x0041e] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReaderImpl.Read () [0x00097] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReader.Read () [0x00000] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlReader.MoveToContent () [0x0004b] in <1140eab9e72948548294172a9716416d>:0 at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPlexEpisodeMetadata.Read11_MediaContainer () [0x00008] in <9e2adf50005347d8a1cd9a351c15e59e>:0 at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&) at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00038] in <8f2c484307284b51944a1a13a14c0266>:0 --- End of inner exception stack trace --- at System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.XmlReader xmlReader, System.String encodingStyle, System.Xml.Serialization.XmlDeserializationEvents events) [0x00139] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.XmlReader xmlReader, System.String encodingStyle) [0x00000] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.Serialization.XmlSerializer.Deserialize (System.IO.TextReader textReader) [0x0001c] in <1140eab9e72948548294172a9716416d>:0 at Ombi.Api.ApiRequest.DeserializeXml[T] (System.String input) [0x00017] in :0	Ombi.Api.ApiRequest	Error	4/5/2017 7:59:30 AM
```

**Comment by gilbN** [comment]
@elit3ge looks like the same error #1308

**Comment by elit3ge** [comment]
@gilbN Except you were trying to send a test newsletter, mine is just trying to scan and then dies.

**Comment by ofurpesi** [comment]
Ran the Plex episode cacher. After it finished, i sent a test email to myself. It displayed movies that i added a long time ago and some episodes i added a long time ago as well. Nothing new displayed even though i had new episodes...

**Comment by Stryk3r78** [comment]
Yea still not working. NO new eps added from last nights downloads. I also have the same error as @elit3ge in my logs this morning

`System.InvalidOperationException: There is an error in XML document (0, 0). ---> System.Xml.XmlException: Root element is missing. at System.Xml.XmlTextReaderImpl.Throw(Exception e) at System.Xml.XmlTextReaderImpl.ParseDocumentContent() at System.Xml.XmlTextReaderImpl.Read() at System.Xml.XmlTextReader.Read() at System.Xml.XmlReader.MoveToContent() at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPlexAccount.Read3_user() --- End of inner exception stack trace --- at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events) at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader) at Ombi.Api.ApiRequest.DeserializeXml[T](String input) in C:\projects\requestplex\Ombi.Api\ApiRequest.cs:line 107	Ombi.Api.ApiRequest	Error	4/5/2017 2:31:41 AM`

But the issues with my blank table at least is resolved but the episode parsing is still not working right.

**Comment by gilbN** [comment]
Same here, not working. But no errors in the log

**Comment by Stryk3r78** [comment]
Something else interesting that seems to have happened. My test newsletter is sending different results from the "recently added email notification" job. Since I manually cleared by recentlyaddedlog table I have some old random movies and tv shows showing up in the test newsletter when I send it now. But I just manually ran the recently added email job and it sent the newsletter which showed the 3 new movies and 2 new shows I added today but of course none of the new episodes for my existing shows were listed still. 

I then ran the test newsletter again and technically it should be blank now that it should have updated the recentlyaddedlog table but it sent the same list of random movies and tv shows from before. So I'm getting 2 completely different newsletters depending on whether I run a test newsletter or the newsletter job. There were no errors in the log after running any of these jobs or test newsletters, the last error I had was the one posted above from 2:31am last night with the XML errors.

**Comment by ofurpesi** [comment]
My setup is behaving almost exactly like yours @Stryk3r78

**Comment by Stryk3r78** [comment]
I had another look at the contents of my test newsletter, and it seems that what it's sending at the first 5 movies and tv shows (with no episodes listed underneath, just the show description) from my library in alphabetically order.

my 5 movies are: 10 things about you, 2017 oscar short films, 20th century women, the accountant, and alice through the looking glass. then my 5 tv shows are: the 100, 1000 ways to die, 24: legacy, adam ruins everything and the affair.

These items keep being sent in the test newsletter regardless of what new is added to my library, and all of these items have been in my library for a while and have not appeared in any recently added list likely until I cleared my recentlyaddedlog table. 

At least there is some pattern to the what's showing up, and if I send the actual newsletter manually using the job, none of these show up and I get the proper results (minus new eps for existing shows). Again no errors at all in my logs from last night, lots of new episodes added and even a couple movies but the contents of the test newsletter now don't change anymore, just what's listed above the same "first 5" items from both my libraries.

**Comment by tidusjar** [comment]
Just to update everyone, I've just found a massive flaw in the way we try and find new episodes that I am fixing now. I am working on this even know i've not posted on here recently.

**Comment by gilbN** [comment]
Excellent news!

**Comment by tidusjar** [comment]
So guys,

Can you try EAP?

I've bumped up the version number to 2.2.1 and added a new migrations task that will clear out your RecentlyAddedLog table and re-populate it with the correct information.

The issue with episodes was that to find 'unique' episodes I was looking the the main provider id e.g. IMDBId/TheMovieDb.

So each episode has a "ProviderId" which is the series IMDBId. So I was looking for episodes that I have sent using the IMDBId meaning if 1 episode has been sent for that series then it would not send anymore (Since all episodes have the same provider id). 

That was the issue, to resolve this, internally Plex stores it's own unique Id for episodes, I am now using that instead. 

I also fixed the issue where in the email it shows the comma at the end of the episode:
![image](https://cloud.githubusercontent.com/assets/6642220/24772519/87fc0f78-1b09-11e7-97d8-da830c528208.png)

It's only a small thing but I fixed that:
![image](https://cloud.githubusercontent.com/assets/6642220/24772537/9a60db44-1b09-11e7-86a2-51e3afb873d9.png)

**Comment by Stryk3r78** [comment]
Thanks Jamie,

I've updated to 2.2.1643 and it appears that the new episodes are being listed now. I re ran the episode cacher and plex cacher jobs and send a test newsletter and the TV section is now showing what matches to my recently added section in plex from today. However, my Movie section is still showing the "first 5" items from my movie library like I mentioned above, but the tv section sorted itself out.

One other thing I noticed and maybe it's just nitpicking, but display order in the newsletter doesn't match the order in which they were added (I had noticed this as well for the movies, something I had downloaded Monday might be listed first and then something downloaded Thursday night which would be the most recent item would be listed last). Not sure if there is a way to order by time added or if you even care.

Do you know how I might be able to resolve the issue with my test newsletter movie section? I'm not sure how it got like this and the "newsletter job" doesn't seem to send these 5 movies in its list but I know there are movies I downloaded today, that aren't showing up in the test now.

**Comment by tidusjar** [comment]
Excellent news!

So for test emails (I did add this into the tooltip). If we cannot find any 'new' content, for test purposes we will grab 5 items. In your case there are no movies, so for the test email we just grab the first 5 movies in the Ombi database for display purposes.

Otherwise you could press "test" and not have any new content and the email wouldn't even send.

Regarding the order, we do record the date and time it was added into the Ombi database so it is possible to order them. Newest first or oldest first?

**Comment by gilbN** [comment]
@tidusjar Updated to 2.2.1646. TvShows are working now. But movies not so much. It's showing the first movies in my first plex library :S

**Comment by tidusjar** [comment]
@gilbN Look at my above comment

**Comment by Stryk3r78** [comment]
That explains it Jamie for my movies test issue, when I sent the recently added job manually it actually sent the right results. the only issue is that I know there is at least 2 new movies I added today.... but maybe it will work itself out tomorrow morning when the newsletter fires off from cron. I'll just let it do it's thing and let you know tomorrow if it doesn't update properly.

As far as ordering, personally I think it would be best to have both Movies and TV shows with the "Most Recent" at the top of the section. So that when users read it, they are looking at the most recent items first ( I find my users like to know what newest first).

Thanks so much for you help!

**Comment by tidusjar** [comment]
I pushed a new commit into eap. I am now ordered them, the problem is for the Plex content I wasn't stamping the time I was adding them. So for new content going forward it will order them correctly :) (Date Descending)

**Comment by gilbN** [comment]
Hm, the test newsletter is showing the same movies as on  2.2.1646. but tvshows is not showing anything new but older shows that I haven't added anything on for a long time. So I guess the same is happening now on tvshows as with movies because nothing is new since last time I ran the test newsletter? So all good I guess? :D

**Comment by tidusjar** [comment]
So yes!

If there is nothing new then we just grab random data for the test purpose.

**Comment by tidusjar** [comment]
If you want to test this you can do the following:

Open up the db and look at the PlexEpisodes table.

Find an episode that you want to appear in the newsletter and take note of the `RatingKey`

Execute the following Query:

`Delete From RecentlyAddedLog where ProviderId=YourRatingKey`

Same with the PlexContent but take note of the `ProviderId` and then:

`Delete From RecentlyAddedLog where ProviderId=YourProviderId`

**Comment by gilbN** [comment]
@tidusjar worked great :)

**Comment by tidusjar** [comment]
I'm going to close this for now since it seems like i've fixed it. Please comment on here if you find any more issues.

**Comment by Shiroihige** [comment]
Is it supposed to show the episode numbers that were added in the newsletter after updating to the latest eap?  Because for me it doesn't show them when I send the test email to admin

**Comment by elit3ge** [comment]
I still have this lovely error flooding my logs and killing the process.

```
System.InvalidOperationException: There is an error in XML document (0, 0). ---> System.Xml.XmlException: Root element is missing. at System.Xml.XmlTextReaderImpl.Throw (System.Exception e) [0x0002a] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo (System.String res) [0x00017] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReaderImpl.ParseDocumentContent () [0x0041e] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReaderImpl.Read () [0x00097] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlTextReader.Read () [0x00000] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.XmlReader.MoveToContent () [0x0004b] in <1140eab9e72948548294172a9716416d>:0 at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderPlexEpisodeMetadata.Read11_MediaContainer () [0x00008] in :0 at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&) at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00038] in <8f2c484307284b51944a1a13a14c0266>:0 --- End of inner exception stack trace --- at System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.XmlReader xmlReader, System.String encodingStyle, System.Xml.Serialization.XmlDeserializationEvents events) [0x00139] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.Serialization.XmlSerializer.Deserialize (System.Xml.XmlReader xmlReader, System.String encodingStyle) [0x00000] in <1140eab9e72948548294172a9716416d>:0 at System.Xml.Serialization.XmlSerializer.Deserialize (System.IO.TextReader textReader) [0x0001c] in <1140eab9e72948548294172a9716416d>:0 at Ombi.Api.ApiRequest.DeserializeXml[T] (System.String input) [0x00017] in <7f5d015a584b4b3f89e9b62f39461ff2>:0	Ombi.Api.ApiRequest	Error	4/7/2017 6:37:21 AM
```

**Comment by gilbN** [comment]
The newsletter that got sent out today only showed the TV show that I deleted the ratingkey on.

**Comment by tidusjar** [comment]
@gilbN was anything new added and the jobs run after they were added?
@elit3ge that is nothing to do with the newsletter. It's an error in your episode cacher. If it's killing the process i suggest you turn off episode searching. It's quite an involved process due to the way we are working with the Plex API.

**Comment by elit3ge** [comment]
@tidusjar It doesn't kill the process it becomes unresponsive via the web interface. I have opened a new ticket. https://github.com/tidusjar/Ombi/issues/1356

**Comment by Stryk3r78** [comment]
My newsletter that went out this morning, only showed 3 movies I downloaded last night (though they were in order this time :) )

Is it possible that the test newsletter updated the recently added log table and that's why my real newsletter is now not listed the episodes that were listed in the test newsletter I sent myself last night?

**Comment by Stryk3r78** [comment]
another update, yesterday when I sent the test newsletter I had items in it. But they didn't show up in todays newsletter. New shows downloaded overnight and I noticed that they didn't showup either as teh cacher job didn't run again since I manually ran it last night (I guess it hasn't been 11 hours). After running the episode cacher manually, my test emails are now showing the items since the last test newsletter. 

I reran the newsletter email job manually, and another newsletter was sent out that has the same content as the test newsletter. But it is not in order, again the most recent item is listed last, the 3rd more recent item is listed first, the 2nd oldest item is listed 2nd. I'm not sure where all the items from last nights test went, as they are completely missing even though there were there and I only sent a test, not the real newsletter.

The movies were blank as expected due to them being listed in the first newsletter this morning. So it looks like maybe it just need a cycle to "catchup". But it also brings another issue, would it be possible to run the episode cacher before sending the newsletter? I obviously had a lot of content waiting that wasn't added since the job doesn't run very often. And it doesn't seem the ordering is working for the TV shows like it was for the movies.

**Comment by ofurpesi** [comment]
Ran the test email. It showed movies added and a single episode, but it was missing 3 tv shows added yesterday. So still having issues with tv shows added recently

**Comment by Stryk3r78** [comment]
@ofurpesi did you manually run the episode cacher before sending the test? it's possible it just needs to update. that's what happened to me this morning.

**Comment by ofurpesi** [comment]
@Stryk3r78 no did not run the episode cacher. Gonna do that now

**Comment by ofurpesi** [comment]
Ran the episode cacher...sama result. Still missing some episodes

**Comment by JDIacobbo** [comment]
I manually refreshed the Plex Episode Catcher, Plex Catcher, and Radarr Catcher then sent the test email. Everything is looking good so far. We will see next week when the scheduled email is sent out that everything is 100% working.

**Comment by ofurpesi** [comment]
Manually refreshed plex episode cacher ,Plex catcher and Radarr catcher. Same result

**Comment by brooklyn11218** [comment]
I have my newsletter sent daily. The first newsletter after I manually refreshed the Plex Episode cacher had pretty much every episode of every tv show in my library. After that no tv episodes have been shown at all. Only movies.

**Comment by JDIacobbo** [comment]
I am having an issue now where there aren't any episodes listed unless I manually run the Plex Episode Catcher. Once I run that, the newsletter tests out fine. This seems like an issue with the Scheduled Job. Should I open a new issue for this?

**Comment by brooklyn11218** [comment]
Yes. This one is closed for some reason so it would probably be better to open a new issue.
