### ISSUE TITLE
OMBI Not Updating 

### ISSUE THREAD

**Issue by Comfubar** [tidusjar/Ombi#1379]
#### Ombi Version:

V 2.1.1336

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Operating System:
Windows 10

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
Failed caching queued items from SickRage	Ombi.Services.Jobs.SickRageCacher	Error	4/13/2017 7:32:23 PM
There has been a API exception when Getting the Sickrage shows	Ombi.Api.SickrageApi	Error	4/13/2017 7:32:23 PM
System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 192.168.1.204:8081 at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress) at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception) --- End of inner exception stack trace --- at System.Net.HttpWebRequest.GetResponse() at RestSharp.Http.GetRawResponse(HttpWebRequest request) at RestSharp.Http.GetResponse(HttpWebRequest request)	Ombi.Api.ApiRequest	Error	4/13/2017 7:32:22 PM
Exception when calling GetShows for SR, Retrying 00:00:30	Ombi.Api.SickrageApi	Error	4/13/2017 7:31:31 PM
System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 192.168.1.204:8081 at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress) at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception) --- End of inner exception stack trace --- at System.Net.HttpWebRequest.GetResponse() at RestSharp.Http.GetRawResponse(HttpWebRequest request) at RestSharp.Http.GetResponse(HttpWebRequest request)	Ombi.Api.ApiRequest	Error	4/13/2017 7:31:31 PM
Exception when calling GetShows for SR, Retrying 00:00:10	Ombi.Api.SickrageApi	Error	4/13/2017 7:31:00 PM
System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 192.168.1.204:8081 at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress) at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception) --- End of inner exception stack trace --- at System.Net.HttpWebRequest.GetResponse() at RestSharp.Http.GetRawResponse(HttpWebRequest request) at RestSharp.Http.GetResponse(HttpWebRequest request)	Ombi.Api.ApiRequest	Error	4/13/2017 7:31:00 PM
Exception when calling GetShows for SR, Retrying 00:00:05	Ombi.Api.SickrageApi	Error	4/13/2017 7:30:34 PM
System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 192.168.1.204:8081 at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress) at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception) --- End of inner exception stack trace --- at System.Net.HttpWebRequest.GetResponse() at RestSharp.Http.GetRawResponse(HttpWebRequest request) at RestSharp.Http.GetResponse(HttpWebRequest request)	O

```

#### Problem Description:

OMBI is not updating or is still stating there is an update when already updated ive followed the updating to a tee and also stopped ombi when updating and issue still occurs 
 My internal ip address has changed from 192.168.1.204 to 192.168.0.222 but i dont know what one to change for those ApiRequest  Errors

**Comment by tidusjar** [comment]
What's your branch set to in the settings?

**Comment by Comfubar** [comment]
Stable

**Comment by ubun2Junky** [comment]
I attempted to upgrade by downloading the Ombi.zip file stopping ombi service and moving the folder to override the old one.  Restarted services, logging in and I'm also getting an upgrade message.  Saying I'm still running version 2.2.0. I'm running on the stale branch as well.

**Comment by Comfubar** [comment]
Mine hasn't even update to 2.2.0 at all and if stopped service and did the same as you and no update

**Comment by PotatoQuality** [comment]
We can't help you with your internal ip adress.  You need to change your host adress for the system you use.

@Comfubar  @ubun2Junky Did you overwrite the ombi files?

**Comment by Comfubar** [comment]
Oh i fixed the internal IP address that was no biggie 

@PotatoQuality  Yea I overwrote the files with no problem Ive stopped the service and everything 

Still didn't update at all

**Comment by sharrken** [comment]
I am having the exact same issue. Manually downloaded the 2.2.1 release, stopped Ombi, extracted the zip over the existing directory, Ombi still reports v2.2.0 in the "Updates" page and that there is an update available.

**Ombi Version**: 2.2.1591 (according to About)

**Update Branch**: Stable

**OS/Mono**: CentOS 7.3.1611 / Mono Stable 4.8.0.520

**Comment by tidusjar** [comment]
The latest version guys is version `	2.2.1678`
https://github.com/tidusjar/Ombi/releases/tag/v2.2.1

**Comment by sharrken** [comment]
Turns out I was just extracting it blind over the existing install folder, resulting in the contents going to ombi/Release rather than ombi/ .

**Comment by tidusjar** [comment]
Resolved? :)

**Comment by ubun2Junky** [comment]
I used rsync to move the files over and resolved my issue. I'm good!!  Thx tidusjar!

**Comment by Comfubar** [comment]
Still an issue here on windows for me but im going to try and update again tonight see what happens Will report around 1am EST

**Comment by Comfubar** [comment]
So I believe it finally updated me to 2.2.1 so I would say this is resolved thank you guys for all the help

**Comment by Comfubar** [comment]
## Accidental Closure 

It never updated for me what so ever Upon my drunken night thinking this thing updated for me after my friends birthday party it has not 

Its still showing as version 2.1 I have done everything but tried updating it in Windows Safe mode which i will try Today Sunday 

But as far as Stopping the service and unblocking the master file and then dragging the files and folders from the Zip into the folder i have Ombi in which is C:\Ombi it just doesn't update at all  not entirely sure why

**Comment by Comfubar** [comment]
Seems like that didnt fix the issue still running on 2.1.0 and Ombi wont update for some odd reason

**Comment by tidusjar** [comment]
There must be something you are missing in the process as this is not been an issue for anyone else.

Can you download the latest release from here: https://github.com/tidusjar/Ombi/releases/latest

And unblock > extract into a new folder and see what version that reports?

**Comment by Comfubar** [comment]
I was just able to do so and it did update but every single setting was lost i did backup before updating is there something i can move from my backup so no settings are lost during update

**Comment by tidusjar** [comment]
Move the `Ombi.sqlite` file! :)

**Comment by Comfubar** [comment]
Just did and it worked flawlessly dont know why it would update with stable but it did with Early Access but Oh well as long as im updated
