### ISSUE TITLE
Marking title unavailable/deleting show does not remove Available status on search screen

### ISSUE THREAD

**Issue by hexeth** [tidusjar/Ombi#1566]
Mark any movie/show unavailable in request queue and/or delete show. Searching that same title will still show title as available.

**Comment by PotatoQuality** [comment]
We checking If the media is on plex, we dont check If you delete a request on the request queue ( that is not how Ombi works)

**Comment by PotatoQuality** [comment]
But it is possible that the cache system override your not available tsg

**Comment by PotatoQuality** [comment]
Damn mobile  support xd

**Comment by halethrain** [comment]
I deleted the movie from Plex as well, it still believes the movie to be available. Clicking "View on Plex" on the title just goes to my Plex dashboard

**Comment by tidusjar** [comment]
Ombi does not go back into your library to see if the content has now been removed. I don't plan to change this until we are at a stable release.

**Comment by estavez** [comment]
When is this feature gonna be implemented in v3?

This is really a becoming a missing feature after running on a stable v3 not crashing like v2 was doing all the time on Linux. After running V3 for a while running all users is using the request system now and with lots of old movies or tv shows taking up unnecessary space, that sometimes needs to be cleaned up by us through Plex or CP & Sonarr with more when not watched anymore, could be good if an admin could remove the old content directly from Plex within Ombi if possible in near future release.

This is a MUST HAVE for the request system, as the users can do a request themselves again if something was removed and they want to see the movie again in that way we can clean up all old stuff no one sees anymore and the system will be complete. 

Why is Ombi not able sync both ways or either look for what has been removed directly in Plex, CP or Sonarr as I see it the function is there in a way already just only for sync one way under **Settings - Media Server** - **Manual Run Full Sync** or **Manually Run Recently Added Sync** but again it is only missing the search for removed content. If this function can run every once in a while in a cronjob, then it should be **Run Recently Added or Removed Sync** should be implemented.

It could also be a good feature also to block certain stuff from being possible to be re-added by requests and show it next the content to the users as "Declined by admin" or something similar. Please note the last thing i nice to have not need to have!

**Comment by AmarettoSlim** [comment]
First off, thanks @tidusjar for the killer tool!

For what it's worth, syncing what's in plex to ombi on a recurring schedule and having ombi accurately a title is no longer available (and thus can be requested again) after it's been deleted would be greatly appreciated by anyone who has: mistakenly deleted a title in plex, pulled the wrong one down due the wrong profile configuration, etc. :)

**Comment by romprod** [comment]
Was looking to do exactly this today.

I tend to delete movies that I've seen but this sometimes means that users are then no longer able to re-request the movies.

Maybe an option in Ombi to manually check Plex for a film that can be triggered by users (which can be disabled) would work?

**Comment by tidusjar** [comment]
This has been fixed in the develop branch! 🎉 🎈

**Comment by romprod** [comment]
Hey, unless I'm missing something, I still have the same behaviour.

I've never checked before, but I assume it's one of the cron jobs that's set? If so I've changed the frequency and restarted Ombi and left a day to check.

I'm running the develop branch with 3.0.4122

**Comment by tidusjar** [comment]
There is a job that runs every 5 days that resyncs to Plex.  Check the jobs
page to change it.

**Comment by romprod** [comment]
OK, changed back to every midnight to see if it kicks in tonight.

**Comment by romprod** [comment]
Still the same behaviour.

I've confirmed that a request gets dealt with correctly by each of the apps, Radarr, SABnzbd and then Plex, it then shows up in Ombi as available.

Just that I'm still unable to re-request it once it gets deleted.

Should going into the Plex config and clicking on the "Manually Run Full Sync" option then temporarily fix everything? Which it doesn't

**Comment by krisklosterman** [comment]
@tidusjar Has this really been resolved? because I am having the same issue as romprod above

**Comment by krisklosterman** [comment]
@tidusjar Can this be reopened please

**Comment by romprod** [comment]
I never had this working so gave up in the end!

**Comment by clarenceb5** [comment]
If the items shows as Available on the search screen it is because you have
it in your library.

Removing or Deleting a "Request" in Ombi does not remove it from your Plex
library therefore a search will still show it as Available.

**Comment by romprod** [comment]
Brilliant, I get that, but when the actual file is deleted and then Plex removes the item, Ombi never realises that and users are then unable to re-request the item.

Or am I missing the point?

**Comment by AmarettoSlim** [comment]
You nailed it romprod, that's exactly what happens today.

I believe the desired behavior is that when a file is removed from Plex, that Ombi recognizes this (during the sync job) and allows users to request that same item again.

@tidusjar any chance we can re-open this?

**Comment by SiemdeNijs** [comment]
Just wondering - is there a fix we can use for those whom are not on the develop branch ? I now have about 10-20 movies that are marked "Available", while removed from my server. They are not even appearing under request, only under search, so I cannot remove them manually, or for example request them again. They are stuck in the current state. 

Sync is not fixing things either.

**Comment by nebbles** [comment]
Bumping this since setting up an Ombi install and discovered that this still doesn't work. The database really needs cleaning up if the media is no longer available on Plex. There isn't even a manual way to remove it.

**Comment by tidusjar** [comment]
There is a job by default that runs every 5 days that sorts out the database. This shouldn't be an issue

**Comment by nebbles** [comment]
Apologies the job does work, however I needed to update the cron job and restart to force the db update to run. Then had to revert the cron job (back to daily instead).

Is there any way this can be initiated manually rather than changing the cron job temporarily? 

I've had to do this on the Media Database job (to update Ombi showing a film as available) and for the radarr sync (to update it showing as requested even when request has been deleted and film was removed from radarr), as there are no manual triggers for this sync.

**Comment by tidusjar** [comment]
Please raise a new issue regarding manually running it and I'll add that functionality.

**Comment by jaretclifton** [comment]
Same behavior here. The job doesn't actually mark deleted media as unavailable in Ombi.

**Comment by nebbles** [comment]
@jaretclifton it might help when #3110 is implemented, but I manually reconfigured the cron timing to force a sync and eventually it did work. The settings not having a manual trigger button was a real pain for debugging this issue.

**Comment by aaron-kidwell** [comment]
can we fix this now
