### ISSUE TITLE
Settings on the sonarr page won't save.

### ISSUE THREAD

**Issue by jvacek** [tidusjar/Ombi#1644]
#### Ombi build Version:

V 3.0.2247

#### Update Branch:

Dot Net Core
#### Media Sever:

Plex

#### Operating System:

linux

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
2017-10-30 13:36:32.349 +01:00 [Information] Start installing Hangfire SQL objects...
2017-10-30 13:36:36.750 +01:00 [Information] Hangfire SQL objects installed.
2017-10-30 13:36:36.800 +01:00 [Information] Starting Hangfire Server
2017-10-30 13:36:36.805 +01:00 [Information] Using job storage: 'SQLite Server: Ombi.db'
2017-10-30 13:36:36.805 +01:00 [Information] Using the following options for Hangfire Server:
2017-10-30 13:36:36.805 +01:00 [Information]     Worker count: 1
2017-10-30 13:36:36.805 +01:00 [Information]     Listening queues: 'default'
2017-10-30 13:36:36.805 +01:00 [Information]     Shutdown timeout: 1.00:00:00
2017-10-30 13:36:36.805 +01:00 [Information]     Schedule polling interval: 00:00:15
2017-10-30 13:40:36.208 +01:00 [Information] Created User "sausage"
2017-10-30 13:40:37.023 +01:00 [Information] Created the roles
2017-10-30 13:40:37.268 +01:00 [Information] Added the Admin role
2017-10-30 13:44:55.838 +01:00 [Error] Could not test Plex
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: SSL peer certificate or SSH remote key was not OK
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Api.<Request>d__8`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Plex.PlexApi.<GetStatus>d__9.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<Plex>d__49.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 202
2017-10-30 13:45:05.643 +01:00 [Error] Could not test Plex
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: SSL peer certificate or SSH remote key was not OK
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Api.<Request>d__8`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Plex.PlexApi.<GetStatus>d__9.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<Plex>d__49.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 202
2017-10-30 13:45:23.184 +01:00 [Error] Could not test Plex
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: Server returned nothing (no headers, no data)
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Api.<Request>d__8`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Plex.PlexApi.<GetStatus>d__9.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<Plex>d__49.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 202
2017-10-30 13:45:27.389 +01:00 [Error] Could not test Plex
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: SSL peer certificate or SSH remote key was not OK
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Api.<Request>d__8`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Plex.PlexApi.<GetStatus>d__9.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<Plex>d__49.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 202
2017-10-30 13:45:33.397 +01:00 [Error] Could not test Plex
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: SSL peer certificate or SSH remote key was not OK
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Api.<Request>d__8`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Plex.PlexApi.<GetStatus>d__9.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<Plex>d__49.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 202
2017-10-30 13:46:25.203 +01:00 [Error] Could not test Plex
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: SSL peer certificate or SSH remote key was not OK
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Api.<Request>d__8`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Plex.PlexApi.<GetStatus>d__9.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<Plex>d__49.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 202
2017-10-30 13:46:42.014 +01:00 [Error] Could not test Plex
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: SSL peer certificate or SSH remote key was not OK
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Api.<Request>d__8`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Plex.PlexApi.<GetStatus>d__9.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<Plex>d__49.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 202
2017-10-30 13:46:45.700 +01:00 [Warning] Error thrown when attempting to obtain the plex libs
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: SSL peer certificate or SSH remote key was not OK
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Api.<Request>d__8`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Plex.PlexApi.<GetLibrarySections>d__11.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Plex\PlexApi.cs:line 68
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.PlexController.<GetPlexLibraries>d__9.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\PlexController.cs:line 107
2017-10-30 13:56:42.051 +01:00 [Error] StatusCode: NotFound, Reason: Not Found
2017-10-30 13:56:42.071 +01:00 [Error] StatusCode: NotFound, Reason: Not Found
2017-10-30 13:56:42.112 +01:00 [Error] StatusCode: NotFound, Reason: Not Found
2017-10-30 14:02:17.765 +01:00 [Error] Could not test Sonarr
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: SSL connect error
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Api.<Request>d__8`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Sonarr.SonarrApi.<SystemStatus>d__17.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Sonarr\SonarrApi.cs:line 201
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<Sonarr>d__52.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 266
2017-10-30 14:13:13.441 +01:00 [Information] Hangfire Server stopped.
2017-10-30 14:13:28.344 +01:00 [Information] Start installing Hangfire SQL objects...
2017-10-30 14:13:28.395 +01:00 [Information] Hangfire SQL objects installed.
2017-10-30 14:13:28.419 +01:00 [Information] Starting Hangfire Server
2017-10-30 14:13:28.422 +01:00 [Information] Using job storage: 'SQLite Server: Ombi.db'
2017-10-30 14:13:28.422 +01:00 [Information] Using the following options for Hangfire Server:
2017-10-30 14:13:28.422 +01:00 [Information]     Worker count: 1
2017-10-30 14:13:28.422 +01:00 [Information]     Listening queues: 'default'
2017-10-30 14:13:28.422 +01:00 [Information]     Shutdown timeout: 1.00:00:00
2017-10-30 14:13:28.422 +01:00 [Information]     Schedule polling interval: 00:00:15
2017-10-30 14:21:09.305 +01:00 [Error] StatusCode: NotFound, Reason: Not Found
2017-10-30 14:21:09.384 +01:00 [Error] StatusCode: NotFound, Reason: Not Found
2017-10-30 14:21:09.422 +01:00 [Error] StatusCode: NotFound, Reason: Not Found
2017-10-30 14:39:03.988 +01:00 [Error] Could not test Sonarr
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: SSL connect error
   at System.Net.Http.CurlHandler.ThrowIfCURLEError(CURLcode error)
   at System.Net.Http.CurlHandler.MultiAgent.FinishRequest(StrongToWeakReference`1 easyWrapper, CURLcode messageResult)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Api.<Request>d__8`1.MoveNext() in C:\projects\requestplex\src\Ombi.Api\Api.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Api.Sonarr.SonarrApi.<SystemStatus>d__17.MoveNext() in C:\projects\requestplex\src\Ombi.Api.Sonarr\SonarrApi.cs:line 201
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<Sonarr>d__52.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 266
```

#### Problem Description:

**Settings on the sonarr page won't save.**
When the host, port, token, profiles and root folders are all filled in, saving does not seem to work any action. A popup does not show up, and the settings do not persist when page is re-navigated to

Am using ssh tunneling to access ombi for now

#### Reproduction Steps:

1. Go to settings, TV, Sonarr
2. Fill in all required fields
3. Retrieve folders, test connection
4. Press save
5. Reload or navigate to another page and then back
6. See nothing is saved

**Comment by Codehhh** [comment]
[System.Net.Http.CurlHandler Error](../wiki/Common-Errors#systemnethttpcurlhandler)

Try this and report back

**Comment by jvacek** [comment]
```libcurl4-openssl-dev is already the newest version (7.47.0-1ubuntu2.4).```

**Comment by Codehhh** [comment]
Is there also an SSH tunnel from Ombi -> Plex?

**Comment by jvacek** [comment]
In the meantime I switched from using the SSH tunnel in favour of an nginx reverse proxy using SSL, still same issue.

**Comment by Codehhh** [comment]
Is the SSL a valid cert or is it self signed?

**Comment by jvacek** [comment]
reverse proxy for ombi is signed using letsencrypt.
Connection to Plex and Sonarr is on localhost so I don't choose the SSL.

**Comment by tidusjar** [comment]
In ombi settings enable the ignore certificate errors

**Comment by jvacek** [comment]
Enabled the invalid cert ignoring a little while ago in an early attempt at fixing this, still doesn't seem to work.
To reiterate, the sonarr setting page in Ombi is able to test connection, retrieve profiles and root folders successfully, however the save button does not seem to function correctly in my case, it does  **neither** tell me that the changes were saved (like the radarr page does) **nor** that there was an issue saving the changes.
I've restarted the Ombi process a couple times in the meantime, now running as a systemd service using my user, still the same issue.

**Comment by jvacek** [comment]
Just tried settings this up using Firefox running on the server, connected via ssh -CY to get the window to tunnel so I can do a real connection to localhost:5000, could not set it up that way either.

**Comment by Niksal12** [comment]
I have the same issue, Radarr settings can be saved with no issues, Sonarr cannot. 

`vendor.js:8 ERROR TypeError: Cannot read property 'value' of undefined
    at e.onSubmit (main.js:50)
    at Object.eval [as handleEvent] (ng:///e/e.ngfactory.js:161)
    at Object.handleEvent (vendor.js:113)
    at Object.handleEvent (vendor.js:113)
    at re (vendor.js:64)
    at vendor.js:78
    at e.object.r [as _next] (vendor.js:169)
    at e.__tryOrUnsub (vendor.js:375)
    at e.next (vendor.js:375)
    at e._next (vendor.js:375)
_ @ vendor.js:8
vendor.js?v=bMkI8LLPNqhf9i0w0Qd5EV8lEQT1UkPiVQ3y_Svo-cA:8 ERROR TypeError: Cannot read property 'value' of undefined
    at e.onSubmit (sonarr.component.ts:106)
    at Object.eval [as handleEvent] (e.ngfactory.js:161)
    at Object.handleEvent (vendor.js?v=bMkI8LLPNqhf9i0w0Qd5EV8lEQT1UkPiVQ3y_Svo-cA:113)
    at Object.handleEvent (vendor.js?v=bMkI8LLPNqhf9i0w0Qd5EV8lEQT1UkPiVQ3y_Svo-cA:113)
    at re (vendor.js?v=bMkI8LLPNqhf9i0w0Qd5EV8lEQT1UkPiVQ3y_Svo-cA:64)
    at vendor.js?v=bMkI8LLPNqhf9i0w0Qd5EV8lEQT1UkPiVQ3y_Svo-cA:78
    at e.object.r [as _next] (vendor.js?v=bMkI8LLPNqhf9i0w0Qd5EV8lEQT1UkPiVQ3y_Svo-cA:169)
    at e.__tryOrUnsub (vendor.js?v=bMkI8LLPNqhf9i0w0Qd5EV8lEQT1UkPiVQ3y_Svo-cA:375)
    at e.next (vendor.js?v=bMkI8LLPNqhf9i0w0Qd5EV8lEQT1UkPiVQ3y_Svo-cA:375)
    at e._next (vendor.js?v=bMkI8LLPNqhf9i0w0Qd5EV8lEQT1UkPiVQ3y_Svo-cA:375)
_ @ vendor.js?v=bMkI8LLPNqhf9i0w0Qd5EV8lEQT1UkPiVQ3y_Svo-cA:8
t.handleError @ vendor.js?v=bMkI8LLPNqhf9i0w0Qd5EV8lEQT1UkPiVQ3y_Svo-cA:155
(anonymous) @ vendor.js?v=bMkI8LLPNqhf9i0w0Qd5EV8lEQT1UkPiVQ3y_Svo-cA:78
e.object.r @ vendor.js?v=bMkI8LLPNqhf9i0w0Qd5EV8lEQT1UkPiVQ3y_Svo-cA:169
e.__tryOrUnsub @ vendor.js?v=bMkI8LLPNqhf9i0w0Qd5EV8lEQT1UkPiVQ3y_Svo-cA:375
e.next @ vendor.js?v=bMkI8LLPNqhf9i0w0Qd5EV8lEQT1UkPiVQ3y_Svo-cA:375
e._next @ vendor.js?v=bMkI8LLPNqhf9i0w0Qd5EV8lEQT1UkPiVQ3y_Svo-cA:375
e.next @ vendor.js?v=bMkI8LLPNqhf9i0w0Qd5EV8lEQT1UkPiVQ3y_Svo-cA:375
e.next @ vendor.js?v=bMkI8LLPNqhf9i0w0Qd5EV8lEQT1UkPiVQ3y_Svo-cA:375
e.emit @ vendor.js?v=bMkI8LLPNqhf9i0w0Qd5EV8lEQT1UkPiVQ3y_Svo-cA:169
e.onSubmit @ vendor.js?v=bMkI8LLPNqhf9i0w0Qd5EV8lEQT1UkPiVQ3y_Svo-cA:473
(anonymous) @ e.ngfactory.js:153
handleEvent @ vendor.js?v=bMkI8LLPNqhf9i0w0Qd5EV8lEQT1UkPiVQ3y_Svo-cA:113
handleEvent @ vendor.js?v=bMkI8LLPNqhf9i0w0Qd5EV8lEQT1UkPiVQ3y_Svo-cA:113
re @ vendor.js?v=bMkI8LLPNqhf9i0w0Qd5EV8lEQT1UkPiVQ3y_Svo-cA:64
(anonymous) @ vendor.js?v=bMkI8LLPNqhf9i0w0Qd5EV8lEQT1UkPiVQ3y_Svo-cA:71
(anonymous) @ vendor.js?v=bMkI8LLPNqhf9i0w0Qd5EV8lEQT1UkPiVQ3y_Svo-cA:565
t.invokeTask @ vendor.js?v=bMkI8LLPNqhf9i0w0Qd5EV8lEQT1UkPiVQ3y_Svo-cA:1083
onInvokeTask @ vendor.js?v=bMkI8LLPNqhf9i0w0Qd5EV8lEQT1UkPiVQ3y_Svo-cA:36
t.invokeTask @ vendor.js?v=bMkI8LLPNqhf9i0w0Qd5EV8lEQT1UkPiVQ3y_Svo-cA:1083
i.runTask @ vendor.js?v=bMkI8LLPNqhf9i0w0Qd5EV8lEQT1UkPiVQ3y_Svo-cA:1083
e.invokeTask @ vendor.js?v=bMkI8LLPNqhf9i0w0Qd5EV8lEQT1UkPiVQ3y_Svo-cA:1083
h @ vendor.js?v=bMkI8LLPNqhf9i0w0Qd5EV8lEQT1UkPiVQ3y_Svo-cA:1055
f @ vendor.js?v=bMkI8LLPNqhf9i0w0Qd5EV8lEQT1UkPiVQ3y_Svo-cA:1055`

**Comment by PotatoQuality** [comment]
guys why are you connect ombi on the same machine with ssl to sonarr? its localhost. (missing the reason why ssl is needed when connecting localhost)

**Comment by Niksal12** [comment]
Not OP but I am not trying to use ssl, and sonarr is not on the same machine but is within my network.

**Comment by PotatoQuality** [comment]
can you make a new issue for that? this topic about ssl problems. 

(or i missing the point right now :P)

**Comment by Niksal12** [comment]
I can

**Comment by tidusjar** [comment]
I think they are both related.

**Comment by jvacek** [comment]
`guys why are you connect ombi on the same machine with ssl to sonarr? its localhost. (missing the reason why ssl is needed when connecting localhost)`
Am not, I use localhost connection with no SSL. here is a screenrec of what I'm doing, if there's something obviously wrong please tell me :L
https://transfer.sh/IFs5N/Untitled2.mov

**Comment by PotatoQuality** [comment]
@jvacek wait, i got the same problem last week.

I solved by the following thing:

Let Sonarr generate a new api key. After that. Save it in sonarr. Restart Sonarr.
And try it again in Ombi.

**Comment by Niksal12** [comment]
@PotatoQuality Just tried that and still have the same issue as @jvacek.

**Comment by PotatoQuality** [comment]
damnit. We need to wait for some help from tidusjar.

**Comment by tidusjar** [comment]
Yeah I think I broke it last night when doing some refactoring around that area. I'll fix it when I get a chance

**Comment by jvacek** [comment]
I reset my token and now the connection test does not work either. Works in organizr though.
