### ISSUE TITLE
Newsletter test works but not scheduled or ad hoc run

### ISSUE THREAD

**Issue by goku-son** [tidusjar/Ombi#2134]
#### Ombi build Version:

V 3.0.3111

#### Update Branch:

Stable

#### Media Sever:

Plex

#### Media Server Version:

1.12

#### Operating System:

Windows 10

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

(Logs go here. Don't remove the ' tags for showing your logs correctly. Please make sure you remove any personal information from the logs)

2018-04-06 07:09:43.556 -05:00 [Information] 1 scheduled job(s) enqueued.
2018-04-06 07:19:28.584 -05:00 [Information] 1 scheduled job(s) enqueued.
2018-04-06 07:30:28.584 -05:00 [Information] 1 scheduled job(s) enqueued.
2018-04-06 18:49:41.932 -05:00 [Error] StatusCode: Unauthorized, Reason: Unauthorized, RequestUri: https://plex.tv/users/sign_in.json
2018-04-06 18:51:48.876 -05:00 [Error] StatusCode: 429, Reason: , RequestUri: http://api.themoviedb.org/3/movie/8388?api_key=b8eabaf5608b8hh8d0298aa189dd90bf00&append_to_response=videos,release_dates
2018-04-06 18:51:48.934 -05:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/movie/8388?api_key=b8eabaf5608b88d0298aa189jcdd90bf00&append_to_response=videos,release_dates Because we got Status Code: 429
2018-04-06 18:56:49.273 -05:00 [Error] StatusCode: 429, Reason: , RequestUri: http://api.themoviedb.org/3/find/tt6421110?api_key=b8eabaf5608b88d0298aufa189dd90bf00&external_source=imdb_id
2018-04-06 18:56:49.332 -05:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/find/tt6421110?api_key=b8eabaf5608b8rf8d0298aa189dd90bf00oi&external_source=imdb_id Because we got Status Code: 429
2018-04-06 18:56:59.479 -05:00 [Error] StatusCode: 429, Reason: , RequestUri: http://api.themoviedb.org/3/movie/442064?api_key=b8eab78af5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates
2018-04-06 18:56:59.535 -05:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/movie/442064?api_key=b8eabaf5608b88d029gd78aa189dd90bf00&append_to_response=videos,release_dates Because we got Status Code: 429
2018-04-06 19:01:38.413 -05:00 [Information] 1 scheduled job(s) enqueued.
2018-04-06 19:10:53.450 -05:00 [Information] 1 scheduled job(s) enqueued.


```

#### Problem Description:

Test newsletter work but scheduled newsletter does not. 

#### Reproduction Steps:

Noticed that I did not get the newsletter this morning. If I go to the newsletter settings and test I get the email. If I if I select trigger to send the newsletter immediately, I never get it. I posted the logs and hoping I could get some assistance on this. Thanks in advance.

**Comment by tidusjar** [comment]
Did anything get added to Plex?

Did ombi pickup that they have been added? Search for it to see if it's available

**Comment by goku-son** [comment]
On March 30th I got my first scheduled newsletter. However, this past Friday I did not which lead me to test (successfull) and then trigger (nothing happens) the newsletter. I can see new content added after March 30th which is recognized by a Tautulli (shows available) which suggests it synced up fine with plex but for some reason this week's run (only been running for 2 weeks) did not even generate a email nor have the manual triggered job.

**Comment by tidusjar** [comment]
Ombi has nothing to do with Tautulli. Can you please check if ombi has picked it up as available by searching for it.

**Comment by goku-son** [comment]
So sorry, I meant in Ombi. Yeah, if I search for a movie that has been added since my last newsletter on March 30th, Ombi shows it as available.

**Comment by goku-son** [comment]
Forgot to add if there is some kind of debug that could be enabled because I see nothing in the log if I try and trigger a manual send of the newsletter.

**Comment by mdhwoods** [comment]
i have same issue, newsletter not going out when content added.  Does the added content have to come though ombi?  Meaning does a request have to be in ombi for it to know it was added?  some of my requests are old and not in ombi as they were added in the past and waiting for the release.   I have a news program that's recorded on my dvr and added to plex ever night. this is also not a request in ombi. none generate the newsletter. Test does work.  Ombi is configured to talk to plex as it shows when requests exist or have become available when requested.

**Comment by tidusjar** [comment]
It does not need to be in Ombi.

@goku-son can you create a admin user for me on your ombi and send me your database on Discord with information about what movie/show is not appearing on the newsletter so I can see what is going on?

**Comment by dejected1** [comment]
i have a similar issue. The test works fine but the letter does not send per the cron expression. Also when i hit test for the entered cron expression in ombi it shows the wrong time and dates. 0 5 * * WED is what i put in for testing but the test button in ombi says this will run at 10pm not 5 am. Also at exactly 5 PM (not am) server time ombi crashed along with PHP. i had to restart the service. No log entry was created for the crash, event log says it termed with exit code 0.

**Comment by tidusjar** [comment]
I need some logs to help. 

Regarding the cron is correct. It's UTC

**Comment by dejected1** [comment]
im looking at /ombi/logs and nothing is generated for today, when it crashed. Is there a verbose log feature i can turn on or is there another spot i should be looking.

**Comment by tidusjar** [comment]
There will be some sort of output somewhere. Docker logs? There no verbose feature

**Comment by dejected1** [comment]
i dont use docker. It crashed again at 11am. 6 hours after it crashed before. Again it crashed on the hour. Is it a different job that is running causing this perhaps? The only time that is close is the automatic update job, thats 6 hours. I had auto update enabled and it knows the name of the service, cause i told it. its also reporting that there is an update to be applied but when i check github there is no update. I turned off auto update for now. see what happens.

**Comment by mdhwoods** [comment]
Jamie what do you need from me?  It didn’t run last night again. You want my data and a user?

**Comment by tidusjar** [comment]
Could you create an admin user for me and then send me the db on discord? With what's not appearing

**Comment by mdhwoods** [comment]
Done. Check discord

**Comment by tidusjar** [comment]
Can you guys  please read https://github.com/tidusjar/Ombi/wiki/Newsletter-Settings

and make sure you have users with the correct role?

**Comment by dejected1** [comment]
So it was the update schedule that was crashing ombi. After I turned it off no crashes in nearly 24 hours. I saw you released a new build. Does that address this crash?

**Comment by tidusjar** [comment]
@dejected1 Ombi was not crashing in that case. It was trying to update it. The updater has known issues. Please keep this issue on topic.

**Comment by goku-son** [comment]
No scheduled newsletter this morning. This is all that is in the log:

2018-04-13 07:10:06.602 -05:00 [Information] 1 scheduled job(s) enqueued.
2018-04-13 07:19:51.904 -05:00 [Information] 1 scheduled job(s) enqueued.
2018-04-13 07:30:07.204 -05:00 [Information] 1 scheduled job(s) enqueued.

Do let me know if there is anything else I could collect to help isolate this issue.  Thanks!

**Comment by mdhwoods** [comment]
Do you have it enabled for each user?  That was my oversight.

**Comment by goku-son** [comment]
Yeah, I have the receivesnewsletter role.  I totally overlooked that @tidusjar asked me to send him some info so I will do that.

**Comment by diedrichg** [comment]
I'm seeing the same issues on v3.0.3179 as the OP

**Comment by tidusjar** [comment]
make sure the metadata job has run

**Comment by tidusjar** [comment]
That's not there yet, just look at the jobs page to see when it should run (press the Test button)

**Comment by goku-son** [comment]
So I upgraded a couple of days ago to 3.0.3179. Metadata job is set to run every day at 10PM. I am going to wait till the next scheduled newsletter on 4/20 and see if the issue is now resolved.

**Comment by goku-son** [comment]
@tidusjar Same issue this morning...no newsletter. Same messages I posted from last week's run. So just to restate, test works fine, but scheduled job or trigger button don't produce an email. Are the scheduled job and trigger using some different mechanism than the test button? I am at a total loss as to why the test works but the schedule or trigger do not. Is there any type of debug or tracing that could be enabled? Thanks in advance.

**Comment by elit3ge** [comment]
+1 for me, no newsletter this week on the latest build.

**Comment by mdhwoods** [comment]
Mine came through yesterday 8am eastern.

**Comment by goku-son** [comment]
I am now running 3.0.3206 but same issue. I started up my old v2 and I guess will wait until next Friday to see which one produces the newsletter.  Kind of crappy to have to have v2 around just to produce the newsletter for me. Very bizarre problem.

**Comment by tidusjar** [comment]
If you give me time I'll fix it. You know the newsletter schedule can be
customised....

**Comment by mdhwoods** [comment]
Nice. I didn’t know that. Where’s the option for when it’s sent?

**Comment by tidusjar** [comment]
Job settings page

**Comment by tidusjar** [comment]
Fixed in develop

**Comment by goku-son** [comment]
@tidusjar thanks!

**Comment by goku-son** [comment]
@tidusjar updated to this patch but trigger and test of the newsletter fail with these errors:

2018-04-21 21:29:47.879 -05:00 [Information] 1 scheduled job(s) enqueued.
2018-04-21 21:30:06.017 -05:00 [Error] Error when attempting to create newsletter
System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at lambda_method(Closure , ValueBuffer )
   at System.Linq.Enumerable.WhereEnumerableIterator`1.GetCount(Boolean onlyIfCheap)
   at lambda_method(Closure , QueryContext )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass17_1`1.<CompileQueryCore>b__0(QueryContext qc)
   at System.Linq.Queryable.Count[TSource](IQueryable`1 source)
   at Ombi.Schedule.Jobs.Ombi.NewsletterJob.<Start>d__13.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\NewsletterJob.cs:line 103
2018-04-21 21:30:06.029 -05:00 [Error] Could not test Newsletter
System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at lambda_method(Closure , ValueBuffer )
   at System.Linq.Enumerable.WhereEnumerableIterator`1.GetCount(Boolean onlyIfCheap)
   at lambda_method(Closure , QueryContext )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass17_1`1.<CompileQueryCore>b__0(QueryContext qc)
   at System.Linq.Queryable.Count[TSource](IQueryable`1 source)
   at Ombi.Schedule.Jobs.Ombi.NewsletterJob.<Start>d__13.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\NewsletterJob.cs:line 247
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<NewsletterTest>d__65.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 383
2018-04-21 21:30:17.926 -05:00 [Information] 1 scheduled job(s) enqueued.
2018-04-21 21:32:17.945 -05:00 [Information] 1 scheduled job(s) enqueued.
2018-04-21 21:33:36.016 -05:00 [Error] Error when attempting to create newsletter
System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at lambda_method(Closure , ValueBuffer )
   at System.Linq.Enumerable.WhereEnumerableIterator`1.GetCount(Boolean onlyIfCheap)
   at lambda_method(Closure , QueryContext )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass17_1`1.<CompileQueryCore>b__0(QueryContext qc)
   at System.Linq.Queryable.Count[TSource](IQueryable`1 source)
   at Ombi.Schedule.Jobs.Ombi.NewsletterJob.<Start>d__13.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\NewsletterJob.cs:line 103
 2018-04-21 21:33:36.024 -05:00 [Error] Could not test Newsletter
System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at lambda_method(Closure , ValueBuffer )
   at System.Linq.Enumerable.WhereEnumerableIterator`1.GetCount(Boolean onlyIfCheap)
   at lambda_method(Closure , QueryContext )
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass17_1`1.<CompileQueryCore>b__0(QueryContext qc)
   at System.Linq.Queryable.Count[TSource](IQueryable`1 source)
   at Ombi.Schedule.Jobs.Ombi.NewsletterJob.<Start>d__13.MoveNext() in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Ombi\NewsletterJob.cs:line 247
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Ombi.Controllers.External.TesterController.<NewsletterTest>d__65.MoveNext() in C:\projects\requestplex\src\Ombi\Controllers\External\TesterController.cs:line 383

**Comment by tidusjar** [comment]
Should be fixed in develop

**Comment by goku-son** [comment]
Running the latest dev but the problem is back to the original issue. Test works but trigger and scheduled job does not. Got the newsletter this morning from my v2 instance but nothing from v3. Nothing in the logs either.

**Comment by elit3ge** [comment]
I updated to latest stable yesterday which forced the newsletter to be sent with my entire library. I have my newsletter set to 10pm, which I received at 10:03pm with the new eps that were added from 12:35pm when I updated to the latest. Then I received another one at 10:09pm with a show that had 1 episode added.

**Comment by tidusjar** [comment]
@elit3ge you didn't read the release notes. 

@goku-son please provide some logs

**Comment by elit3ge** [comment]
@tidusjar No, I did not. That only explains the whole library, not the 2 newsletters within 6 mins.

**Comment by goku-son** [comment]
@tidusjar Here are the logs for last Friday’s run:

2018-04-27 08:48:31.090 -05:00 [Information] Plex Movies to send: 1085
2018-04-27 08:48:31.125 -05:00 [Information] Emby Movies to send: 0
2018-04-27 08:48:32.010 -05:00 [Information] Plex Episodes to send: 2488
2018-04-27 08:48:32.010 -05:00 [Information] Emby Episodes to send: 0

Note that it never even started the newsletter just  @7AM The above log was generated only when I performed a test. Trigger does nothing nor does the scheduled job. In the meantime I got v2 running on the same system and that does send me the email on Fridays at 7AM.  

Let me know if there is any debug logging I could turn on as the log does not provide any insight into what is happening. Thanks.

**Comment by tidusjar** [comment]
Please use develop @goku-son

**Comment by goku-son** [comment]
Updated to the latest dev as of today. Let’s see what happens tomorrow. Thanks.

**Comment by goku-son** [comment]
Same issue nothing in logs and got the ombiv2 newsletter and not the v3 newsletter. Test works but not trigger or scheduled job. Did not even have a log for today until I manually triggered the job. 

At this point I am okay with closing this since it appears to only be happening to me. I am going to shutdown v2 and use Tautulli’s new newsletter feature which works just fine for me like Ombiv2. I will keep using V3 for strictly requests handling which has been flawless for me. Thank you so much for all your help with this I really appreciated it.

**Comment by anojht** [comment]
hey can you pm me on discord @goku-son discord is MrGoldenPhoenix
