### ISSUE TITLE
Newsletter not sending updates for movies or showing blank

### ISSUE THREAD

**Issue by Speedygg** [tidusjar/Ombi#2138]
#### Ombi build Version:

3.0.3158

#### Update Branch:

develop

#### Media Sever:

Plex

#### Media Server Version:

1.12.2.4929

#### Operating System:

ubuntu 16.04

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

Logs dont show anything

```

#### Problem Description:

The newsletter has stopped sending movie updates. The problem began after the latest develop update that gives the option to disable tvshows or movies. Test emails currently work for tv shows showing newly added episodes, but the movies section isalways blank even when new movies have been added. The email becomes completely blank when tvshows are disabled. The email works fine when movies are disabled and shows new episodes.

#### Reproduction Steps:

attempting to schedule or send a test email for the newsletter

**Comment by tidusjar** [comment]
I cannot seem to recreate this.

Are you sure Ombi is picking up the content?

**Comment by Speedygg** [comment]
Hmm that's very odd because it can see movies in my request list that are on my server and marks them available. It also seesif I already have a movie in my  library and attempt to add it. My server loads properly including when I test and load it's libraries.

**Comment by tidusjar** [comment]
Please update to latest release and then try?

**Comment by Speedygg** [comment]
I did update to the latest version and i had the same problem. I snooped around and i figured why not try a new install. I used the guide and everything went fine. Permissions and user folder access are all fine. All the plex users and  media libraries loaded, it can see which media I have since I cant request things already available, but when I send the test newsletter I STILL only get updates for tv shows and not movies. The movie portion of the email is blank. I'm in develop branch 3.0.3162

**Comment by JDIacobbo** [comment]
I am having the same issue. Please let me know what I can do to help replicate it.

Version: 3.0.3173
OS: Windows 10

**Comment by tidusjar** [comment]
Is someone able to create an admin user for me and send me the ombi.db on discord? Include what should be appearing and what's not etc.

**Comment by JDIacobbo** [comment]
Yes. I'll send it out shortly.

**Comment by tidusjar** [comment]
I think i've now fixed this in the latest develop build. 

There was an issue with the metadata job, so it wouldn't set the TheMovieDBId for content.

Please upgrade and let the metadata job run and then try a newsletter.

**Comment by Speedygg** [comment]
the 3.0.3179 update fixed the issue for me. Thank you very much tidusjar

**Comment by kmlucy** [comment]
I'm still having this issue on 3.0.3185. When I send out a test newsletter with only movies enabled, it is empty.

**Comment by tidusjar** [comment]
@kmlucy Make sure the Metadata job has run

**Comment by kmlucy** [comment]
Is there a way to manually run the metdata job? It is scheduled to run every night.

**Comment by tidusjar** [comment]
It's scheduled to run every night, but you can change that in the job settings. No way to currently manually trigger it.

**Comment by kmlucy** [comment]
Looks like everything is good now, thanks!

**Comment by leftovernick** [comment]
Having this issue on 3.0.4256. How can I ensure the metadata agent has run?

Refresh Metadata settings are: 0 0 */3 * *

When I test I get:
5/3/19, 5:00 PM
5/6/19, 5:00 PM
5/9/19, 5:00 PM
5/12/19, 5:00 PM
5/15/19, 5:00 PM
5/18/19, 5:00 PM
5/21/19, 5:00 PM
5/24/19, 5:00 PM
5/27/19, 5:00 PM
5/30/19, 5:00 PM

This has been going on for about a month for me.
