### ISSUE TITLE
Can't setup Ombi (v3.0.3239)

### ISSUE THREAD

**Issue by uncleiven** [tidusjar/Ombi#2207]
#### Ombi build Version:

v3.0.3239

#### Update Branch:

Master

#### Media Sever:

N/A
#### Media Server Version:

N/A

#### Operating System:

Linux

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

N/A

#### Problem Description:

I am unable to setup Ombi, I have a hosted server and the admins have just installed the latest version. When I go through the various setup screens, the process to gain access to Plex fails and then if I skip that part and try to setup an admin account it fails as per the screen shot

![screen shot 2018-04-28 at 09 27 16](https://user-images.githubusercontent.com/34493348/39394288-6b16c412-4ac8-11e8-9d67-766e7d5a23bc.png)

#### Reproduction Steps:

N/A

**Comment by uncleiven** [comment]
![screen shot 2018-04-28 at 09 45 38](https://user-images.githubusercontent.com/34493348/39394332-f7026c60-4ac8-11e8-932e-2812c89e01a3.png)

![screen shot 2018-04-28 at 09 46 19](https://user-images.githubusercontent.com/34493348/39394349-2b87ca34-4ac9-11e8-86a3-d099b34b6b9a.png)

Then it just hangs here....

![screen shot 2018-04-28 at 09 46 31](https://user-images.githubusercontent.com/34493348/39394350-2de0b64c-4ac9-11e8-84ad-013f9487b44e.png)

**Comment by tidusjar** [comment]
Fixed in develop

**Comment by uncleiven** [comment]
@tidusjar..... excuse my ignorance but what does that mean?

**Comment by tidusjar** [comment]
I've fixed this in the develop branch of code

**Comment by uncleiven** [comment]
Ok thanks. I’ll speak to my provider

**Comment by uncleiven** [comment]
I have had v3.0.3255 installed but I am still having issues. I went through the Wizard again and I requested a Plex Token, it then progressed through to a sign in screen asking for Username and Password, this was different to the previous screen where it was asking for a new admin account to be setup. I entered what I thought the details might have been from the v2 instance of Ombi but it's not letting me log in or use the forgotten password option...

![screen shot 2018-04-28 at 17 22 52](https://user-images.githubusercontent.com/34493348/39398710-7d2f0d58-4b09-11e8-9298-9b373cce2033.png)
![screen shot 2018-04-28 at 17 22 13](https://user-images.githubusercontent.com/34493348/39398711-7d47adea-4b09-11e8-99be-4a7b1948b47b.png)
[log-20180428.txt](https://github.com/tidusjar/Ombi/files/1957914/log-20180428.txt)

**Comment by uncleiven** [comment]
Ignore me, being a bloody idiot. It's obviously my Plex log on details which works fine :)
