### ISSUE TITLE
Ombi not aware of movies I have in collections [Emby]

### ISSUE THREAD

**Issue by bozrdang** [tidusjar/Ombi#2366]
#### Ombi build Version:

V 3.0.3456

#### Update Branch:

Dev

#### Media Sever:

Emby

#### Media Server Version:

3.4.1.0

#### Operating System:

Docker

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```


[ombi_log1.txt](https://github.com/tidusjar/Ombi/files/2152294/ombi_log1.txt)

```

#### Problem Description:

When searching for movies that I already have in my library, Ombi shows Available (as expected) if they are NOT part of a collection.  But if they are part of a collection, Ombi shows Request as if I don't have the movie.

Log shows lines like: " The media item Rocky Collection does not have a ImdbId, searching for ImdbId\n'

#### Reproduction Steps:
Mentioned above

**Comment by tidusjar** [comment]
Thanks!

**Comment by tidusjar** [comment]
Fixed in dev

**Comment by bozrdang** [comment]
I updated to 3.0.3458 and reran the cacher.  Still no change.

[new_ombi_log.txt](https://github.com/tidusjar/Ombi/files/2153174/new_ombi_log.txt)

**Comment by tidusjar** [comment]
Can you please update, i've just pushed another fix. Can you please confirm (The Content Sync job needs to be run, you can manually run from the Emby Settings page)

**Comment by roborobp** [comment]
Is there any way to reopen this issue or do I make a new ticket? I'm on the latest stable build and seeing this issue.
