### ISSUE TITLE
Ombi sees shows but not episodes in Emby library

### ISSUE THREAD

**Issue by bozrdang** [tidusjar/Ombi#2367]
#### Ombi build Version:

V 3.0.3456

#### Update Branch:

Dev

#### Media Sever:

Emby

#### Media Server Version:

3.4.1.0

#### Operating System:

Docker

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```
[ombi_log.txt](https://github.com/tidusjar/Ombi/files/2152303/ombi_log.txt)


```

#### Problem Description:

After running Emby cacher Ombi seems to know I have the shows (Ones I have will say View In Emby) but no episodes for any of them (Every show I have has a Request button).

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by tidusjar** [comment]
If you press the "Select..." On a TV show does it show the episodes as available?

**Comment by tidusjar** [comment]
I can see the issue via the log. Thanks for reporting

**Comment by bozrdang** [comment]
If I press the "Select..." on a TV Show it does nothing.  The page reloads but nothing new is displayed.

**Comment by tidusjar** [comment]
Are your shows in collections?

**Comment by tidusjar** [comment]
Can you please manually run the cacher from the emby settings menu

**Comment by bozrdang** [comment]
Shows are not in collections.  Didn't even know that was possible.  Updated to 3.0.3458 and reran the cacher.  Shows still act the same.

[new_ombi_log.txt](https://github.com/tidusjar/Ombi/files/2153172/new_ombi_log.txt)

**Comment by tidusjar** [comment]
Fixed in develop

**Comment by bozrdang** [comment]
Episodes now show when I click on "Select...", but they all say Processing Request under Status.  All shows still show a Request button.  Even shows that I have all the episodes for.  So it still doesn't seem to know which episodes I have.

[ombi.txt](https://github.com/tidusjar/Ombi/files/2161112/ombi.txt)

**Comment by tidusjar** [comment]
Do any episodes show as available? 

Can you run the content sync wait 10 mins and then send me the log file?

**Comment by bozrdang** [comment]
Not that I can see.  When you say "content sync", do you mean the "Manually Run Cacher" button under Ombi>Settings>Media Server>Emby?  If so< I did that right after I updated to the latest version.  But I will try again and submit log.

**Comment by tidusjar** [comment]
Yeah sorry I mean that button you mentioned.

**Comment by bozrdang** [comment]
OK.  I just did that and everything seems the same.  Every episode I look at says "Processing Request" under status whether I have them in Emby or not.  I'm also not sure why it says "Processing request" because no episodes have been requested..

Here is a screen shot:

![untitled](https://user-images.githubusercontent.com/847595/42281846-c0a7f4d0-7f72-11e8-8688-d4085ba949b4.png)

Here is log:

[ombilog.txt](https://github.com/tidusjar/Ombi/files/2163515/ombilog.txt)

**Comment by bozrdang** [comment]
I noticed there was a new dev build so I updated and tried it.  It may have been there before and I just missed it but I now notice a small green label that says "Available" over by Air Date and the Network labels.  It's very likely that has been there and I just missed it.  Is that how it should be?  It seems like that would easily be missed and, especially for shows that have ended and all episodes are available, it seems pointless to still have the Request button.

Anyhow, all episodes I check still show "Processing Request"

**Comment by tidusjar** [comment]
So the available label appears when there are some episodes available, if all episodes are available then the request button is removed.

The fact that it states processing request is that there was a request for it, once it's available on Emby it should show as available.

I'll have to take a further look.

**Comment by bozrdang** [comment]
But it shows Processing Request for every single episode I look at.  And no shows or episodes have ever been requested yet.  Furthermore, if I go to the Requests tab under TV shows, Ombi lists nothing as I would expect.

**Comment by tidusjar** [comment]
In that case are they monitored In sonarr? Since that would also make them
as processing.

**Comment by bozrdang** [comment]
Yes, they are still monitored in Sonarr.  I just set some of them to unmonitored and it didn't change anything. I even ran the Emby Cacher again just in case but it didn't change anything.

**Comment by tidusjar** [comment]
Hey @bozrdang Can you contact me on Discord?

**Comment by bozrdang** [comment]
It's a lot better and seeing most of my episodes now, but it does not see that I have the 2nd part of two part episodes that are a single video file.  Sonarr and Emby both show that I have them but Omby shows a Request button for them.

Emby shows episodes like this as a single entry  with two episode numbers as seen in the pic below:

![untitled](https://user-images.githubusercontent.com/847595/42395157-d834eb44-812a-11e8-966b-bc2049b85432.jpg)

**Comment by tidusjar** [comment]
Ok great, can you raise a separate issue for that since it's not really
related to this issue and it will be easier to sort that way.

Thanks
