### ISSUE TITLE
Ombi doesn't see that I have the 2nd part of some 2-part episodes [Emby]

### ISSUE THREAD

**Issue by bozrdang** [tidusjar/Ombi#2374]
#### Ombi build Version:

V 3.0.3472

#### Update Branch:

Dev

#### Media Sever:

Emby

#### Media Server Version:

3.4.1.0

#### Operating System:

Linux (Docker)

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

[ombilog.txt](https://github.com/tidusjar/Ombi/files/2171929/ombilog.txt)


```

#### Problem Description:

Ombi does not see that I have the 2nd part of two part episodes that are a single video file. Sonarr and Emby both show that I have them both but Omby shows a Request button for them.

Emby shows episodes like this as a single entry with two episode numbers as seen in the pic below:

![untitled](https://user-images.githubusercontent.com/847595/42399248-1cfe35e0-813b-11e8-8535-d30a6fb2698c.jpg)

#### Reproduction Steps:

Please include any steps to reproduce the issue, this the request that is causing the problem etc.

**Comment by jaycedk** [comment]
Any news on this issue, have this issue too.

**Comment by goldenpipes** [comment]
@tidusjar this was fixed in develop yes?

**Comment by tidusjar** [comment]
Not yet

**Comment by MnM001** [comment]
Hi,

Any progress on this issue? I think it needs to be fixed as the way it presents the information it looks like the whole is missing not just an episode... one has to drill down a lot to find out that only one is (whn in fact even that 1 episode is actually not missing).

**Comment by tidusjar** [comment]
No there is no progress on this issue yet. 

Please keep in mind that I have a full time job, a 2 year old and a wife at home. Any spare time I have is spent on Ombi. So if I've not got around to doing this yet, it's because I've not had time.

**Comment by tidusjar** [comment]
So I'm currently looking into this and not sure if this is actually achievable, calling the Emby API for 2-Part episodes, Emby is only listing it as 1 episode. You can see this if you view the Metadata on that episode.

For example
![image](https://user-images.githubusercontent.com/6642220/52744883-b30ca280-2fd5-11e9-9bb9-c201d49d455c.png)


As you can see this is episode 17 & 18, but the Episode Number is listing this as only episode 17.


@LukePulverenti do you have any idea how I can work out from the Emby API if a episode is a 2-Part episode? Other than trying to parse the Title?

**Comment by LukePulverenti** [comment]
Sorry for the delay. There will be an IndexNumberEnd property that can give you the number range. So in this example, it would be 18.

**Comment by tidusjar** [comment]
This has been fixed in the develop branch! 🎉 🎈

**Comment by anujpuri85** [comment]
@tidusjar I know this issue has been closed, but I'm on the new version 4, and I'm still seeing this problem. Images attached of it showing the show is partially available, and that the second part of an episode has not been requested, even though I have it in emby as two parts/episodes in one file.

![Partially Available](https://user-images.githubusercontent.com/9307523/94709918-df407880-030b-11eb-921c-3fb39cfe53f0.PNG)
![Second Part Not Requested](https://user-images.githubusercontent.com/9307523/94709925-e10a3c00-030b-11eb-8dcd-16487490a8cc.PNG)

**Comment by theradiostar** [comment]
I am seeing this issue as well in v4.

Thank you for all your work on Ombi!
