### ISSUE TITLE
Not receiving notifications via Pushover

### ISSUE THREAD

**Issue by jojogrosso** [tidusjar/Ombi#2385]
#### Ombi build Version:

V 3.0.3421

#### Update Branch:

master

#### Media Sever:

Plex

#### Media Server Version:

1.13.4.5251

#### Operating System:

Windows Server 2016

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

2018-07-13 20:36:27.783 -04:00 [Debug] Searching : "test"
2018-07-13 20:36:27.807 -04:00 [Debug] Search Result: "Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult"
2018-07-13 20:36:29.011 -04:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/movie/298027?api_key=b8eabaf5608b88d0298aa189dd90bf00
2018-07-13 20:36:29.027 -04:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/movie/298027?api_key=b8eabaf5608b88d0298aa189dd90bf00 Because we got Status Code: TooManyRequests
2018-07-13 20:36:31.401 -04:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/movie/529564?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates
2018-07-13 20:36:31.415 -04:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/movie/529564?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates Because we got Status Code: TooManyRequests
2018-07-13 20:36:41.586 -04:00 [Warning] Tried auto sending movie but failed. Message: "(null)"
2018-07-13 20:46:15.989 -04:00 [Debug] Search Result: "Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult"
2018-07-13 20:46:18.282 -04:00 [Debug] Searching : "s"
2018-07-13 20:46:18.347 -04:00 [Debug] Search Result: "Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult"
2018-07-13 20:46:19.388 -04:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/movie/651?api_key=b8eabaf5608b88d0298aa189dd90bf00
2018-07-13 20:46:19.403 -04:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/movie/651?api_key=b8eabaf5608b88d0298aa189dd90bf00 Because we got Status Code: TooManyRequests
2018-07-13 20:46:19.481 -04:00 [Debug] Searching : "spider"
2018-07-13 20:46:19.495 -04:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/search/movie?api_key=b8eabaf5608b88d0298aa189dd90bf00&query=spider
2018-07-13 20:46:19.510 -04:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/search/movie?api_key=b8eabaf5608b88d0298aa189dd90bf00&query=spider Because we got Status Code: TooManyRequests
2018-07-13 20:46:25.690 -04:00 [Error] StatusCode: TooManyRequests, Reason: , RequestUri: http://api.themoviedb.org/3/movie/17532?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates
2018-07-13 20:46:25.705 -04:00 [Error] Retrying RequestUri: http://api.themoviedb.org/3/movie/17532?api_key=b8eabaf5608b88d0298aa189dd90bf00&append_to_response=videos,release_dates Because we got Status Code: TooManyRequests
2018-07-13 20:46:29.541 -04:00 [Debug] Search Result: "Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult, Ombi.Api.TheMovieDb.Models.MovieSearchResult"

```

#### Problem Description:

I stopped receiving "new request" notifications from Pushover about a month ago. When I "test" it, I get the test notification. I tried to disable it. Saved it, then re-enabled it, but I'm still not receiving them.

#### Reproduction Steps:

I used to receive notifications from Pushover when someone requested a movie.

**Comment by jimphreak** [comment]
+1 Having the same issue.  Stopped working also about a month ago.  Tests work.

**Comment by anojht** [comment]
could you remove any quotes, single or double from the notification templates and try again?

**Comment by jimphreak** [comment]
I removed all quotes, no luck.  This is what my new request code looks like:

Hello! The user {RequestedUser} has requested the {Type} {Title}! Please log in to approve this request. Request Date: {RequestedDate}

**Comment by anojht** [comment]
I think the problem lies with certain notification variables. I see that you have made some changes to the template, can you try changing the template to the following for troubleshooting purposes: 
`Hello! The user {UserName} has requested the {Type} {Title}!`

**Comment by jimphreak** [comment]
Just tested this.  No change.

**Comment by jojogrosso** [comment]
I haven’t changed mine. I believe it’s still default showing:
```
Hello! The user '{UserName}' has requested the {Type} '{Title}'! Please log in to approve this request. Request Date: {RequestedDate}
```

I just changed it to remove quotes, as requested, to show:
```
Hello! The user {UserName} has requested the {Type} {Title}’ Please log in to approve this request. Request Date: {RequestedDate}
```

Still no luck.

**Comment by anojht** [comment]
@jojogrosso remove everything you have for the template and paste exactly this: `Hello! The user {UserName} has requested the {Type} {Title}!` and then try it please

**Comment by jojogrosso** [comment]
@anojht I just tried that, and I still didn't get a notification.

**Comment by anojht** [comment]
We had a similar issue before and that template setting fixed it. But it looks like this might be a different bug, thanks for trying it!

**Comment by jojogrosso** [comment]
No, problem. If you want me to try anything else, let me know. Thanks for working on this!

**Comment by gold007eye** [comment]
I am having the same issue, but with 1 difference.  I am receiving the notifications, but anything variable content is mostly missing. 

Example:
Your Request of {Title} on {ApplicationName} is now available!
Comes through as:
Your request of  on Plex Server

**Comment by jojogrosso** [comment]
Well, I just got a notification. Looks like my zombie has been updated to 3.0.3477.  Was there a fix for this in this version ?

**Comment by tidusjar** [comment]
Not as far as I am aware, so does this work?

**Comment by rdavey228** [comment]
Doesnt work for me - I just updated.

I get "Request Accepted" notifications but the initial notification to say a user has requested an item never works.

Just updated to 3.0.3477

**Comment by tidusjar** [comment]
Can you please post any relevant logs

**Comment by loeschj** [comment]
Just wanted to add to this as I am experiencing the same thing with the Slack and Pushover notifications. I decided to copy every single variable from the Wiki and add them in and this is the output:

Name of Variable - {VariableOutput}

UserName - 
Alias - {Alias}
RequestedDate - 
Type - 
Title - The Great Gatsby
Overview - 
Year - 
EpisodesList - 
SeasonsList - 
PosterImage - 
ApplicationName - Plex Requests
ApplicationUrl - 
IssueDescription - This is my description
IssueCategory - 
IssueSubject - This is my subject
NewIssueComment - 
LongDate - Tuesday, August 14, 2018
ShortDate - 8/14/18
LongTime - 7:54:30 PM
ShortTime - 7:54 PM

**Comment by gold007eye** [comment]
I'm not sure if this helps, but after updating to 3.0.3477 some messages are coming through ok, but others are still not filling in the variables.  this is the only info i see in the log (this was after trying a fresh start of OMBI).

![image](https://user-images.githubusercontent.com/4365462/44288888-8b5f9c00-a237-11e8-8c69-b2b605c65936.png)

**Comment by tidusjar** [comment]
Interesting, does your Application Name also contain special characters? it sounds like Pushover is truncating the text once it finds a special character

Can you check this and get back to me?

**Comment by gold007eye** [comment]
It was funny you asked this as I was just noticing that.  I tried changing {ApplicationName} to '{ApplicationName}' but then nothing showed up for that variable.

**Comment by gold007eye** [comment]
So it does seem like certain special characters might be interfering with either the code output of notifications or just with pushover notifications.

**Comment by tidusjar** [comment]
Fixed in develop

**Comment by jojogrosso** [comment]
Hi, I hate to re-open this, but I am now on build 3.0.4680 with the same issue here. The tests work, but I don't get New Request notifications anymore. I don't have any special characters either.

**Comment by Nabukodonosor** [comment]
I'm on 4.10.2 and still don't get Pushover nothifications. Can't believe they still can't fix this. :/

**Comment by tidusjar** [comment]
Raise a new issue. This one is closed.
