### ISSUE TITLE
Current TV Shows Not Being Imported Into Ombi (Sonarr)

### ISSUE THREAD

**Issue by dcplaya** [tidusjar/Ombi#2514]
#### Ombi build Version:

V 3.0.3587

#### Update Branch:

Master

#### Media Sever:

Plex

#### Media Server Version:

Plex 1.13.7.5369

#### Operating System:

Ubuntu 18.04 With Ombi Running In Docker

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server VPS
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting EP Cacher
info: Ombi.Notifications.Agents.MobileNotification[0]
      there are no admins to send a notification for RequestApproved, for agent Mobile
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting Plex Content Cacher
info: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Starting to cache the content on server VPS

```

#### Problem Description:

Ombi does not update the list of TV Shows when running a scan. I have tried manual full, manual recent, and letting auto scan nightly. I recently deleted the Ombi db (lost admin password, nothing to do with this) so the TV list is completely empty but the Movies list. I opened up the database and the Sonarr cache is empty (Radarr cache has data)

#### Reproduction Steps:

N/A

**Comment by dcplaya** [comment]
![screenshot 2018-09-17 at 5 55 06 am](https://user-images.githubusercontent.com/1105320/45624139-48633500-ba3e-11e8-9a15-e16df5f6ec24.png)


Yes, and successfully connects as well for the test.

**Comment by tidusjar** [comment]
How long have you waited? Since the jobs run on a set schedule (you can see on the jobs page)

**Comment by dcplaya** [comment]
Ombi has been running for over 2 days now. Below is a screenshot of all the cron jobs in Ombi.  Is there a debug mode I can enable to see more detailed logs? Is there a way to force the sonarr job to start just so I can see any errors that pop up in the log? Is there a verbose option for the log too?

![screenshot 2018-09-17 at 10 27 32 am](https://user-images.githubusercontent.com/1105320/45639264-5fb51900-ba64-11e8-8478-50fc1c296cb0.png)

**Comment by CornHead764** [comment]
+1 on this. Just installed the latest build of Ombi through apt. TV was working fine before the update, and is no longer the case. Movies are still fine.

**Comment by tidusjar** [comment]
Can someone check the logs after the Sonarr Sync job has run and post it here?

**Comment by tidusjar** [comment]
I cannot seem to reproduce this. Is it all tv shows or just a few?

**Comment by dcplaya** [comment]
> I cannot seem to reproduce this. Is it all tv shows or just a few?

For me, its every single TV show. I can even send you my DB if you would like. The Sonarr cache doesn't have a single entry in it.

**Comment by tidusjar** [comment]
No that's fine. Ideally I need some log files.

**Comment by dcplaya** [comment]
This is today's log and yesterdays log. 

[log-20180917.txt](https://github.com/tidusjar/Ombi/files/2395686/log-20180917.txt)
[log-20180916.txt](https://github.com/tidusjar/Ombi/files/2395687/log-20180916.txt)

**Comment by tidusjar** [comment]
Looks like there is an issue with your connection to Sonarr. In Sonarr do you have a URL Base set?

![image](https://user-images.githubusercontent.com/6642220/45754331-4c947b80-bc13-11e8-83c1-0fdcf9204574.png)

**Comment by dcplaya** [comment]
My Sonnar web url is just `https://tv.TLDN.com` and when I even test the connection in Ombi, it says connection succeeded. It gets the root folders and profiles from Sonarr with no issues.

**Comment by jmbrown79** [comment]
Hi, I am having a similar issue.  Only some of my TV Shows are syncing with Ombi.  Some show as available to watch and others (which are in my library) are showing Request.  I have looked online and tried changing my Agent in Plex to make sure TVDB is first and selected as well as refreshing all meta data and doing a manual sync.  Its still not working for me.  Is there anything else I may have missed I could try?

Thanks!
-Jason

**Comment by TheRealStarboy** [comment]
Hi seems I am having a similar issue as well. Although this could be an issue with me since I am first time user just setting everything up. All the movies worked perfectly but I have several TV shows that do not show as Available. I thought I may have done something wrong so I started over from scratch and setup Ombi again and the exact same shows would not show as Available. I changed the settings in the appsettings.json file to set the logging to Trace. After that I was able to capture this from the console logging. It looks like it is going fine then just gets stuck processing that one series then finally dies the last line of the text below is where it just dies. The TV section it is scanning has 21682 episodes (which matches what Plex shows for episode count) according to this log entry: Total Epsiodes found for TV Shows = 21682


dbug: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      We already have movie Changing Lanes
dbug: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      We already have movie D.A.R.Y.L.
dbug: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      We already have movie Breaking In
dbug: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      We already have movie Action Point
dbug: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      We already have movie Tag
dbug: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      We already have movie Deadpool 2
dbug: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      Found some episodes, this must be a recently added sync
dbug: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      We already have show Lethal Weapon checking for new seasons
dbug: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      We already have show Hawaii Five-0 checking for new seasons
dbug: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      We already have show The Good Place checking for new seasons
dbug: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      We already have show The Big Bang Theory checking for new seasons
dbug: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      We already have show South Park checking for new seasons
dbug: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      We already have show Lethal Weapon checking for new seasons
dbug: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      We already have show The Big Bang Theory checking for new seasons
dbug: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      We already have show Killjoys checking for new seasons
dbug: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      We already have show Elementary checking for new seasons
dbug: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      We already have show Killjoys checking for new seasons
dbug: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      We already have show The Dukes of Hazzard checking for new seasons
dbug: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      We already have show Hogan's Heroes checking for new seasons
dbug: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      We already have show Elementary checking for new seasons
dbug: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      We already have show Killjoys checking for new seasons
dbug: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      We already have show Elementary checking for new seasons
dbug: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      We already have show Killjoys checking for new seasons
dbug: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      We already have show Elementary checking for new seasons
dbug: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      We already have show Our Cartoon President checking for new seasons
dbug: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      We already have show Killjoys checking for new seasons
dbug: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      We already have show Legend of the Seeker checking for new seasons
dbug: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      We already have show Legend of the Seeker checking for new seasons
dbug: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      We already have show Legend of the Seeker checking for new seasons
dbug: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      We already have show Legend of the Seeker checking for new seasons
dbug: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      We already have show Legend of the Seeker checking for new seasons
dbug: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      We already have show Legend of the Seeker checking for new seasons
dbug: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      We already have show Legend of the Seeker checking for new seasons
dbug: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      We already have show Legend of the Seeker checking for new seasons
dbug: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      We already have show Legend of the Seeker checking for new seasons
dbug: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      We already have show Legend of the Seeker checking for new seasons
dbug: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      We already have show Legend of the Seeker checking for new seasons
dbug: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      We already have show Legend of the Seeker checking for new seasons
dbug: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      We already have show Legend of the Seeker checking for new seasons
dbug: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      We already have show Legend of the Seeker checking for new seasons
dbug: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      We already have show Legend of the Seeker checking for new seasons
dbug: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      We already have show Legend of the Seeker checking for new seasons
dbug: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      We already have show Legend of the Seeker checking for new seasons
dbug: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      We already have show Legend of the Seeker checking for new seasons
dbug: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      We already have show Legend of the Seeker checking for new seasons
dbug: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      We already have show Legend of the Seeker checking for new seasons
dbug: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      We already have show Legend of the Seeker checking for new seasons
dbug: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      We already have show Legend of the Seeker checking for new seasons
dbug: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      We already have show Legend of the Seeker checking for new seasons
dbug: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      We already have show Legend of the Seeker checking for new seasons
dbug: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      We already have show Legend of the Seeker checking for new seasons
dbug: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      We already have show Legend of the Seeker checking for new seasons
dbug: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      We already have show Legend of the Seeker checking for new seasons
dbug: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      We already have show Legend of the Seeker checking for new seasons
dbug: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      We already have show Legend of the Seeker checking for new seasons
dbug: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      We already have show Legend of the Seeker checking for new seasons
dbug: Ombi.Schedule.Jobs.Plex.PlexContentSync[0]
      We already have show Legend of the Seeker checking for new seasons

**Comment by colfin22** [comment]
I'm having a similar issue. I use Emby and sonarr. Some of my TV shows aren't getting scanned into the database. Tried a reinstall from scratch but get exactly the save issue. I'll get some logs up later after work

**Comment by tidusjar** [comment]
People are replying to this issue with a different problem. This issue is about Ombi not syncing with **Sonarr**.

**Comment by dcplaya** [comment]
> People are replying to this issue with a different problem. This issue is about Ombi not syncing with **Sonarr**.

I am actually still having this issue and my Ombi is now on v3.0.3795 (docker)

**Comment by tidusjar** [comment]
So your issue is that we are trying to communicate with Sonarr but something is closing the connection from the information in your log file:
 `Unable to read data from the transport connection`

**Comment by dcplaya** [comment]
> So your issue is that we are trying to communicate with Sonarr but something is closing the connection from the information in your log file:
> `Unable to read data from the transport connection`

The only thing that I have that could be a little weird is I have Ombi connecting to Sonarr (and Radarr and Plex and now Lidarr) via an nginx reverse proxy. I don't think that should change anything...

**Comment by tidusjar** [comment]
Are you able to change it to a direct connection to see if that makes a difference?

**Comment by dcplaya** [comment]
I'll try it later tonight and get back to you. I have to rework my ansible playbook to open that port up to more than just localhost.

**Comment by Handl3vogn** [comment]
Think I'm having same issue.
Movies from radarr shows as requested and available, but on tv shows all it says is request. 
Non of them is showing requested or available.
![2](https://user-images.githubusercontent.com/43939607/46587906-5d5a4380-ca93-11e8-8206-c1790782f64b.png)
![3](https://user-images.githubusercontent.com/43939607/46587907-5d5a4380-ca93-11e8-832c-6e59595893b1.png)

**Comment by dcplaya** [comment]
> Think I'm having same issue.
> Movies from radarr shows as requested and available, but on tv shows all it says is request.
> Non of them is showing requested or available.

My TV request/suggestion page looks exactly like yours. GoT and Breaking Bad are first in the list and it thinks I do not have them when in fact I have both already.

**Comment by tidusjar** [comment]
What versions of sonarr are you using.

**Comment by Handl3vogn** [comment]
3.0.3795
Master

**Comment by dcplaya** [comment]
> What versions of sonarr are you using.

> 3.0.3795
> Master
> Linuxserver's docker

I think you gave Ombi's version number, not Sonarr's.

I am running the newest Sonarr docker from Suitarr and the version it reports is
`v2.0.0.5251`

**Comment by Handl3vogn** [comment]
Sorry that's correct donate is
2.0.0.5228

**Comment by tidusjar** [comment]
Can someone please create me a user on their ombi install and then email me their `Ombi.db` file with the credentials for the user you just created so i can see this issue in my debug environment.

Please also include an example of what is missing

**Comment by dcplaya** [comment]
> Can someone please create me a user on their ombi install and then email me their `Ombi.db` file with the credentials for the user you just created so i can see this issue in my debug environment.
> 
> Please also include an example of what is missing

Email sent with my db, login credentials are in the email.

Side note: After creating your user, I am unable to delete the user...

**Comment by tidusjar** [comment]
Known issue

**Comment by dcplaya** [comment]
It safe to remove it from the db manually? I think it's in the aspNetUsers table? Or something similar to that.

**Comment by Handl3vogn** [comment]
Just have to say after letting it sitt for the night mine has begun to work. 
It now shows available on shows I have all episodes. 
example.
![4](https://user-images.githubusercontent.com/43939607/46612834-eadc7880-cb11-11e8-8369-daf0cda4c335.PNG)

**Comment by tidusjar** [comment]
Please check with the latest release

**Comment by Handl3vogn** [comment]
This latest release broke it for movies. Now it only shows what is available.
Earlier it showed requested on movies added trough radarr now it only shows requested on the few I added trough ombi and only as long as I keep them in the request list.

**Comment by tidusjar** [comment]
I don't understand. This issue has nothing to do with movies. If you have a
different issue please raise it or it will be ignored

**Comment by dcplaya** [comment]
I updated a few days ago and let it run to see what happens. Now the webpage is showing it hasn't cached either TV shows or movies! 

For example, I know 100% I have both the following movies/TV show

![image](https://user-images.githubusercontent.com/1105320/47249940-c06ea300-d3ce-11e8-8c9e-60377203d08e.png)

![image](https://user-images.githubusercontent.com/1105320/47249941-cf555580-d3ce-11e8-9827-bdd28faa8171.png)


But when I request either of them, it tells me the request has already been filled.

TV Show Request
![image](https://user-images.githubusercontent.com/1105320/47249954-0a578900-d3cf-11e8-81b6-0f3c7de8896a.png)

Movie Request
![image](https://user-images.githubusercontent.com/1105320/47249956-1fccb300-d3cf-11e8-8901-ef722993b4c2.png)

**Comment by tidusjar** [comment]
Can you please create a local user in ombi, then email me the 3 .dB files, don't worry about the schedules.db and in the email include the username and password that you created so I can run this in my debug environment

**Comment by dcplaya** [comment]
Email sent with the database files. Password is in the email as well.

**Comment by tidusjar** [comment]
Thanks! 

Fixed in develop

**Comment by hansenc0705** [comment]
I'm still noticing this behavior where it gives me the option to request a tv show (that is already in Sonarr) and when i click request it says its already there but still doesnt show up in Ombi.

**Comment by hansenc0705** [comment]
I'm on 3.0.3988

**Comment by cryogenx** [comment]
I'm seeing this issue in current develop version.. i can't seem to make it sync with sonar or radar however it will add movies to radarr

**Comment by Inrego** [comment]
I just installed Ombi for the first time, and set it up with Radarr and Sonarr and Plex. I'm running version 3.0.4659 (released a few hours ago?).

I also have this problem. None of my TV shows are shown as "Available". When requesting a show that I already have, I get the popup saying

> We already have this request, please choose the "Select..." option to refine your request

**Comment by tidusjar** [comment]
For TV shows to become available, every episode need to be available.

**Comment by Inrego** [comment]
Every episode is available. Look here:
![image](https://user-images.githubusercontent.com/2242329/60549838-5876a780-9d26-11e9-9bbc-b0c08f0050ef.png)

And in Sonarr:
![image](https://user-images.githubusercontent.com/2242329/60549880-79d79380-9d26-11e9-93b5-7ecdd4659602.png)

**Comment by Inrego** [comment]
It even says "Processing Request" for shows that I didn't "Request" in Ombi. But I already have them in Sonarr and Plex.

**Comment by Inrego** [comment]
Sorry, it was a mistake in my Plex config combined with not having run a full Plex Scan. All good now.

**Comment by gcorgnet** [comment]
Hi, I am getting the same issue. Ombi talking to Emby and Sonarr.
I can see my OmbiExternal DB has some content in SonarrCache but nothing in the EmbyEpisode table...

Movies work well though...
Any ideas?

Thanks
