### ISSUE TITLE
Music requests are stuck on processing request

### ISSUE THREAD

**Issue by anojht** [tidusjar/Ombi#2536]
Music requests are stuck on processing request and do not update to available status.

**Comment by tidusjar** [comment]
Seems to be working fine for me

**Comment by tidusjar** [comment]
![image](https://user-images.githubusercontent.com/6642220/46036678-03a26280-c0fe-11e8-86d2-97fc5b770905.png)

**Comment by anojht** [comment]
![image](https://user-images.githubusercontent.com/21053678/46036980-bdc4aa80-c0bb-11e8-9fe7-1808d0f266f5.png)

Odd, I have an album stuck in processing. Any way to force a sync?

**Comment by tidusjar** [comment]
The Lidarr sync should run every 40 minutes on the hour, what does it look like in Lidarr?

**Comment by tidusjar** [comment]
Fixed in develop. We currently needed the album to be monitored. So i've change it so we dont need to monitor it now.

**Comment by screwfaze** [comment]
Hi I am on the latest Dev and this is still happening should I open a new ticket?

Thanks
