### ISSUE TITLE
Newsletter incorrectly sending episodes and not sending them at all

### ISSUE THREAD

**Issue by jwor80** [tidusjar/Ombi#2623]
#### Ombi build Version:

V 3.0.3945

#### Update Branch:

master

#### Media Sever:

Emby

#### Media Server Version:

3.5.3.0

#### Operating System:

Windows 10

#### Ombi Applicable Logs (from `/logs/` directory or the Admin page):

```

[log-20181026.txt](https://github.com/tidusjar/Ombi/files/2525503/log-20181026.txt)


```

#### Problem Description:

My Emby DB sync's at 10 till the hour and the newsletter goes out every hour. When I add new TV Shows they are not always going out in the newsletter and sometimes I receive newsletters that contain old TV Shows that should not be going out.

#### Reproduction Steps:

Troubleshooting steps:

1. I removed the OmbiExternal.db file and re-created it.
2. I noticed the OmbiExternal.db contains episodes that I do not have in Emby. These episodes existed before and after the OmbiExternal.db re-creation.
3. There were no new episodes added for almost 2 days and randomly I received a newsletter at 4am for 3 shows and 2 of the 3 shows contained multiple episodes.
4. The log file has been throwing errors for plex but I'm using Emby so I'm not sure those errors apply.
5. Sometimes the log file logs information about the number of Movies/Shows to send but most of the time it does not.

**Comment by jwor80** [comment]
I just noticed the newsletter that I referenced in this issue is for future episodes that I do not have in my collection.  If I search the future episode title in Emby it appears with a label of "unaired" but I believe Ombi believes that I already have this episode.

**Comment by jwor80** [comment]
I worked with guys from Emby and they said to make sure we are excluding show with a LocationType of "Virtual".

**Comment by jwor80** [comment]
I'm not sure if other Emby users are having this issue in Ombi or not.  I've had to shut off the TV Shows newsletter.  If the Emby team didn't make changes on their side I'm not sure why my older versions of Ombi are sending out incorrect newsletters.  Here is my post with the Emby team https://emby.media/community/index.php?/topic/64651-unaired-episodes/

**Comment by tidusjar** [comment]
I plan to address this soon

**Comment by tidusjar** [comment]
I was actually passing in the exclude virtual stuff, but I was passing in Virtual item=False but it should have been IsVirtualItem=False!

Fixed in develop

**Comment by jwor80** [comment]
I test in development 3.0.3966 but I'm still seeing the issue.  I restored one of my old databases > searched for an unaired episode in the database to verify it didn't exist. I sent a test newsletter and verified the episode was not in the newsletter.  After that I manually ran the Emby cacher and sent a test newsletter.  The newsletter showed the unaired episode and it was back in the database.

**Comment by jwor80** [comment]
I was able to revert back to 3.0.3421 and fix my issue.  Version 3.0.3477 pulled in my unaired episodes

**Comment by tidusjar** [comment]
Thanks that helps the investigation

**Comment by tidusjar** [comment]
How do you make emby show future episodes?

**Comment by jwor80** [comment]
The only way I know how is to search for the name of the future episode. The episode name will appear in the search with a red unaired label on it.

**Comment by tidusjar** [comment]
Fixed in develop,

Your best bet is to clear your EmbyContent and EmbyEpisodes data in the OmbiExternal.db using something like SQLiteBrowser to reset it.
