### ISSUE TITLE
"Delete issues after they have been resolved" setting does not work

### ISSUE THREAD

**Issue by GldRush98** [tidusjar/Ombi#2802]
I have this set to 1 day on my Ombi install, but resolved issues are never deleted. On top of that, there is no way to delete them through Ombi. I've had to go digging through the database every once in a while to clean theses up. Any thoughts?

1. Settings -> Configuration -> Issues -> [X] Delete issues after they have been resolved. Set days to 1.
2. Create an issue.  Mark it resolved.
3. Wait 1 day (or any amount of days).
4. Observe the resolved issue is never deleted.

This is the linuxserver docker package.
Version: 3.0.4119
Media Server: Plex

**Comment by tidusjar** [comment]
Please can you update this issue and use the template.

**Comment by tidusjar** [comment]
This has been fixed in the develop branch! 🎉 🎈

**Comment by dearekaelle** [comment]
running version 3.0.4727 in a docker. this seems still not resolved. issues won't auto delete once resolved. 

System.IIssuesPurge is being launched but resolved issues remain at place after defined time has lapsed

2019-08-17 11:19:00.001 +02:00 [Debug] Calling Execute on job System.IIssuesPurge
2019-08-17 11:19:00.003 +02:00 [Debug] Trigger instruction : NoInstruction
2019-08-17 11:19:29.553 +02:00 [Debug] Batch acquisition of 0 triggers
2019-08-17 11:19:52.986 +02:00 [Debug] Batch acquisition of 1 triggers
2019-08-17 11:20:00.000 +02:00 [Debug] Batch acquisition of 0 triggers

**Comment by dearekaelle** [comment]
would you please reopen this issue?
