### ISSUE TITLE
Ombi Not Marking Albums as "Available" for Music

### ISSUE THREAD

**Issue by millertime0503** [tidusjar/Ombi#2803]
**Describe the bug**
I think this is different from [#2626](https://github.com/tidusjar/Ombi/issues/2626), as only Music is a problem. It will display "Monitored" for albums that are monitored in Lidarr, but says they are Not Requested, gives you the option to Request, and does not mark them available. Don't usually have this issue with Movies or TV.

**To Reproduce**
1. New Windows install, copied ombi.db from v3.0.2-something

**Expected behavior**
Albums that are already available show up as available.

**Screenshots**
![darkside](https://user-images.githubusercontent.com/47581506/52679647-93e51680-2eea-11e9-9d26-0f0bc33bd39f.PNG)

**Logs (Logs directory where Ombi is located)**
Nothing relevant from what I can see.

**Desktop (please complete the following information):**
 - OS: Windows Server 2016 Standard

**Ombi Version (please complete the following information):**
 - Version 3.0.4119

- Media Server [e.g. Plex]
Plex

I'm new to GitHub, so apologies if this is a dupe or I'm just an idiot.

**Comment by tidusjar** [comment]
Are they available in Lidarr?

**Comment by millertime0503** [comment]
Yes. Lidarr and Plex both see them as available.

**Comment by millertime0503** [comment]
Update: New requests made through Ombi (as opposed to existing content already in Lidarr) do not get marked as Available in Ombi after they have been acquired. Tested with album "Compton" by Dr. Dre, the request went through and downloaded, Plex and Lidarr both see it as available, but it still says Processing Request in Ombi.

**Comment by rudyolph** [comment]
same thing happens with my setup.  I'm on Lidarr nightly.  Not sure if that makes a difference.

**Comment by veteze** [comment]
This is happening to me too. Fresh install. First time using lidarr or Ombi. Movies and TV both show as available. Artists that are available show as monitored. And any albums that are in Lidarr show as monitored and it pulls the rating over as well. But it shows the Request link instead of the Available or any link to plex. 

I'm using version 3.0.4256.

Thanks! Love these apps!

**Comment by wptex** [comment]
The issue occurs even if the album is manually marked available. It only shows the status as available under requests, not when searching the album.

**Comment by tidusjar** [comment]
Fixed the issue where the request button was appearing when it shouldn't (in regards to monitored).

**Comment by Qstick** [comment]
Likely fixed in latest nightly of Lidarr.... hopefully

**Comment by tidusjar** [comment]
Thanks A lot!

**Comment by war3zlod3r** [comment]
was this issue ever resolved still having the same problem in Ombi 3.0.4892 Lidarr 0.7.1.1381

**Comment by DamageDoctor** [comment]
> was this issue ever resolved still having the same problem in Ombi 3.0.4892 Lidarr 0.7.1.1381

Yep I am experiencing it to with those versions

![image](https://user-images.githubusercontent.com/19231914/79947096-ad053200-84b4-11ea-9ef2-686ca96bef2c.png)

**Comment by martonbaksa** [comment]
Yes, I am having this above issue that damagedoctor is experiencing and can't seem to fix it.
Thanks!

**Comment by rouggy** [comment]
Same issue here
