### ISSUE TITLE
Not connecting / Syncing to Plex Server 

### ISSUE THREAD

**Issue by waynemillskidals** [tidusjar/Ombi#2866]
It took a few attempts to get the paramaters correct to connect to Plex.
Plex is on the same LAN however when it auto discovers the server it changes the port to the public IP port not the LAN port.

Eventually it connects and when i press test i get success
![screenshot 2019-03-05 at 18 11 42](https://user-images.githubusercontent.com/29538924/53827157-5ec06700-3f72-11e9-9ae3-02b993d002d7.png)

The problem is when i get requests.  They are getting downloaded but Ombi I don't think is syncing correctly

![screenshot 2019-03-05 at 18 11 53](https://user-images.githubusercontent.com/29538924/53827206-7697eb00-3f72-11e9-9dd4-f474e48ff8c6.png)
These are still saying 'awaiting processing' and i have to force the 'mark available' to clear.

I also get the impression the sync is not working as when i try and pull/import Plex users to Ombi this also does not work and i have to enable them manually.

The connections to everything else works (Sonar, Radarr) which is also on the same server as Plex

Any ideas?

**Comment by krisklosterman** [comment]
Ill let someone else give the official answer, but there are scheduled jobs that run the sync between ombi and plex "system"->"Jobs" that I don't think run that often. Plex sync is every two days. Recently Added for plex is ever 30 minutes. But maybe it has something to do with that.

What OS is ombi installed on ? You could also check the logs

**Comment by tidusjar** [comment]
That is correct @krisklosterman 
So what you could do in the meantime on the Plex Settings page in Ombi run the Manual Sync button. That could take 5-10 minutes possibly longer depending on your Plex library size.

That will do the initial sync to get all the content down from Plex, then an iterative smaller sync will run every 30 minutes (Recently Added Sync) that will keep the Ombi upto date in regards with what has been added to Plex.

**Comment by Vaelek** [comment]
I have this same issue. I tail'd the plex and Ombi logs while poking around. When I do a Test Connection for Plex, it succeeds, and I see it in the plex logs, nothing in ombi log. 
When I do a force sync, all or recent, I see nothing in any logs, and nothing ever changes from processing.

**Comment by tpfleck** [comment]
I am having this issue as well as @Vaelek

**Comment by dgcurtis** [comment]
I'm seeing the same thing as well.  I've installed using the apt repo.  Everything looks fine in the UI when I add the plex server but the logs show:
_Apr  1 20:00:37 usenet2 Ombi[30388]:       Getting all content from server *******_
and that's it.  The log in /etc/Ombi/Logs is empty as well.

Most of time, when I go back to the browser and click Media Server->Plex, it doesn't show the plex server info.  I end up having to restart the service to be able to view the Plex server info in the ui.

**Comment by dgcurtis** [comment]
It looks like I must have changed to the devel apt repo.  Devel used to work but something must have recently broke.   I changed back to stable, reinstalled and now it's syncing.

**Comment by tidusjar** [comment]
Make sure you have also set your lang correctly: https://github.com/tidusjar/Ombi/wiki/Common-Errors#proxmox-lxc-containers

**Comment by D0rd** [comment]
Same as @Vaelek and @dgcurtis. Everything was working fine, and today I realized the syncs were not longer working, available new movies on Plex where not showing as available in Ombi. Tried manual triggers to no avail. Tried creating a new docker but no dice. I switched to stable and that fixed it, so confirming that something in devel must have broke. Unfortunately the logs stayed empty for me too, so I don't really have any additional info to help troubleshoot.

**Comment by Coolfeather2** [comment]
same issues here, no log in /etc/Ombi/Logs
Searching for the movie returns that it is available, but status is p"rocessing request" in requests

**Comment by tidusjar** [comment]
Is someone able to identify which version of dev broke it?

**Comment by Coolfeather2** [comment]
I was on stable v3.0.4256  -sorry

checked dev on v3.0.4406, same problem

**Comment by tidusjar** [comment]
This has been fixed in the develop branch! 🎉 🎈

**Comment by Coolfeather2** [comment]
still not quite working for me?
v3.0.4434
Tried clearing externaldb and syncing again

**Comment by tidusjar** [comment]
@Coolfeather2 what's specifically not working for you?

**Comment by Coolfeather2** [comment]
Anything requested is not being marked available in the request tab, but appearing as available in search 

[Images](https://m.imgur.com/a/x3qfqN8)

**Comment by kdizzay** [comment]
Duplicated here as well in latest develop build 3.0.4489 , item shows available under Search but still 'Processing Request' under Requests, same as @Coolfeather2

**Comment by Coolfeather2** [comment]
Hi tidusjar, any progress on this?
Titles still show available in search tab
Titles showing processing requests in request tab
Still present on v3.0.4538
Tested by running scan - did not clear database

**Comment by tidusjar** [comment]
Hi sorry but there has been no further progress on this yet.

Please remember that I have a full time (quite demanding) job, a toddler, a wife and a puppy. 
All of my limited free time is usually spent either developing Ombi, fixing bugs on Ombi or providing support with Ombi, keeping in mind that no one is paying me to do this.

Ombi is currently a 1 person development team. 

So if I have not yet got around to this you now know why 😄

The only way I'm able to reproduce and fix these sorts of issues is to debug Ombi whilst it's connected to your Plex server. If you are happy for me to do this then please PM me on Discord.

**Comment by THCue** [comment]
Same issue for me I believe it's related. Plex Connects no problem but it's not seeing whats in the libraries. In Discord and we been trying to trouble shoot this for about a week.

**Comment by hstorey219** [comment]
I did some testing and found out why I can not connect to the Plex server. If you have on the Plex server under Network settings , Secure Connections set to "Required". Obmi will not connect, but if you change it to Preferred, then Obmi will connect to the Plex Server.

**Comment by tidusjar** [comment]
Need log files to tell what's going on.

**Comment by coyotanark** [comment]
I can confirm I see the same behavior. Available in search but not marked as available on the requests lists. Nothing shows in the logs, feel free to say what would help here to help you solve the issue

**Comment by tidusjar** [comment]
Please set your logs to `Debug`. You can do this in the `appsettings.json` file located where Ombi is installed.

**Comment by tidusjar** [comment]
Can you please follow the above and the run the Manual sync with the latest dev build

**Comment by Coolfeather2** [comment]
```
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Debug",
      "System": "Information",
      "Microsoft": "None",
      "Hangfire": "None"
    }
```

Log:
[log-20190526.txt](https://github.com/tidusjar/Ombi/files/3219951/log-20190526.txt)


Version 3.0.4572
using http://repo.ombi.turd.me/develop/ jessie main


Search:
![image](https://user-images.githubusercontent.com/14107982/58376816-4e35f080-7fa5-11e9-81b0-951cdb3a6640.png)

Request:
![image](https://user-images.githubusercontent.com/14107982/58376800-175fda80-7fa5-11e9-96a9-200f29e6bc64.png)

**Comment by jtelling325** [comment]
> Make sure you have also set your lang correctly: https://github.com/tidusjar/Ombi/wiki/Common-Errors#proxmox-lxc-containers

How would someone running on a seedbox and does not have access to install dir do this?

**Comment by Coolfeather2** [comment]
Contact your host?
