### ISSUE TITLE
Users being spammed with email notifications

### ISSUE THREAD

**Issue by Do-while-Bacon** [tidusjar/Ombi#2955]
**Describe the bug**

Since moving to Quartz, multiple users are receiving email notifications at 2:00 AM (when Plex Sync job runs) alerting them that pieces of media have been made available on Plex. One user has received 4 emails about the same move being made available, each arriving shortly after 2:00 AM.

**To Reproduce**

Install latest development build of Ombi
Configure email notifications
Fulfill a requested movie
Users will receive daily emails about their request being available

**Expected behavior**

Users should only receive one email when the movie is made available

**Logs**

May be related to this error found in the Ombi logs shortly after 2:00 AM:

```
2019-04-27 02:02:05.074 -04:00 [Error] Job Plex.IPlexContentSync threw an unhandled Exception:
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.Execute(IJobExecutionContext context) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentSync.cs:line 119
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
2019-04-27 02:02:05.076 -04:00 [Debug] Batch acquisition of 0 triggers
2019-04-27 02:02:05.077 -04:00 [Debug] Calling Execute on job Plex.IPlexEpisodeSync
2019-04-27 02:02:05.086 -04:00 [Error] Job Plex.IPlexContentSync threw an exception.
Quartz.SchedulerException: Job threw an unhandled exception. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.Execute(IJobExecutionContext context) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentSync.cs:line 119
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
   --- End of inner exception stack trace --- [See nested exception: System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.Execute(IJobExecutionContext context) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentSync.cs:line 119
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)]
2019-04-27 02:02:05.087 -04:00 [Debug] Trigger instruction : NoInstruction
2019-04-27 02:02:05.475 -04:00 [Information] Total Epsiodes found for TV Shows = 24416
```

My SMTP server shows multiple emails going out at 2:00 AM. All of these are redundant:

```
[root@redacted log]# cat maillog | grep 02: | grep to=
Apr 22 02:04:03 redacted postfix/smtp[19590]: E3B1780A1E3D: to=<redacted@gmail.com>, relay=email-smtp.us-east-1.amazonaws.com[54.197.236.193]:587, delay=1.4, delays=0.05/0.03/0.96/0.32, dsn=2.0.0, status=sent (250 Ok 0100016a43a4ec57-0ef85561-3170-4cf4-9d18-33108a170140-000000)
Apr 23 02:02:49 redacted postfix/smtp[7608]: 48AEF80A1E3D: to=<redacted@gmail.com>, relay=email-smtp.us-east-1.amazonaws.com[23.21.45.252]:587, delay=1.1, delays=0.05/0.03/0.76/0.26, dsn=2.0.0, status=sent (250 Ok 0100016a48ca27f8-56984293-461c-4423-9ddd-b5f94aae72f1-000000)
Apr 24 02:04:06 redacted postfix/smtp[23162]: C33F180A1E3D: to=<redacted@gmail.com>, relay=email-smtp.us-east-1.amazonaws.com[50.19.245.95]:587, delay=0.93, delays=0.05/0.02/0.6/0.25, dsn=2.0.0, status=sent (250 Ok 0100016a4df1b210-47536f43-09a4-422d-8776-8a0656314ec1-000000)
Apr 24 02:04:06 redacted postfix/smtp[23163]: D59C080A1E4C: to=<redacted@gmail.com>, relay=email-smtp.us-east-1.amazonaws.com[54.197.236.193]:587, delay=0.86, delays=0.04/0.02/0.59/0.21, dsn=2.0.0, status=sent (250 Ok 0100016a4df1b24c-58bdf1e2-3fea-4cff-bf43-2bbc9f75079a-000000)
Apr 25 02:02:55 redacted postfix/smtp[17560]: 8B3B780A1E3D: to=<redacted@gmail.com>, relay=email-smtp.us-east-1.amazonaws.com[54.221.247.93]:587, delay=1.3, delays=0.05/0.03/0.96/0.29, dsn=2.0.0, status=sent (250 Ok 0100016a5316f941-736e68c5-3692-4bc0-a694-b3f6d3c83ad8-000000)
Apr 26 02:04:09 redacted postfix/smtp[6246]: 0D75B80A1E4D: to=<redacted@gmail.com>, relay=email-smtp.us-east-1.amazonaws.com[54.243.82.153]:587, delay=0.73, delays=0.04/0.03/0.46/0.2, dsn=2.0.0, status=sent (250 Ok 0100016a583e762e-a57be1bb-1d0a-4752-973f-0032afc22c6a-000000)
Apr 26 02:04:09 redacted postfix/smtp[6245]: EF00F80A1E3D: to=<redacted@gmail.com>, relay=email-smtp.us-east-1.amazonaws.com[54.243.163.169]:587, delay=0.97, delays=0.05/0.02/0.68/0.22, dsn=2.0.0, status=sent (250 Ok 0100016a583e76c6-d2088d22-5aba-42ad-825e-597deeb9c432-000000)
Apr 27 02:03:37 redacted postfix/smtp[30966]: A6C1380A1E3D: to=<redacted@gmail.com>, relay=email-smtp.us-east-1.amazonaws.com[54.243.47.236]:587, delay=1.2, delays=0.05/0.03/0.95/0.2, dsn=2.0.0, status=sent (250 Ok 0100016a5d6455b0-95651957-5df4-4bbb-8636-a18416da2f22-000000)
```

**Desktop):**

Linuxserver.io docker container (development) running on CentOS 7.6

**Ombi Version:**

- Version 3.0.4489
- Plex version 1.15.5.994

**Additional information**

It only seems to do these nightly emails for requests that have been fulfilled since updating to a build with Quartz. I.e., it's not sending emails about requests fulfilled several weeks ago when the old job scheduler was used.

**Comment by Do-while-Bacon** [comment]
Not happening in latest build. Looks like this was already fixed. Thanks!

**Comment by jeffkeller87** [comment]
I am on 3.0.4522 (trying to avoid https://github.com/tidusjar/Ombi/issues/2750) and am still seeing this happen with two movies and two users.

No errors or anything, just a log entry like the following after every Media Data Refresh job:

```
2019-04-29 22:12:32.090 -04:00 [Information] We have found the request "xxxx" on Emby, sending the notification
```

Where `xxxx` is the same movie each time. Might be worth reopening this issue @tidusjar.

**Comment by jeffkeller87** [comment]
I manually ran the cacher and saw these two errors. Could the caching for these two movies be failing in such a way that Ombi keeps "rediscovering" them?

```
2019-04-29 22:29:15.065 -04:00 [Error] Job Emby.IEmbyContentSync threw an unhandled Exception: 
Quartz.JobPersistenceException: The job (Emby.IRefreshMetadata) referenced by the trigger does not exist.
   at Quartz.Simpl.RAMJobStore.StoreTriggerInternal(IOperableTrigger newTrigger, Boolean replaceExisting)
   at Quartz.Simpl.RAMJobStore.StoreTrigger(IOperableTrigger newTrigger, Boolean replaceExisting, CancellationToken cancellationToken)
   at Quartz.Core.QuartzScheduler.TriggerJob(JobKey jobKey, JobDataMap data, CancellationToken cancellationToken)
   at Ombi.Schedule.OmbiQuartz.TriggerJob(String jobName, String group) in C:\projects\requestplex\src\Ombi.Schedule\OmbiQuartz.cs:line 79
   at Ombi.Schedule.Jobs.Emby.EmbyContentSync.Execute(IJobExecutionContext job) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Emby\EmbyContentSync.cs:line 59
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
2019-04-29 22:29:15.066 -04:00 [Debug] Batch acquisition of 0 triggers
2019-04-29 22:29:15.066 -04:00 [Error] Job Emby.IEmbyContentSync threw an exception.
Quartz.SchedulerException: Job threw an unhandled exception. ---> Quartz.JobPersistenceException: The job (Emby.IRefreshMetadata) referenced by the trigger does not exist.
   at Quartz.Simpl.RAMJobStore.StoreTriggerInternal(IOperableTrigger newTrigger, Boolean replaceExisting)
   at Quartz.Simpl.RAMJobStore.StoreTrigger(IOperableTrigger newTrigger, Boolean replaceExisting, CancellationToken cancellationToken)
   at Quartz.Core.QuartzScheduler.TriggerJob(JobKey jobKey, JobDataMap data, CancellationToken cancellationToken)
   at Ombi.Schedule.OmbiQuartz.TriggerJob(String jobName, String group) in C:\projects\requestplex\src\Ombi.Schedule\OmbiQuartz.cs:line 79
   at Ombi.Schedule.Jobs.Emby.EmbyContentSync.Execute(IJobExecutionContext job) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Emby\EmbyContentSync.cs:line 59
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)
   --- End of inner exception stack trace --- [See nested exception: Quartz.JobPersistenceException: The job (Emby.IRefreshMetadata) referenced by the trigger does not exist.
   at Quartz.Simpl.RAMJobStore.StoreTriggerInternal(IOperableTrigger newTrigger, Boolean replaceExisting)
   at Quartz.Simpl.RAMJobStore.StoreTrigger(IOperableTrigger newTrigger, Boolean replaceExisting, CancellationToken cancellationToken)
   at Quartz.Core.QuartzScheduler.TriggerJob(JobKey jobKey, JobDataMap data, CancellationToken cancellationToken)
   at Ombi.Schedule.OmbiQuartz.TriggerJob(String jobName, String group) in C:\projects\requestplex\src\Ombi.Schedule\OmbiQuartz.cs:line 79
   at Ombi.Schedule.Jobs.Emby.EmbyContentSync.Execute(IJobExecutionContext job) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Emby\EmbyContentSync.cs:line 59
   at Quartz.Core.JobRunShell.Run(CancellationToken cancellationToken)]

```

**Comment by tidusjar** [comment]
@jeffkeller87 Fixed that error in latest develop
