### ISSUE TITLE
Ombi crashes on first page load

### ISSUE THREAD

**Issue by adwinying** [tidusjar/Ombi#3244]
**Describe the bug**
Ombi crashes after the page is first load. The request page does not list any movies. 

**To Reproduce**
1. Access via URL
2. Ombi Crashes, and no movies are shown on the Request page

**Expected behavior**
Ombi loads with a list of movies on the request page.

**Screenshots**
![image](https://user-images.githubusercontent.com/6265936/68486486-80ea5180-0284-11ea-9b99-6e3d572f0a83.png)

**Logs (Logs directory where Ombi is located)**
Logs do not show any errors

**Desktop (please complete the following information):**
- Ubuntu 18.04 + Docker Compose

**Ombi Version (please complete the following information):**
 - Version: 3.0.4817-master
- Media Server: Plex

**Additional context**
N/A

**Comment by tidusjar** [comment]
I need some logs. Please provide something to go on other than "it doesn't work"

**Comment by ianhirdman** [comment]
I  am also experiencing same issue, have updated to most recent version since inititial discover but issue persists and no movie/tv suggestions are loaded and attempting to use the search function to query external sources also fails, i have discoverd issues in the web console as well as the log files and will provide examples of these below:

Web Console (500 internal Server Errors and DB Column index fail):

`ERROR 
{…}
​
error: {…}
​​
error: "SQLite Error 1: 'no such column: x.RequestId'."
​​
<prototype>: Object { … }
​
headers: {…}
​​
lazyInit: function lazyInit()
​​
lazyUpdate: null
​​
normalizedNames: Map(0)
​​
<prototype>: Object { has: has(), get: get(), keys: keys()
, … }
​
message: "Http failure response for http://x.x.x.x:5000/api/v1/search/Movie/Popular: 500 Internal Server Error"
​
name: "HttpErrorResponse"
​
ok: false
​
status: 500
​
statusText: "Internal Server Error"
​
url: "http://x.x.x.x:5000/api/v1/search/Movie/Popular"
​
<prototype>: Object { constructor: e()
 }
core.js:14597
    Angular 4
    RxJS 5
    Angular 11`

Log file on terminal (More SQLite errors):

`2019-11-09 08:30:02.634 +00:00 [Error] Exception when adding new Movie "Barbie Dreamtopia: Festival of Fun"
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such column: x.RequestId'.
2019-11-09 08:30:02.644 +00:00 [Error] Exception when adding new Movie "The Angry Birds Movie"
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such column: x.RequestId'.
2019-11-09 08:30:02.653 +00:00 [Error] Exception when adding new Movie "Alice Through the Looking Glass"
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such column: x.RequestId'.
2019-11-09 08:30:02.663 +00:00 [Error] Exception when adding new Movie "Alice in Wonderland"
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such column: x.RequestId'.
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such column: x.RequestId'.`

Any help to get this functioning again would be great to get using this amazing tool again :)

Thanks :)

**Comment by adwinying** [comment]
@tidusjar Here are the logs, though I doubt they're of any use... 

By the way this isn't the first time this has happened, I had to remove `Ombi.db` and `OmbiExternal.db` in order to get it working again (which of course, all data is removed in the process...)

```
2019-11-10 21:23:35.404 +09:00 [Information] Default Quartz.NET properties loaded from embedded resource file
2019-11-10 21:23:35.700 +09:00 [Debug] TaskSchedulingThreadPool configured with max concurrency of 10 and TaskScheduler ThreadPoolTaskScheduler.
2019-11-10 21:23:35.732 +09:00 [Information] Initialized Scheduler Signaller of type: Quartz.Core.SchedulerSignalerImpl
2019-11-10 21:23:35.739 +09:00 [Information] Quartz Scheduler v."3.0.7.0" created.
2019-11-10 21:23:35.748 +09:00 [Information] RAMJobStore initialized.
2019-11-10 21:23:35.770 +09:00 [Information] Scheduler meta-data: Quartz Scheduler (v3.0.7.0) 'DefaultQuartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'Quartz.Core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'Quartz.Simpl.DefaultThreadPool' - with 10 threads.
  Using job-store 'Quartz.Simpl.RAMJobStore' - which does not support persistence. and is not clustered.

2019-11-10 21:23:35.771 +09:00 [Information] Quartz scheduler 'DefaultQuartzScheduler' initialized
2019-11-10 21:23:35.771 +09:00 [Information] Quartz scheduler version: 3.0.7.0
2019-11-10 21:23:35.778 +09:00 [Information] JobFactory set to: Ombi.Schedule.IoCJobFactory
2019-11-10 21:23:36.263 +09:00 [Information] Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
2019-11-10 21:23:36.291 +09:00 [Debug] Batch acquisition of 0 triggers
2019-11-10 21:24:04.004 +09:00 [Debug] Batch acquisition of 0 triggers
2019-11-10 21:24:53.330 +09:00 [Information] Default Quartz.NET properties loaded from embedded resource file
2019-11-10 21:24:53.659 +09:00 [Debug] TaskSchedulingThreadPool configured with max concurrency of 10 and TaskScheduler ThreadPoolTaskScheduler.
2019-11-10 21:24:53.691 +09:00 [Information] Initialized Scheduler Signaller of type: Quartz.Core.SchedulerSignalerImpl
2019-11-10 21:24:53.697 +09:00 [Information] Quartz Scheduler v."3.0.7.0" created.
2019-11-10 21:24:53.707 +09:00 [Information] RAMJobStore initialized.
2019-11-10 21:24:53.729 +09:00 [Information] Scheduler meta-data: Quartz Scheduler (v3.0.7.0) 'DefaultQuartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'Quartz.Core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'Quartz.Simpl.DefaultThreadPool' - with 10 threads.
  Using job-store 'Quartz.Simpl.RAMJobStore' - which does not support persistence. and is not clustered.

2019-11-10 21:24:53.730 +09:00 [Information] Quartz scheduler 'DefaultQuartzScheduler' initialized
2019-11-10 21:24:53.730 +09:00 [Information] Quartz scheduler version: 3.0.7.0
2019-11-10 21:24:53.737 +09:00 [Information] JobFactory set to: Ombi.Schedule.IoCJobFactory
2019-11-10 21:24:54.219 +09:00 [Information] Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
2019-11-10 21:24:54.250 +09:00 [Debug] Batch acquisition of 0 triggers
2019-11-10 21:25:21.060 +09:00 [Debug] Batch acquisition of 0 triggers
2019-11-10 21:25:44.237 +09:00 [Debug] Batch acquisition of 0 triggers
```

**Comment by tidusjar** [comment]
Fixed in v3.0.4887

**Comment by ianhirdman** [comment]
Legend ... thank you so much 😊👍👌

**Comment by adwinying** [comment]
@tidusjar Updated to v3.0.4887 but it's still not working for me... At least I got some useful logs:

```
ombi            | Hello, welcome to Ombi
ombi            | Valid options are:
ombi            | Ombi 3.0.4887-master
ombi            | Copyright (C) 2019 Ombi
ombi            |
ombi            |   --host       (Default: http://*:5000) Set to a semicolon-separated (;) list
ombi            |                of URL prefixes to which the server should respond. For example,
ombi            |                http://localhost:123. Use "*" to indicate that the server should
ombi            |                listen for requests on any IP address or hostname using the
ombi            |                specified port and protocol (for example, http://*:5000). The
ombi            |                protocol (http:// or https://) must be included with each URL.
ombi            |                Supported formats vary between servers.
ombi            |
ombi            |   --storage    Storage path, where we save the logs and database
ombi            |
ombi            |   --baseurl    The base URL for reverse proxy scenarios
ombi            |
ombi            |   --demo       Demo mode, you will never need to use this, fuck that fruit
ombi            |                company...
ombi            |
ombi            |   --help       Display this help screen.
ombi            |
ombi            |   --version    Display version information.
ombi            |
ombi            |
ombi            |
ombi            | We are running on
ombi            | /opt/ombi
ombi            | Hosting environment: Production
ombi            | Content root path: /opt/ombi
ombi            | Now listening on: http://[::]:3579
ombi            | Application started. Press Ctrl+C to shut down.
ombi            | fail: Ombi.ErrorHandlingMiddleware[0]
ombi            |       Something bad happened, ErrorMiddleware caught this
ombi            | Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'duplicate column name: RequestId'.
ombi            |    at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
ombi            |    at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
ombi            |    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
ombi            |    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
ombi            |    at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
ombi            |    at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
ombi            |    at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
ombi            |    at Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
ombi            |    at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
ombi            |    at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
ombi            |    at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
ombi            |    at Ombi.Store.Context.Sqlite.ExternalSqliteContext..ctor(DbContextOptions`1 options) in C:\projects\requestplex\src\Ombi.Store\Context\Sqlite\ExternalSqliteContext.cs:line 16
ombi            |    at lambda_method(Closure , ServiceProviderEngineScope )
ombi            |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
ombi            |    at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
ombi            |    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
ombi            |    at lambda_method(Closure , IServiceProvider , Object[] )
ombi            |    at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator>b__0(ControllerContext controllerContext)
ombi            |    at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
ombi            |    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
ombi            |    at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
ombi            |    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
ombi            |    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
ombi            |    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
ombi            |    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
ombi            |    at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
ombi            |    at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
ombi            |    at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
ombi            |    at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
ombi            |    at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
ombi            |    at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\Middleware\ApiKeyMiddlewear.cs:line 51
ombi            |    at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\Middleware\ErrorHandlingMiddlewear.cs:line 24
```

**Comment by tidusjar** [comment]
Is that actually stopping ombi from working?

**Comment by adwinying** [comment]
Yes, Ombi still crashes and restart.

**Comment by AKPWebDesign** [comment]
I'm seeing the error below when attempting to see the "movies" search tab. I have attempted to run build 4887, perform a search, then upgrade afterwards (as suggested on other issues), but with no luck thus far. I'm running Ombi using the `linuxserver/ombi` Docker image.

```
fail: Ombi.ErrorHandlingMiddleware[0]
    Something bad happened, ErrorMiddleware caught this
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such column: x.RequestId'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.FirstOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\First.cs:line 144
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\Select.cs:line 106
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\AsyncIterator.cs:line 98
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteSingletonAsyncQuery[TResult](QueryContext queryContext, Func`2 compiledQuery, IDiagnosticsLogger`1 logger, Type contextType)
   at Ombi.Store.Repository.PlexServerContentRepository.Get(String providerId) in C:\projects\requestplex\src\Ombi.Store\Repository\PlexContentRepository.cs:line 66
   at Ombi.Core.Rule.Rules.Search.PlexAvailabilityRule.Execute(SearchViewModel obj) in C:\projects\requestplex\src\Ombi.Core\Rule\Rules\Search\PlexAvailabilityRule.cs:line 31
   at Ombi.Core.Rule.RuleEvaluator.StartSearchRules(SearchViewModel obj) in C:\projects\requestplex\src\Ombi.Core\Rule\RuleEvaluator.cs:line 54
   at Ombi.Core.Engine.Interfaces.BaseEngine.RunSearchRules(SearchViewModel model) in C:\projects\requestplex\src\Ombi.Core\Engine\Interfaces\BaseEngine.cs:line 53
   at Ombi.Core.Engine.TvSearchEngine.ProcessResult(SearchTvShowViewModel item) in C:\projects\requestplex\src\Ombi.Core\Engine\TvSearchEngine.cs:line 171
   at Ombi.Core.Engine.TvSearchEngine.GetShowInformation(Int32 tvdbid) in C:\projects\requestplex\src\Ombi.Core\Engine\TvSearchEngine.cs:line 120
   at Ombi.Controllers.SearchController.GetShowInfo(Int32 tvdbId) in C:\projects\requestplex\src\Ombi\Controllers\SearchController.cs:line 274
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\Middleware\ApiKeyMiddlewear.cs:line 51
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\Middleware\ErrorHandlingMiddlewear.cs:line 24
```

**Comment by dudeofawesome** [comment]
I'm also experiencing the `Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such column: x.RequestId'.` error.

**Comment by tidusjar** [comment]
#3253
