### ISSUE TITLE
Movie search doesn't work after upgrade to v3.0.4880

### ISSUE THREAD

**Issue by paulfantom** [tidusjar/Ombi#3253]
**Describe the bug**
Section `Movies` in Search tab doesn't show any movies and don't return any results after trying to search. There is no such problem in `TV Shows` tab.

**To Reproduce**
1. Go to 'Search'
2. Click on 'Movies' (already at this point there is no proposed movies)
3. Enter any movie title and press Enter or click on looking glass icon
4. Nothing happens

**Expected behavior**
Movie propositions are displayed and search works.

**Screenshots**
![Screenshot_20191113_110352](https://user-images.githubusercontent.com/3531758/68753571-91445880-0605-11ea-9769-15be6af3a3d7.png)

**Logs (Logs directory where Ombi is located)**
I think this one is relevant:
```
fail: Ombi.Schedule.Jobs.Plex.PlexContentSync[2008]
      Exception when adding new Movie <NAME_REDACTED>
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such column: x.RequestId'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.AsyncSelectEnumerable`2.AsyncSelectEnumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.FirstOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\First.cs:line 144
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\Select.cs:line 106
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\AsyncIterator.cs:line 98
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteSingletonAsyncQuery[TResult](QueryContext queryContext, Func`2 compiledQuery, IDiagnosticsLogger`1 logger, Type contextType)
   at Ombi.Store.Repository.PlexServerContentRepository.GetFirstContentByCustom(Expression`1 predicate) in C:\projects\requestplex\src\Ombi.Store\Repository\PlexContentRepository.cs:line 90
   at Ombi.Schedule.Jobs.Plex.PlexContentSync.ProcessServer(PlexServers servers, Boolean recentlyAddedSearch) in C:\projects\requestplex\src\Ombi.Schedule\Jobs\Plex\PlexContentSync.cs:line 246
```

**Desktop (please complete the following information):**
 - OS: Fedora 30
 - Browser: Chrome Version 78.0.3904.87 (Official Build) (64-bit)

**Ombi Version (please complete the following information):**
 - Version 3.0.4880
 - Media Server: Plex Version 1.18.1.2019

**Additional context**
This happened after upgrade from `Ombi v3.0.4817`. Everything is run in containers using `linuxserver/ombi` with persistent volume attached.
Excerpt from docker-compose:
```
  ombi:
    image: linuxserver/ombi
    restart: 'always'
    ports:
      - 3579:3579
    networks:
      - web
    volumes:
      - ombi:/config
...
volumes:
  ombi:
```

**Comment by CaptAintHere** [comment]
I'm facing the same issue with latest version 3.0.4880. Movie search doesn't work and there is no cover for TV shows.

**Comment by ZiemusG** [comment]
i have the same problem after update to v3.0.4880
no such column: x.RequestId'.  
My Ombi:
Version	3.0.4880
Branch	master
Github	https://github.com/tidusjar/Ombi
Discord	https://discord.gg/Sa7wNWb
Reddit	https://www.reddit.com/r/Ombi/
Issues	https://github.com/tidusjar/Ombi/issues
Wiki	https://github.com/tidusjar/Ombi/wiki
OS Architecture	X64
OS Description	Linux 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27)
Process Architecture	X64
Application Base Path	/opt/Ombi
Storage Path	/etc/Ombi/
Ombi Database	Sqlite - Data Source=/etc/Ombi/Ombi.db
External Database	Sqlite - Data Source=/etc/Ombi/OmbiExternal.db
Settings Database	Sqlite - Data Source=/etc/Ombi/OmbiSettings.db

**Comment by murac** [comment]
yes me too! everything was solid up till last night

**Comment by tidusjar** [comment]
Can someone please email me the OmbiExternal.db to tidusjar@gmail.com

**Comment by tidusjar** [comment]
Fixed in v3.0.4887

**Comment by rsteckler** [comment]
This is still broken for me on 4890 and 4892.  The Obi system page still says that the DB is Sqlite.

**Comment by tidusjar** [comment]
Run 4887. Then do some searching etc and then upgrade to the latest

**Comment by rsteckler** [comment]
I continue to get the same error on 4887.  
```	
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such column: x.RequestId'.```

**Comment by Spass1966** [comment]
Encountered the same issue. Reverting to 4817 has fixed it.

**Comment by tidusjar** [comment]
@Spass1966 I had thought I'd fixed the issue. That's why the issue is closed. Apologies I cannot monitor the thread 24/7.

For anyone experiencing the issue, please run the following against your SQLite database. Due the the recent changes to the multiple DB providers, if the migrations did not run in the correct order it has caused this issue and it's quite difficult to fix with EF migrations due to some users have the issue, and some dont.

```

ALTER TABLE PlexServerContent ADD COLUMN RequestId INTEGER NULL;
```

**Comment by Spass1966** [comment]
Apologies for the stupid question but how do I access the SQLite database from inside the LinuxServer container? `sqlite3` doesn't seem to be an available command. I've worked with postgresql before and am feeling a little ashamed of my lack of knowledge here.

**Comment by rsteckler** [comment]
I ran the alter table command and still get the error.  I wonder if my error is for a different table.  Here's my full stack trace (though note that it's upside down)
```
	2019-11-18 07:20:56	
at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\Middleware\ErrorHandlingMiddlewear.cs:line 24
2019-11-18 07:20:56	
at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\Middleware\ApiKeyMiddlewear.cs:line 51
2019-11-18 07:20:56	
at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
2019-11-18 07:20:56	
at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
2019-11-18 07:20:56	
at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
2019-11-18 07:20:56	
at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
2019-11-18 07:20:56	
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
2019-11-18 07:20:56	
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
2019-11-18 07:20:56	
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2019-11-18 07:20:56	
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
2019-11-18 07:20:56	
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
2019-11-18 07:20:56	
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
2019-11-18 07:20:56	
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2019-11-18 07:20:56	
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
2019-11-18 07:20:56	
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
2019-11-18 07:20:56	
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
2019-11-18 07:20:56	
at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
2019-11-18 07:20:56	
at lambda_method(Closure , Object )
2019-11-18 07:20:56	
at Ombi.Controllers.SearchController.GetShowInfo(Int32 tvdbId) in C:\projects\requestplex\src\Ombi\Controllers\SearchController.cs:line 274
2019-11-18 07:20:56	
at Ombi.Core.Engine.TvSearchEngine.GetShowInformation(Int32 tvdbid) in C:\projects\requestplex\src\Ombi.Core\Engine\TvSearchEngine.cs:line 120
2019-11-18 07:20:56	
at Ombi.Core.Engine.TvSearchEngine.ProcessResult(SearchTvShowViewModel item) in C:\projects\requestplex\src\Ombi.Core\Engine\TvSearchEngine.cs:line 171
2019-11-18 07:20:56	
at Ombi.Core.Engine.Interfaces.BaseEngine.RunSearchRules(SearchViewModel model) in C:\projects\requestplex\src\Ombi.Core\Engine\Interfaces\BaseEngine.cs:line 53
2019-11-18 07:20:56	
at Ombi.Core.Rule.RuleEvaluator.StartSearchRules(SearchViewModel obj) in C:\projects\requestplex\src\Ombi.Core\Rule\RuleEvaluator.cs:line 54
2019-11-18 07:20:56	
at Ombi.Core.Rule.Rules.Search.PlexAvailabilityRule.Execute(SearchViewModel obj) in C:\projects\requestplex\src\Ombi.Core\Rule\Rules\Search\PlexAvailabilityRule.cs:line 31
2019-11-18 07:20:56	
at Ombi.Store.Repository.PlexServerContentRepository.Get(String providerId) in C:\projects\requestplex\src\Ombi.Store\Repository\PlexContentRepository.cs:line 66
2019-11-18 07:20:56	
at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteSingletonAsyncQuery[TResult](QueryContext queryContext, Func`2 compiledQuery, IDiagnosticsLogger`1 logger, Type contextType)
2019-11-18 07:20:56	
at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
2019-11-18 07:20:56	
at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\AsyncIterator.cs:line 98
2019-11-18 07:20:56	
at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\Select.cs:line 106
2019-11-18 07:20:56	
at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken)
2019-11-18 07:20:56	
at System.Linq.AsyncEnumerable.FirstOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\First.cs:line 144
2019-11-18 07:20:56	
at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
2019-11-18 07:20:56	
at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken)
2019-11-18 07:20:56	
at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, CancellationToken cancellationToken)
2019-11-18 07:20:56	
at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
2019-11-18 07:20:56	
at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
2019-11-18 07:20:56	
at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
2019-11-18 07:20:56	
at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
2019-11-18 07:20:56	
at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
2019-11-18 07:20:56	
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such column: x.RequestId'.
2019-11-18 07:20:56	
Something bad happened, ErrorMiddleware caught this
2019-11-18 07:20:56	
fail: Ombi.ErrorHandlingMiddleware[0]
```

Here's my table schema:
```
sqlite> .schema PlexServerContent
CREATE TABLE IF NOT EXISTS "PlexServerContent" (
    "Id" INTEGER NOT NULL CONSTRAINT "PK_PlexServerContent" PRIMARY KEY AUTOINCREMENT,
    "AddedAt" TEXT NOT NULL,
    "ImdbId" TEXT NULL,
    "Key" INTEGER NOT NULL,
    "Quality" TEXT NULL,
    "ReleaseYear" TEXT NULL,
    "TheMovieDbId" TEXT NULL,
    "Title" TEXT NULL,
    "TvDbId" TEXT NULL,
    "Type" INTEGER NOT NULL,
    "Url" TEXT NULL, RequestId INTEGER NULL,
    CONSTRAINT "AK_PlexServerContent_Key" UNIQUE ("Key")
);
```

Is there a full migration script available somewhere that I can just run and be done?

**Comment by rsteckler** [comment]
@Spass1966 
```
apt update
apt install sqlite3
cd /config
sqlite3 Ombi.db
```

**Comment by dippynark** [comment]
@Spass1966 in the root of my Ombi config volume (`/config` for me) I did `sqlite3 OmbiExternal.db` and then the command that @tidusjar posted above - seems to be working

**Comment by dippynark** [comment]
@rsteckler you applied that to `Ombi.db`? My one doesn't have the `PlexServerContent` table

**Comment by tidusjar** [comment]
Sorry guys apply it to the Ombi external db

**Comment by rsteckler** [comment]
> Sorry guys apply it to the Ombi external db

That worked.  

Thanks!

**Comment by deusxanime** [comment]
I had this problem also and fixed it by running the previously recommended SQL query against OmbiExternal.db

`ALTER TABLE PlexServerContent ADD COLUMN RequestId INTEGER NULL;`

I didn't want to install stuff into my container so I just used the zip version (no install needed on your desktop either) of this [SQLite browser/editor](https://github.com/sqlitebrowser/sqlitebrowser/releases). I stopped my Ombi container, opened the OmbiExternal.db with the SQLite editor program, ran the query above, verified it had added the column into the proper table, saved it, and then started the Ombi container back up again. Everything looks like it working again with movies and TV posters showing up, as well as the "no such columns" error now no longer showing up in the logs.

**Comment by Sibicle** [comment]
Here is a oneliner to fix the issue, assuming you are running in a docker container, your container has `ombi` in the name, your image requires the config dir to be mounted at `/config`, and the host is running Debian, Ubuntu, or a related distro that uses `apt`. If any of these points aren't true, see the details below the command and modify to your needs.

```bash
sudo apt update; \
sudo apt install -y sqlite3; \
sqlite3 $( \
  docker inspect --format '{{ range .Mounts }}{{if eq .Destination "/config"}}{{ .Source }}{{end}}{{end}}'  \
  $(docker ps --filter name=ombi --format '{{.ID}}') \
)/app/OmbiExternal.db 'ALTER TABLE PlexServerContent ADD COLUMN RequestId INTEGER NULL'
```

Explanation of parts:

Update `apt` & install `sqlite3`
```bash
sudo apt update; \
sudo apt install -y sqlite3;
```

Inspect container `$CONTAINER_ID`, list mounts, and if the mount destination is `/config`, print the source
```bash
docker inspect --format \
  '{{ range .Mounts }}{{if eq .Destination "/config"}}{{ .Source }}{{end}}{{end}}'  \
  $CONTAINER_ID
```

List containers, filtering on `ombi`. Format output to only include the container id.
```bash
docker ps --filter name=ombi --format '{{.ID}}'
```

Concatenate the inspected directory path with the path to the `.db` file within the `/config` dir
```bash
$( ... )/app/OmbiExternal.db
```

Tell `sqlite3` to run the actual query
```bash
 sqlite3 /opt/ombi/app/OmbiExternal.db 'ALTER TABLE PlexServerContent ADD COLUMN RequestId INTEGER NULL'
```


After you are done, you can remove `sqlite3`
```bash
sudo apt remove --purge sqlite3
```

**Comment by gtosnipey** [comment]
If anyone could help provide the command equivalents for fixing this on an Unraid server that would be awesome! A bit of a noob here on the sql/command stuff so still trying to find my way around, thanks in advance!

**Comment by Sibicle** [comment]
It looks like Unraid doesn't have a package manager, but luckily there is a standalone binary for `sqlite3` available [here](https://www.sqlite.org/download.html). Binary means the file has been compiled to machine code, standalone means the file knows how to perform its role (look at sqlite `.db` files) without any other files.

First you need to find where the `.db` file is stored. The simplest way to do that is to just search through the entire filesystem starting at `/`.

```bash
find / -name OmbiExternal.db
```

Then you can download the zip file of the `sqlite3` binary,  expand the archive like so, and change into the new directory like so:

```bash
cd ~
wget https://www.sqlite.org/2019/sqlite-tools-linux-x86-3300100.zip
unzip sqlite-tools-linux-x86-3300100.zip
cd sqlite-tools-linux-x86-3300100
```

You need to tell the computer it's allowed to run the binary file, not just look at its contents
```bash
chmod a+x sqlite3
```

Now you should be able to run the query, making sure to replace the path with the correct one from the `find` earlier
```bash
sqlite3 /your/path/here/OmbiExternal.db 'ALTER TABLE PlexServerContent ADD COLUMN RequestId INTEGER NULL'
```

Here it is all in one block (theoretically). I would always be careful copying and pasting stuff like this from the internet, if you don't know what it does.
```bash
cd ~
wget https://www.sqlite.org/2019/sqlite-tools-linux-x86-3300100.zip
unzip sqlite-tools-linux-x86-3300100.zip
cd sqlite-tools-linux-x86-3300100
chmod a+x sqlite3
./sqlite3 $(find / -name OmbiExternal.db -print0 -quit 2>/dev/null) 'ALTER TABLE PlexServerContent ADD COLUMN RequestId INTEGER NULL'
```

**Comment by elynch303** [comment]
still seeing this issue on 

3.0.4890

**Comment by sienar1** [comment]
Was seeing the issue on 3.0.4892, but sqlite3 commands posted above corrected the problem for me

**Comment by elynch303** [comment]
> Was seeing the issue on 3.0.4892, but sqlite3 commands posted above corrected the problem for me

I tried that I'm getting Error: attempt to write a readonly database

**Comment by sienar1** [comment]
stop the ombi service, and use sudo when running the sqlite3 command

**Comment by elynch303** [comment]
> stop the ombi service, and use sudo when running the sqlite3 command

fun i was thinking maybe the service was locking it thank you this worked

**Comment by FenixVale** [comment]
For those not using docker

```
sudo apt-get update && sudo apt install sqlite3
cd /etc/Ombi
sudo sqlite3 OmbiExternal.db
ALTER TABLE PlexServerContent ADD COLUMN RequestId INTEGER NULL;
(Ctrl A+D close Sqlite3)
sudo systemctl restart ombi
```

This should resolve it for you.

/etc/Ombi assumes default install location.

**Comment by Glynnryan** [comment]
> 
> 
> For those not using docker
> 
> ```
> sudo apt-get update && sudo apt install sqlite3
> cd /etc/Ombi
> sudo sqlite3 OmbiExternal.db
> ALTER TABLE PlexServerContent ADD COLUMN RequestId INTEGER NULL;
> (Ctrl A+D close Sqlite3)
> sudo systemctl restart ombi
> ```
> 
> This should resolve it for you.
> 
> /etc/Ombi assumes default install location.

I've tried this and still have the same issue - movie search doesn't work, or movie suggestions.
Version | 3.0.4892

**Comment by sienar1** [comment]
> I've tried this and still have the same issue - movie search doesn't work, or movie suggestions.
> Version | 3.0.4892

Are you getting any errors running the commands?

**Comment by masterzxz** [comment]
> I had this problem also and fixed it by running the previously recommended SQL query against OmbiExternal.db
> 
> `ALTER TABLE PlexServerContent ADD COLUMN RequestId INTEGER NULL;`
> 
> I didn't want to install stuff into my container so I just used the zip version (no install needed on your desktop either) of this [SQLite browser/editor](https://github.com/sqlitebrowser/sqlitebrowser/releases). I stopped my Ombi container, opened the OmbiExternal.db with the SQLite editor program, ran the query above, verified it had added the column into the proper table, saved it, and then started the Ombi container back up again. Everything looks like it working again with movies and TV posters showing up, as well as the "no such columns" error now no longer showing up in the logs.

Thx mate, managed to resolve my issue with your steps.

**Comment by devi59** [comment]
> Here is a oneliner to fix the issue, assuming you are running in a docker container, your container has `ombi` in the name, your image requires the config dir to be mounted at `/config`, and the host is running Debian, Ubuntu, or a related distro that uses `apt`. If any of these points aren't true, see the details below the command and modify to your needs.
> 
> ```shell
> sudo apt update; \
> sudo apt install -y sqlite3; \
> sqlite3 $( \
>   docker inspect --format '{{ range .Mounts }}{{if eq .Destination "/config"}}{{ .Source }}{{end}}{{end}}'  \
>   $(docker ps --filter name=ombi --format '{{.ID}}') \
> )/app/OmbiExternal.db 'ALTER TABLE PlexServerContent ADD COLUMN RequestId INTEGER NULL'
> ```
> 
> Explanation of parts:
> 
> Update `apt` & install `sqlite3`
> 
> ```shell
> sudo apt update; \
> sudo apt install -y sqlite3;
> ```
> 
> Inspect container `$CONTAINER_ID`, list mounts, and if the mount destination is `/config`, print the source
> 
> ```shell
> docker inspect --format \
>   '{{ range .Mounts }}{{if eq .Destination "/config"}}{{ .Source }}{{end}}{{end}}'  \
>   $CONTAINER_ID
> ```
> 
> List containers, filtering on `ombi`. Format output to only include the container id.
> 
> ```shell
> docker ps --filter name=ombi --format '{{.ID}}'
> ```
> 
> Concatenate the inspected directory path with the path to the `.db` file within the `/config` dir
> 
> ```shell
> $( ... )/app/OmbiExternal.db
> ```
> 
> Tell `sqlite3` to run the actual query
> 
> ```shell
>  sqlite3 /opt/ombi/app/OmbiExternal.db 'ALTER TABLE PlexServerContent ADD COLUMN RequestId INTEGER NULL'
> ```
> 
> After you are done, you can remove `sqlite3`
> 
> ```shell
> sudo apt remove --purge sqlite3
> ```

This worked beautifully!

**Comment by requiem240sx** [comment]
I'm on CentOS running Docker Ombi Version: 3.0.4892 (I simply upgraded to this a week ago or so, and Users started saying there was issues...  finally looked at the logs and found some errors that led me to there. 

FYI I spun up a brand new container, and it works fine... but didn't want to re-configure everything.... so was very happy to see some solutions posted here. 

Did as everyone else said prior....

```
yum update -y
yum install libsqlite3x-devel.x86_64 -y
cd ombi/config
docker stop ombi
sqlite3 OmbiExternal.db 'ALTER TABLE PlexServerContent ADD COLUMN RequestId INTEGER NULL'
sudo yum remove libsqlite3x-devel.x86_64 -y
```

AND IT WORKED!  So happy I don't have to re-configure Ombi, thank you everyone!

**Comment by Combatchuck** [comment]
SQL command didn't fix for me. I just had to rebuild as a new docker container, then replace the ombi.settings, and ombi.db after it came up.

**Comment by tidusjar** [comment]
FYI if you dont want to run the script, just delete the OmbiExternal.db and then restart Ombi.

**Comment by soulvoid86** [comment]
> FYI if you dont want to run the script, just delete the OmbiExternal.db and then restart Ombi.

This work for me on #3286 
Thanks!

**Comment by dr0id123** [comment]
> FYI if you dont want to run the script, just delete the OmbiExternal.db and then restart Ombi.

This works.  After restarting docker, simply manually run the cacher/scan against Plex/Emby,

**Comment by Glynnryan** [comment]
> 
> 
> FYI if you dont want to run the script, just delete the OmbiExternal.db and then restart Ombi.

Worked for me, thank you!

**Comment by safnz** [comment]
> 
> 
> FYI if you dont want to run the script, just delete the OmbiExternal.db and then restart Ombi.

+1, worked here too. Thanks!

**Comment by tohaku** [comment]
> oblem also and fixed it by running the previously recommended SQL query against OmbiExternal.db

Thanks for the program recommendation.  I'm running Unraid so this worked great after copying the db to my local machine and using the software to run the sql command.

**Comment by sidscri** [comment]
Hey guys and gals.  I had the same problem after upgrading from v3.0.4817 to latest release and dev. As a test I reverted back to 4817nit worked again. I upgraded to the next upgrade v3.0.4887, the issue came up again. So something is up with the newer versions.  Please help by fixing the issues.  I will also try deleting the ombiexternal.db then restart to see if that fixes the issue for now.

**Comment by sidscri** [comment]
Ok deleting worked. I do have a question though. What am i missing without ombiexternal.db present? does it eventually repopulate the file when it is required?

**Comment by henroFall** [comment]
> 
> 
> I'm on CentOS running Docker Ombi Version: 3.0.4892 (I simply upgraded to this a week ago or so, and Users started saying there was issues... finally looked at the logs and found some errors that led me to there.
> 
> FYI I spun up a brand new container, and it works fine... but didn't want to re-configure everything.... so was very happy to see some solutions posted here.
> 
> Did as everyone else said prior....
> 
> ```
> yum update -y
> yum install libsqlite3x-devel.x86_64 -y
> cd ombi/config
> docker stop ombi
> sqlite3 OmbiExternal.db 'ALTER TABLE PlexServerContent ADD COLUMN RequestId INTEGER NULL'
> sudo yum remove libsqlite3x-devel.x86_64 -y
> ```
> 
> AND IT WORKED! So happy I don't have to re-configure Ombi, thank you everyone!

Confirmed, worked. For those without docker installs, just change to /etc/Ombi (or wherever your "Storage path" shows as at the /Settings/About page. then do 

> sudo sqlite3 OmbiExternal.db 'ALTER TABLE PlexServerContent ADD COLUMN RequestId INTEGER NULL'

**Comment by rutskiuk** [comment]
How do I do this for Windows using DB Browser for SQLite?

**Comment by rutskiuk** [comment]
I may have answered this for myself:

1. Open OmbiExternal.db in DB Browser for SQLite
2. Make the changes detailed above (go to the PlexServerContent table, modify table, Add field, RequestId, select the type as INTEGER and leave the NN (null) field unticked)
3. Export the database to a SQL file (File >Export > Database to SQL file > Select Name > OK)
4. Import the SQL file (File > Import > Database from SQL file > Select the modified SQL file you saved earlier
5. Save a new database in the same location as OmbiExternal.db and call it what you like
6. Replace the OmbiExternal.db with your new file (I tend to give the new file the old file's name add an x to the old file name just in case)
7. Restart Ombi

I hope that helps someone

**Comment by JRussell** [comment]
> 
> 
> I may have answered this for myself:
> 
>     1. Open OmbiExternal.db in DB Browser for SQLite
> 
>     2. Make the changes detailed above (go to the PlexServerContent table, modify table, Add field, RequestId, select the type as INTEGER and leave the NN (null) field unticked)
> 
>     3. Export the database to a SQL file (File >Export > Database to SQL file > Select Name > OK)
> 
>     4. Import the SQL file (File > Import > Database from SQL file > Select the modified SQL file you saved earlier
> 
>     5. Save a new database in the same location as OmbiExternal.db and call it what you like
> 
>     6. Replace the OmbiExternal.db with your new file (I tend to give the new file the old file's name add an x to the old file name just in case)
> 
>     7. Restart Ombi
> 
> 
> I hope that helps someone

I did this but skipped steps 3-5. Not sure why you export/import. Is there a reason I'm missing for those steps? As soon as I added the field it was good to go and I just copied it back to the docker volume.

**Comment by skettydog** [comment]
This is still an issue on a brand new install. I'm experiencing this on a brand new install on v3.0.4892. I'm getting the same error as everyone else: 'no such column: x.RequestId.'

**Comment by Tripwyr** [comment]
I am having the same issue. Adding x.RequestId eliminates that error, but I still get 'no such column: x.TotalSeasons' and 'no such column: x.RequestedByAlias'. TV search works fine, Movie search, Movie Requests, and TV Requests are all broken.

**Comment by jneljeff** [comment]
Same issue on a fresh install running 4892.  In addition, movie requests are not being sent to radarr.  Nothing appears in the logs from these actions.

**Comment by ronso21** [comment]
Same issue on latest develop build 3.0.4958

**Comment by alexwitherspoon** [comment]
I can confirm a fresh install of 4892 had the symptom of Radarr/Movies not searching/responding. Deleting "OmbiExternal.db" and restarting Ombi then resumed expected functionality. Below was the observed error I saw repeated many times in the logs. Happy to diagnose more if I could be pointed in a direction.

```
2020-01-13 22:41:32.797 +00:00 [Error] Something bad happened, ErrorMiddleware caught this
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such column: x.RequestId'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.FirstOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\First.cs:line 144
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore(CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\Select.cs:line 106
   at System.Linq.AsyncEnumerable.AsyncIterator`1.MoveNext(CancellationToken cancellationToken) in D:\a\1\s\Ix.NET\Source\System.Interactive.Async\AsyncIterator.cs:line 98
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteSingletonAsyncQuery[TResult](QueryContext queryContext, Func`2 compiledQuery, IDiagnosticsLogger`1 logger, Type contextType)
   at Ombi.Store.Repository.PlexServerContentRepository.Get(String providerId) in C:\projects\requestplex\src\Ombi.Store\Repository\PlexContentRepository.cs:line 66
   at Ombi.Core.Rule.Rules.Search.PlexAvailabilityRule.Execute(SearchViewModel obj) in C:\projects\requestplex\src\Ombi.Core\Rule\Rules\Search\PlexAvailabilityRule.cs:line 31
   at Ombi.Core.Rule.RuleEvaluator.StartSearchRules(SearchViewModel obj) in C:\projects\requestplex\src\Ombi.Core\Rule\RuleEvaluator.cs:line 54
   at Ombi.Core.Engine.Interfaces.BaseEngine.RunSearchRules(SearchViewModel model) in C:\projects\requestplex\src\Ombi.Core\Engine\Interfaces\BaseEngine.cs:line 53
   at Ombi.Core.Engine.TvSearchEngine.ProcessResult(SearchTvShowViewModel item) in C:\projects\requestplex\src\Ombi.Core\Engine\TvSearchEngine.cs:line 171
   at Ombi.Core.Engine.TvSearchEngine.GetShowInformation(Int32 tvdbid) in C:\projects\requestplex\src\Ombi.Core\Engine\TvSearchEngine.cs:line 120
   at Ombi.Controllers.SearchController.GetShowInfo(Int32 tvdbId) in C:\projects\requestplex\src\Ombi\Controllers\SearchController.cs:line 274
   at lambda_method(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext)
   at Ombi.ApiKeyMiddlewear.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\Middleware\ApiKeyMiddlewear.cs:line 51
   at Ombi.ErrorHandlingMiddleware.Invoke(HttpContext context) in C:\projects\requestplex\src\Ombi\Middleware\ErrorHandlingMiddlewear.cs:line 24
```

**Comment by vanderby** [comment]
@tidusjar It appears the EF migrations are not running on startup after upgrading. I am using SQLite.

Looking at the __EFMigrationsHistory table the last few entries I have are:
20180928201334_Votes	2.1.3-rtm-32065
20181204084915_RequestQueue	2.1.3-rtm-32065
20191102235658_Inital	2.2.6-servicing-10079

In the source code I see there are these migration files that didn't get applied:
\src\Ombi.Store\Migrations\20190104203305_LanguageCode.Designer.cs
\src\Ombi.Store\Migrations\20190116212601_RequestedByAlias.Designer.cs
\src\Ombi.Store\Migrations\20190216224539_Roles.Designer.cs
\src\Ombi.Store\Migrations\20190216231519_TvRequestsTotalSeasons.Designer.cs
\src\Ombi.Store\Migrations\20191016203035_RequestIdOnPlexContent.Designer.cs

These migrations add the columns that are called out in the error messages.

**Comment by vanderby** [comment]
@tidusjar  It appears the EF migrations are not running after upgrading or they are purposefully being skipped in favour of the SQLite Initial script which has an issue with CreateTable vs alterTable for upgrade (see my last paragraph below). I am using SQLite.

Looking at the Ombi.db __EFMigrationsHistory table the last few entries I have are:
20180928201334_Votes 2.1.3-rtm-32065
20181204084915_RequestQueue 2.1.3-rtm-32065
20191102235658_Inital 2.2.6-servicing-10079

In the source code I see there are these migration files that didn't get applied:
\src\Ombi.Store\Migrations\20190104203305_LanguageCode.Designer.cs
\src\Ombi.Store\Migrations\20190116212601_RequestedByAlias.Designer.cs
\src\Ombi.Store\Migrations\20190216224539_Roles.Designer.cs
\src\Ombi.Store\Migrations\20190216231519_TvRequestsTotalSeasons.Designer.cs
\src\Ombi.Store\Migrations\20191016203035_RequestIdOnPlexContent.Designer.cs

These migrations add the columns that are called out in the error messages. 

The 20191102235658_Inital 2.2.6-servicing-10079 has create table calls with the appropriate columns for SQLite, but since the tables already exist from a previous installation I suspect they don't modify an existing table. If we're upgrading from a previous installation we would want to use the AlterTable() call instead of CreateTable().

**Comment by fireheadman** [comment]
same issue... new install.   Took maybe 3 days for this to get into this condition.
Tried remediation by deleting the OmbiExternal.db (stopped app first, then started after removal).
THe DB recreated itself, but still nothing showing in the Movies.   Does work for TV Shows.

DO see lots of errors in the Logs dir.  (log-20200126.txt).

**Comment by thenamelessthing** [comment]
I have the same problem, fresh install from : 

3.0.4892 under ubuntu 16.04.3
--

**Comment by thu3n** [comment]
same here, same output like fireheadman

**Comment by tidusjar** [comment]
Cannot reproduce this issue on the latest version of ombi. Closing this for now as all the issues in here being raised are already covered above.

If you think you genuinely have an issue please raise a new issue on github.
