### ISSUE TITLE
Unable to Send Newsletter Test

### ISSUE THREAD

**Issue by jwor80** [tidusjar/Ombi#3445]
**Describe the bug**
When I attempt to send a newsletter test an e-mail is never received for the admin accounts. An error is found in the log file.

**To Reproduce**
1. Go to Notifications
2. Click on Newsletter
3. Scroll down to Test and click
4. See error in log

**Expected behavior**
Successfully receive a newsletter e-mail.

**Screenshots**

**Logs (Logs directory where Ombi is located)**
2020-03-24 20:17:22.322 -05:00 [Error] Could not test Newsletter
System.InvalidOperationException: The LINQ expression 'DbSet<PlexServerContent>
    .Where(p => (int)p.Type == 0 && p.HasTheMovieDb)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.<VisitMethodCall>g__CheckTranslated|8_0(ShapedQueryExpression translated, <>c__DisplayClass8_0& )
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator()
   at System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   at System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToHashSet[TSource](IEnumerable`1 source, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToHashSet[TSource](IEnumerable`1 source)
   at Ombi.Schedule.Jobs.Ombi.NewsletterJob.Start(NewsletterSettings settings, Boolean test)
   at Ombi.Schedule.Jobs.Ombi.NewsletterJob.Start(NewsletterSettings settings, Boolean test) in /home/vsts/work/1/s/src/Ombi.Schedule/Jobs/Ombi/NewsletterJob.cs:line 316
   at Ombi.Controllers.V1.External.TesterController.NewsletterTest(NewsletterNotificationViewModel settings) in /home/vsts/work/1/s/src/Ombi/Controllers/V1/External/TesterController.cs:line 449
2020-03-24 20:17:39.916 -05:00 [Debug] Batch acquisition of 0 triggers

**Desktop (please complete the following information):**
 - OS: Windows 10 64-bit

**Ombi Version (please complete the following information):**
 - Version 4.0.280.0
- Media Server Emby

**Additional context**
Trigger now fails as well as the test.

**Comment by tidusjar** [comment]
Should be fixed in the latest version now

**Comment by jwor80** [comment]
I'm still seeing the issue in 4.0.282.0

2020-03-25 07:57:31.103 -05:00 [Error] Could not test Newsletter
System.InvalidOperationException: The LINQ expression 'DbSet<LidarrAlbumCache>
    .Where(l => l.FullyAvailable)' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync(). See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.<VisitMethodCall>g__CheckTranslated|8_0(ShapedQueryExpression translated, <>c__DisplayClass8_0& )
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Ombi.Schedule.Jobs.Ombi.NewsletterJob.Start(NewsletterSettings settings, Boolean test) in /home/vsts/work/1/s/src/Ombi.Schedule/Jobs/Ombi/NewsletterJob.cs:line 145
   at Ombi.Schedule.Jobs.Ombi.NewsletterJob.Start(NewsletterSettings settings, Boolean test) in /home/vsts/work/1/s/src/Ombi.Schedule/Jobs/Ombi/NewsletterJob.cs:line 316
   at Ombi.Controllers.V1.External.TesterController.NewsletterTest(NewsletterNotificationViewModel settings) in /home/vsts/work/1/s/src/Ombi/Controllers/V1/External/TesterController.cs:line 449
2020-03-25 07:57:49.303 -05:00 [Debug] Batch acquisition of 0 triggers

**Comment by tidusjar** [comment]
@jwor80 Just pushed out another build that will resolve your issue. I missed music

**Comment by jwor80** [comment]
Thank you! The newsletter was successful

**Comment by tidusjar** [comment]
I mentioned it in my comment above.
