### ISSUE TITLE
no favicon when using reserve proxy

### ISSUE THREAD

**Issue by ksbansal** [tidusjar/Ombi#547]
If this is a bug report please make sure you have filled the following in:
(If it's not a bug and a feature request then just remove the below)
#### Plex Requests.Net Version:

1.9.2
#### Operating System:

windows
#### Applicable Logs (from `/logs/` directory or the Admin page):

```
Logs go here (Please make sure you remove any personal information from the logs)
```
#### Reproduction Steps:

use base url option
Please include any steps to reproduce the issue, this the request that is causing the problem etc.

Not sure if this is because of Plex requests net or because of the way I set my reserve proxy.

**Comment by ksbansal** [comment]
Just figured out its definitely plex requests net.
Here's an example of what happens:
So it should be mydomain.com/plex/favicon.ico       <--my base url is plex
iInstead it stays at mydomain.com:"port here"/favicon.ico

**Comment by colemoine** [comment]
hmm i'm still having this same issue with 1.9.4 on ubuntu 16.10 mono 4.2.1

**Comment by SuperPotatoMen** [comment]
Fixed in the next release!

**Comment by colemoine** [comment]
Still having this issue with with the favicon and reverse proxy, seems like its looking for the favicon.ico at https://customurl.net/favicon.ico instead of https://customurl.net/content/favicon.ico which is causing the 403 error, let me know if you need more info did a clean install of 1.10 minus the .sqlite file

**Comment by tidusjar** [comment]
Tried clearing the cache?

**Comment by SuperPotatoMen** [comment]
@colemoine did you clearing your browser cache first?
