### ISSUE TITLE
no pushover notification when new movies are added

### ISSUE THREAD

**Issue by phairplay** [tidusjar/Ombi#832]
### Ombi Version:

V 1.10.1

#### Update Branch:

Stable

#### Operating System:

windows 10 

#### Applicable Logs (from `/logs/` directory or the Admin page):
```
Message
Area
Log Level
Date
Adding movie to CP result True
PlexRequests.UI.Modules.SearchModule
Debug
12/22/2016 8:58:46 PM
We are authenticated! Setting session.
PlexRequests.UI.Modules.UserLoginModule
Debug
12/22/2016 8:57:25 PM
Friends list result = True
PlexRequests.UI.Modules.UserLoginModule
Debug
12/22/2016 8:57:25 PM
User is the account owner
PlexRequests.UI.Modules.UserLoginModule
Debug
12/22/2016 8:57:25 PM
```
#### Problem Description:
i dont recieve a pushover notification when new movies are added. ive checked the settings and the test works. 

#### Reproduction Steps:
in the main plex request options "do not send notifications for requests that don't require approval"
is unticked.

**Comment by FunkMast3rFlex** [comment]
This is the same for me with all three applications but I think this is being worked on the for the next update release.

**Comment by tidusjar** [comment]
This has been fixed in the Early Access Preview branch.

**Comment by FunkMast3rFlex** [comment]
Thanks

**Comment by phairplay** [comment]
hi sorry but i've just upgraded to your latest version 2.0.1 and pushover still doesnt work
