### ISSUE TITLE
Emails notifications triplicated 

### ISSUE THREAD

**Issue by rulles** [tidusjar/Ombi#835]
#### Ombi Version:

V 1.10.1

#### Update Branch:

Stable

#### Operating System:

CentOS 7

#### Mono Version (only if your not on windows)

mono 4.2.4-7.el7

#### Applicable Logs (from `/logs/` directory or the Admin page):

```
PlexContent.ProviderId may not be NULL
  at Mono.Data.Sqlite.SQLite3.Reset (Mono.Data.Sqlite.SqliteStatement stmt) <0x41f6d550 + 0x0021b> in <filename unknown>:0 
  at Mono.Data.Sqlite.SQLite3.Step (Mono.Data.Sqlite.SqliteStatement stmt) <0x41f6d170 + 0x0011a> in <filename unknown>:0 
  at Mono.Data.Sqlite.SqliteDataReader.NextResult () <0x41f6b000 + 0x004d7> in <filename unknown>:0 
  at Mono.Data.Sqlite.SqliteDataReader..ctor (Mono.Data.Sqlite.SqliteCommand cmd, CommandBehavior behave) <0x41f6adc0 + 0x00135> in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) Mono.Data.Sqlite.SqliteDataReader:.ctor (Mono.Data.Sqlite.SqliteCommand,System.Data.CommandBehavior)
  at Mono.Data.Sqlite.SqliteCommand.ExecuteReader (CommandBehavior behavior) <0x41f6a400 + 0x0003b> in <filename unknown>:0 
  at Mono.Data.Sqlite.SqliteCommand.ExecuteDbDataReader (CommandBehavior behavior) <0x41fa83f0 + 0x00013> in <filename unknown>:0 
  at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader (CommandBehavior behavior) <0x41fa83c0 + 0x00018> in <filename unknown>:0 
  at Dapper.SqlMapper.QueryMultipleImpl (IDbConnection cnn, Dapper.CommandDefinition& command) <0x4185cbb0 + 0x0020e> in <filename unknown>:0 
2016/12/23 12:00:41.265 PlexRequests.Services.Notification.NotificationEngine Info: Notifying user User01 
2016/12/23 12:00:41.277 PlexRequests.Services.Notification.NotificationEngine Info: Sending notification to: User01  at: user01@email.com, for title: SomeContent
2016/12/23 12:00:41.719 PlexRequests.Services.Notification.EmailMessageNotification Info: sending message to "user01@email.com" <user01@email.com> 
 from: "sender@email.com" <sender@email.com>
 Are we authenticated: True 
2016/12/23 12:00:42.121 PlexRequests.Services.Notification.NotificationEngine Info: Notifying user User01  
2016/12/23 12:00:42.125 PlexRequests.Services.Notification.NotificationEngine Info: Sending notification to: User01  at: user01@email.com, for title: SomeContent
2016/12/23 12:00:42.660 PlexRequests.Services.Notification.EmailMessageNotification Info: sending message to "user01@email.com" <user01@email.com> 
 from: "sender@email.com" <sender@email.com>
 Are we authenticated: True 
2016/12/23 12:00:44.343 PlexRequests.Services.Notification.NotificationEngine Info: Notifying user User01  
2016/12/23 12:00:44.347 PlexRequests.Services.Notification.NotificationEngine Info: Sending notification to: User01  at: user01@email.com, for title: SomeContent
2016/12/23 12:00:44.895 PlexRequests.Services.Notification.EmailMessageNotification Info: sending message to "user01@email.com" <user01@email.com> 
 from: "sender@email.com" <sender@email.com>
 Are we authenticated: True
```

#### Problem Description:

Hello, i realized one problem. When some user do some request and when i insert that content in my plex server, the user receive 3 emails notifications. Have some way to don´t send 3 emails exactly equals?

Other thing i want to do is custom the emails notifications, alter text and other things but cannot find option to do.

#### Reproduction Steps:

Do some request and after that insert the content in plex server, wait for the cronjob and that user who did the request, will receive 3 notifications.

**Comment by SuperPotatoMen** [comment]
@rulles thanks for you report, Tidusjar will you help soon with this problem.


> Oter thing i want to do is custom the emails notifications, alter text and other things but cannot find option to do.

We have planned feature to customize your notifications, it will be in our notifcation update.

**Comment by tidusjar** [comment]
This is live in the Early Access Preview Branch

**Comment by rulles** [comment]
But the Early Access Preview Branch is stable enough to put in production?

The Early Access Preview Branch resolve what of my questions? The emails
custom or the triplicated emails notifications?



Atenciosamente/ With best Regards,
António Pinto

2016-12-28 12:43 GMT+00:00 Jamie <notifications@github.com>:

**Comment by tidusjar** [comment]
The notifications trippling has been fixed. 

The early access preview branch is currently pretty stable, there are not many big breaking changes, I suggest you install it in another folder (The EAP branch contains the new name change so it will need to be a fresh install anyway) and then copy your database over (PlexRequests.sqlite)

**Comment by rulles** [comment]
So the EAP branch fix the problem with the notifications trippling only or
allow custom emails too? If i use the stable (v1.10.1) not fixed yet in
that version??


Atenciosamente/ With best Regards,
António Pinto

2016-12-28 14:46 GMT+00:00 Jamie <notifications@github.com>:

**Comment by tidusjar** [comment]
Only the notification trippling has been fixed in the Early Access Preview. This has not been fixed in Stable yet.
