### ISSUE TITLE
User gets invalid path message adding a TV show

### ISSUE THREAD

**Issue by pauldgifford** [tidusjar/Ombi#994]
#### Ombi Version:

v 2.0.1284

#### Update Branch:

Early Access Preview

#### Operating System:

macOS Sierra 10.12.2 (16C67)

#### Mono Version (only if your not on windows)

Mono JIT compiler version 4.2.4

#### Applicable Logs (from `/logs/` directory or the Admin page):

```

`Exception when calling GetRootFolders for Sonarr, Retrying 00:00:10	Ombi.Api.SonarrApi	Error`

`System.Net.WebException: The request timed out at System.Net.HttpWebRequest.EndGetResponse (IAsyncResult asyncResult) <0x54d0a40 + 0x00177> in :0 at System.Net.HttpWebRequest.GetResponse () <0x54cd298 + 0x0004c> in :0 at RestSharp.Http.GetRawResponse (System.Net.HttpWebRequest request) <0x54ccfd8 + 0x00024> in :0	Ombi.Api.ApiRequest	Error
`
```

#### Problem Description:

User gets invalid path message adding a TV show:

![Error Screenshot](https://www.dropbox.com/s/iaj6vsbgb0gobmt/screenshot_20170124-193240_720.png?raw=1)

#### Reproduction Steps:

In admin > Sonarr
Use Get root folders and click submit. 

(Radarr works perfectly for me btw)

**Comment by tidusjar** [comment]
That's strange!

In your settings, is there any values in your root folder?

**Comment by pauldgifford** [comment]
The value's populate and I select the correct path and hit submit.  I close my browser and go back and it's not selected any longer.

**Comment by porkie02** [comment]
Im getting Invalid path too with sonarr, docker and version 2.0.1282. radarr works fine but it has the old path method. When I try sonarr on older versions its works fine but it has old path method.

`Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Ombi.Api.Models.Sonarr.SonarrAddSeries' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly. To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array. Path '', line 1, position 1. at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract) [0x00058] in <607e95f78559498690f968784b884761>:0 at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, System.Object existingValue, System.String id) [0x00012] in <607e95f78559498690f968784b884761>:0 at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal (Newtonsoft.Json.JsonReader reader, System.Type objectType, Newtonsoft.Json.Serialization.JsonContract contract, Newtonsoft.Json.Serialization.JsonProperty member, Newtonsoft.Json.Serialization.JsonContainerContract containerContract, Newtonsoft.Json.Serialization.JsonProperty containerMember, System.Object existingValue) [0x0007f] in <607e95f78559498690f968784b884761>:0 at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize (Newtonsoft.Json.JsonReader reader, System.Type objectType, System.Boolean checkAdditionalContent) [0x0007a] in <607e95f78559498690f968784b884761>:0	Ombi.Api.SonarrApi	Error	1/25/2017 6:53:30 PM
Exception when calling AddSeries for Sonarr, Retrying 00:00:02	Ombi.Api.SonarrApi	Error	1/25/2017 6:53:27 PM
System.Runtime.Serialization.SerializationException: Invalid JSON string at RestSharp.SimpleJson.DeserializeObject (System.String json) [0x0000c] in :0 at RestSharp.Deserializers.JsonDeserializer.FindRoot (System.String content) [0x00000] in :0 at RestSharp.Deserializers.JsonDeserializer.Deserialize[T] (RestSharp.IRestResponse response) [0x00007] in :0 at RestSharp.RestClient.Deserialize[T] (RestSharp.IRestRequest request, RestSharp.IRestResponse raw) [0x0005c] in :0	Ombi.Api.ApiRequest	Error	1/25/2017 6:53:24 PM
System.Runtime.Serialization.SerializationException: Invalid JSON string at RestSharp.SimpleJson.DeserializeObject (System.String json) [0x0000c] in :0 at RestSharp.Deserializers.JsonDeserializer.FindRoot (System.String content) [0x00000] in :0 at RestSharp.Deserializers.JsonDeserializer.Deserialize[T] (RestSharp.IRestResponse response) [0x00007] in :0 at RestSharp.RestClient.Deserialize[T] (RestSharp.IRestRequest request, RestSharp.IRestResponse raw) [0x0005c] in :0	Ombi.Api.ApiRequest	Error	1/25/2017 6:53:23 PM
Failed to obtain Plex libraries	Ombi.Services.Jobs.PlexContentCacher	Error	1/25/2017 6:50:34 PM
Port: 0	Ombi.UI.Program	Trace	1/25/2017 6:46:14 PM
Getting startup Port	Ombi.UI.Program	Trace	1/25/2017 6:46:13 PM`

**Comment by VanCityGuy** [comment]
Same thing happening to me. I fill out the settings in the Sonarr settings and get paths from the drop down menu. When I select the path, and hit submit, and try to add a TV show, I get: `Error from Sonarr: Invalid Path`

**Comment by tidusjar** [comment]
Can you guys try the latest EAP branch and redo your Sonarr settings? There was a small bug in the sonarr settings that I fixed in the latest eap

**Comment by VanCityGuy** [comment]
Still having the same issue. Though I cannot fully clear and save sonarr settings to re-do them because it requires me to input an API key before saving.

Is there a way to clean the Sonarr settings manually?

**Comment by tidusjar** [comment]
Excellent, can you raise a separate issue for that ?

**Comment by pauldgifford** [comment]
Strange - I am still having the same issue and it is taking a very long time to query and get the root values.

**Comment by tidusjar** [comment]
@pauldgifford It should take milliseconds... Can you just clear your cache to be sure?

**Comment by pauldgifford** [comment]
Boom - fixed with 2.0.1293

thanks man!

**Comment by mow4cash** [comment]
Ombi Version:

v 2.1.1336
Update Branch:

	Stable

Operating System:

FreeBsd

Mono Version (only if your not on windows)

4.6.2 (Stable 4.6.2.7/08fd525 Tue Jan 17 01:47:51 UTC 2017)

Applicable Logs (from /logs/ directory or the Admin page):
```
System.Runtime.Serialization.SerializationException: Invalid JSON string at RestSharp.SimpleJson.DeserializeObject (System.String json) [0x0000c] in :0 at RestSharp.Deserializers.JsonDeserializer.FindRoot (System.String content) [0x00000] in :0 at RestSharp.Deserializers.JsonDeserializer.Deserialize[T] (RestSharp.IRestResponse response) [0x00007] in :0 at RestSharp.RestClient.Deserialize[T] (RestSharp.IRestRequest request, RestSharp.IRestResponse raw) [0x0005c] in :0
```
